### ISSUE TITLE
Dismiss 'New Thread' modal on success

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#10]
Currently, there is a delay when creating a new thread. The 'thread created' message appears, but the modal is still open.

![peek 2017-07-14 21-25](https://user-images.githubusercontent.com/17307/28225374-1d741cde-68db-11e7-9b11-d434125eafbe.gif)

Determine how to optimize the flow when users create new threads, so they receive immediate feedback on success. I.e. the modal might close at the same time the success message displays (while triggering redirect is in progress).

**Comment by AbhijithGanesh** [comment]
I have closed this since changes have been merged
