### ISSUE TITLE
FEAT: We need a template for Feature

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1000]
## Description

It is quite paradoxical that I am creating this issue using a Bug template, we need a template for Issue and feedback. It will be useful to the community to develop in a better way.

**Comment by brylie** [comment]
Indeed. Would you like to create the "Feature" issue template/form?

**Comment by AbhijithGanesh** [comment]
I would like to  be assigned

**Comment by brylie** [comment]
OK, I've assigned you. Thanks!

**Comment by AbhijithGanesh** [comment]
Fixed the 1000th issue of this community 😃
