### ISSUE TITLE
Integrating FastAPI

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1009]
### Idea summary

Instead of using DRF, the project may use FastAPI for the API to increase speed and effectivity of the API.

### Further details

I am glad that you asked about this:
(I am not plugging my article in here but I believe it will be super useful)
https://dev.to/abhijithganesh/what-does-it-take-to-build-an-unconventional-rest-api-in-python-3oog

Also It is integrated through ASGI/WSGI
(EXAMPLE)
```python
import os
from django.apps import apps
from django.core.wsgi import get_wsgi_application
from django.conf import settings



os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'StudentCMS.settings')
apps.populate(settings.INSTALLED_APPS)

from fastapi import FastAPI
from starlette.staticfiles import StaticFiles
from starlette.routing import Mount
from fastapi.middleware.wsgi import WSGIMiddleware
from starlette.middleware.cors import CORSMiddleware
from api.routes import student_router as router
from api.auth_user_router import LoginRouter

def get_application():
    """
    routes = [
        Mount("/static", app=StaticFiles(directory='static'), name = 'static'),
        Mount("/", WSGIMiddleware(get_wsgi_application())),
    ]
    These routes can be mounted as an array if you compromise on static files
    """
    app = FastAPI(title = settings.PROJECT_NAME, debug = settings.DEBUG, redoc_url="/inner-docs")
    app.include_router(router, prefix = "/api")
    app.include_router(LoginRouter, prefix="/security")
    app.mount("/static", app=StaticFiles(directory='static'), name = 'static')
    app.mount("/", WSGIMiddleware(get_wsgi_application()))
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.ALLOWED_HOSTS,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )
    return app

app = get_application()

```
A Small Downside would be: We need to collectstatic before being deployed. Usually heroku does this for us (if DISABLE COLLECTSTATIC isn't configured)

**Comment by brylie** [comment]
What is the performance of the existing API-related code? How would we serialize/deserialize response and request payloads into Django ORM objects using the FastAPI architecture?

**Comment by brylie** [comment]
How would we implement access control using Django accounts/roles within the FastAPI architecture?

**Comment by AbhijithGanesh** [comment]
> 
> 
> How would we implement access control using Django accounts/roles within the FastAPI architecture?

To implement access control using Django, we'll have to use django.contrib.auth.models and Import User from that module. In my opinion, it is the only disadvantage we'll be facing (because DRF has better support for user authentication)

**Comment by AbhijithGanesh** [comment]
> 
> 
> What is the performance of the existing API-related code? How would we serialize/deserialize response and request payloads into Django ORM objects using the FastAPI architecture?

I need sometime to give you an elaborate explanation, I shall inspect this repository's code and shall give you a clear picture

**Comment by brylie** [comment]
We need a clear justification for making a substantial change and replacing the existing API code. 

- Benchmarks for comparison
- Holistic thinking about the benefits/limitations of DRF
- Research on established patterns in the Django ecosystem

CiviWiki is a conventional project and we're trying to simplify our dependencies. Any ideas outside of widely adopted and documented Django "best practices" need to be vetted.

**Comment by AbhijithGanesh** [comment]
Firstly,  The data and research on this concept is not available because of its unconventional appraoch. I have never seen this being implemented on a project of this scale but at the same time I can assure the contributors this concept might be useful in changing inefficient practices. I am working on the benchmarks and I shall soon update them here.

**Comment by wassafshahzad** [comment]
I think we can improve performance using async views for DRF as well.However only if performance optimization is needed.
I agree with @brylie  comments, straying away from best practices could come to bite use later on.

**Comment by AbhijithGanesh** [comment]
I think then we need to raise a new ticket on using DRF async views to improvize efficiency.
