### ISSUE TITLE
Concept for Simplified CiviWiki Design for Next Milestone

### ISSUE THREAD

**Issue by mdwest** [CiviWiki/OpenCiviWiki#101]
The following is a proposal for a simplified version of CiviWiki we should be able to achieve in the next development cycle.  

Simplified linking: Problems link to nothing. Causes Link to Problems, Solutions link to Causes.

Simplified Bills: No Bill Tracking (yet). But, solution civies include space to link bill text document (Traditional upload limited to certain recognized document types - virus safe preferably?), as well as space to identify the local, state or federal actor. 

Simplified Bills Part 2 : To give this impact, we must create a simple system to export spreadsheet information on how many users registered within a relevant district support or oppose any given solution (Relevant District = local, congressional district, state, federal, international). 

Remove the Beta Blocker: Remove beta blocker and allow anyone to use the invite system to solicit new members via email. 

Vission for this Milestone: With a stable system to write civies that terminate in an identifiable call of action (Bill, ordinance, executive order), addressed to an institutional actor (President, Congress, state legislature, local rep). We can automatically produce petition documents. Though an incomplete version of Civiwiki, this milestone would allow us to test our discussion system while developing useful data to petition representatives. 

Include thoughts or ask clarifying questions below

**Comment by brylie** [comment]
I would recommend just using a URL instead of file upload (for the time being).

**Comment by brylie** [comment]
Regarding *point 2*, lets just stick with HTML templates for now (if we all agree). CSV or spreadsheet export seems, intuitively to me, to be more complicated than sticking close to Django template rendering.

**Comment by brylie** [comment]
Regarding the *institutional scope*, lets start with the following:

- country
- state
- city

We can build in more refined grouping in a later milestone, once we start working with APIs.

**Comment by pscheid2** [comment]
This discussion has moved to the loomio platform

https://www.loomio.org/d/APNvQoVT/concept-for-simplified-civiwiki-design-for-next-milestone
