### ISSUE TITLE
Squash migrations

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1017]
### Idea summary

Requirement for less migrations

### Further details

Can we squash/merge migrations, it seems bulky. Is there a way to reduce the number of migrations

**Comment by brylie** [comment]
Yes, this seems reasonable since we are still in a "beta" development stage.

**Comment by AbhijithGanesh** [comment]
I'd like to claim this issue

**Comment by AbhijithGanesh** [comment]
PS:I am working on the FastAPI integration concept, the serializers and api calls in this project is way too complex for me to work on quickly, It is a promising idea but  I am personally running short of time to make this happen.

**Comment by brylie** [comment]
For the time being, I believe the FastAPI concept is not appropriate for this project. We want to write really conventional code, and the FastAPI/Django combination doesn't seem common or well documented.

Let's focus our limited time on core improvements to the project.

**Comment by AbhijithGanesh** [comment]
> 
> 
> For the time being, I believe the FastAPI concept is not appropriate for this project. We want to write really conventional code, and the FastAPI/Django combination doesn't seem common or well documented.
> 
> Let's focus our limited time on core improvements to the project.

Points well noted, thank you.

**Comment by AbhijithGanesh** [comment]
**Tasks**
- [x] Accounts
- [x] api

**Comment by AbhijithGanesh** [comment]
Since the PR is merged, I am closing this
