### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by gorkemarslan** [CiviWiki/OpenCiviWiki#1020]
### Description

Translation texts are not be rendered as expected:

The picture below is taken after going to the URL `/profile/<username>/`:

<img width="978" alt="Screen Shot 2021-09-18 at 19 43 57" src="https://user-images.githubusercontent.com/16780927/133896120-53730698-602b-44a1-83d8-c7c7cb6f6203.png">

The related code line can be found in `project/threads/templates/threads/partials/account/tabs/my_civis.html`:

`<div class="col s6 title-lato">{% trans "My Civi Activity" %} </div>`

### What browser(s) are you seeing the problem on?

Chrome

**Comment by adityamittl** [comment]
I solved this issue.

**Comment by brylie** [comment]
Closing as solved by #1060
