### ISSUE TITLE
Bad Migration Tree

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1022]
### Description

When I was trying to squash migrations of the api , there seems to be an issue related to the whole ancestry of migrations, I am working on this as a part of  #1017. The parent tree appears to be slightly displaced which I'll be looking forward to patch with the other issue mentioned.

### Further details

![image](https://user-images.githubusercontent.com/67182544/133898380-dfa08f6f-9c27-4de8-aca9-ba3b58b99873.png)

**Comment by AbhijithGanesh** [comment]
Subsequently, it also leads us to errors when accounts are merged, I shall not be creating a PR with error-causing code for this project. It is in bad-faith to put in a temporary fix which will not fix the issue holistically. I am sure @brylie and the community will understand.

![image](https://user-images.githubusercontent.com/67182544/133898490-3f8d3f07-8c25-47d1-96bd-8443e5019e57.png)

**Comment by AbhijithGanesh** [comment]
![image](https://user-images.githubusercontent.com/67182544/133898625-3f6c1d06-ff11-42ce-b201-9371dacc2040.png)
Unfortunately, 0041 on Api has a dependency on one of the squashed migrations and this circular dependency needs to be fixed. (I'll most likely add this to my squashing part)

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, I am auditing PR #1023. Is this issue caused before or after the PR? I mean have we had this problem for a long time? I guess we have. Right?

**Comment by AbhijithGanesh** [comment]
> @AbhijithGanesh, I am auditing PR #1023. Is this issue caused before or after the PR? I mean have we had this problem for a long time? I guess we have. Right?
> 

This is chronologically super old, it is caused before the PR. I think the PR applies a temporary fix but a longer fix would be to be restructure the models just like how you restructured the entire project. The issue originates from unsupervised migrations

**Comment by gorkemarslan** [comment]
Ok, thank you for the quick response. :)

I am asking this because I wonder whether we get all the useful files from the `master` branch. I think this issue is not gonna be a big deal in the future.

Ok, I now understand why you squashed 29 migrations, not all of them.

**Comment by AbhijithGanesh** [comment]
If I had squashed all migrations, there would be a circular import and It is not easy for someone to fix it quickly. It would've virtually taken me forever to do so.

**Comment by brylie** [comment]
@all-contributors please add @AbhijithGanesh for bugs
