### ISSUE TITLE
Migrate API code to conventional Django apps

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1026]
Currently, most of our API-related code resides in the `api` app. This includes common Django models, Django Rest Framework API code, and custom functions (some of which may be obsolete).

## Code locations
- [models](https://github.com/CiviWiki/OpenCiviWiki/tree/develop/project/api/models) - these are actually Django models and should move to `<app>/models.py`
- [ViewSets](https://github.com/CiviWiki/OpenCiviWiki/tree/develop/project/api/views) - should move to `<app>/api.py`
- [read.py](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/read.py) - should move to `<app>/api.py`
- [write.py](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/write.py) - should move to `<app>/api.py`
- [permissions](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/permissions.py) - should move to `core/permissions.py`
- [serializer](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/serializers.py) - should move to `<app>/api.py`
- [URLs](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/urls.py)
- [utility functions](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/utils.py) - some of these may be obsoleted by Django Rest Framework
    - [`json_custom_parser`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/utils.py#L25) is probably made obsolete by DRF
    - [`json_response`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/utils.py#L40) is probably made obsolete by DRF
    - [`get_account`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/utils.py#L12) seems a bit odd, and may be possible to remove with a small refactor
- [authentication](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/authentication.py) - we can delete this file and adhere to the [Django/DRF CSRF guidelines](https://www.django-rest-framework.org/topics/ajax-csrf-cors/#csrf-protection)

## Routing
See subtask on "Create global API router"

## Subtasks

- [x] https://github.com/CiviWiki/OpenCiviWiki/issues/1029
- [x] #1030
- [x] #1031
- [x] #1032
- [x] #1040

## Original report

@AbhijithGanesh opened this issue with the following idea. We have re-purposed the issue to track the migration of our API code into a more conventional Django app structure.

### Idea summary

Need for Django-Rest-Framework's Async views

### Further details

To improvize performance and other benchmarks, it would be better if we start transitioning into asynchronous views/endpoint access with DRF. I had initially thought about FastAPI (refer #1009) but since it isn't common practice, I think we should switch to Async DRF.

**Comment by AbhijithGanesh** [comment]
I would like to work on this if no is assigned.

**Comment by brylie** [comment]
Let's figure out whether to prioritize this issue for 2.0 or a later milestone. 

- What parts of the project would need to change to support `async` API views? 
- What current limitations would be improved by switching to `async`?

**Comment by AbhijithGanesh** [comment]
As far as I've understood this project, we will be deprecating api app soon therefore if we are moving to async, we need to know how we'll be migrating.

**Comment by AbhijithGanesh** [comment]
I have a question, if we are deprecating api app what is our alternative. How are we going to keep it  running @brylie

**Comment by brylie** [comment]
We are moving all API-related code out of the `api` app and into related apps. For e.g., `accounts/api.py` contains accounts-related API code. We will still maintain an API but will organize the code into proper Django apps.

The `api` app is too generic. The idea was that CiviWiki would use Django mainly for a REST API while having a JavaScript SPA for the frontend. This pattern was, and still is, popular but is a bit of overkill for most projects, CiviWiki included.

**Comment by brylie** [comment]
@AbhijithGanesh, would you like to help us migrate some of the API code into conventional Django apps?

**Comment by AbhijithGanesh** [comment]
I am more than happy to help the project. I can help. I will read up on the restructuring by Gorkem Arslan and start

**Comment by brylie** [comment]
OK, thanks. I'll revise this issue and add a migration roadmap :-)

**Comment by AbhijithGanesh** [comment]
> OK, thanks. I'll revise this issue and add a migration roadmap :-)
> 

That shall help me loads, thank you. Please add a roadmap and I shall get it running up to speed.

**Comment by AbhijithGanesh** [comment]
We'll be having accounts and that shall be our sole django-app right?

**Comment by brylie** [comment]
There is also a [`threads` app](https://github.com/CiviWiki/OpenCiviWiki/tree/develop/project/threads) in the [`project/` directory](https://github.com/CiviWiki/OpenCiviWiki/tree/develop/project).

**Comment by gorkemarslan** [comment]
@brylie and @AbhijithGanesh, I think we should apply clean code principles when we're moving the components. For example, if functions and classes that will be moved have not docstrings and comments, we should include this descriptive strings to them just after moving. If it is possible, some tests should be must. Before committing, we all should check formatting with `flake8`.

**Comment by brylie** [comment]
Sure, things like docstrings and lint should be included. Let's first focus on getting the code migrated though, as it has been somewhat partial so far. I'd rather have flaky but fully-migrated code than lint-free, partially migrated (fragmented) code.

I just don't want "perfect" to be the enemy of "done" in the case of this refactoring, but otherwise fully agree with your suggestions regarding clean code principles :smiley:

**Comment by brylie** [comment]
@gorkemarslan would you be willing to migrate the remaining accounts code? https://github.com/CiviWiki/OpenCiviWiki/issues/1031

**Comment by gorkemarslan** [comment]
Yes please. :)

**Comment by AbhijithGanesh** [comment]
Can I start migrating the API related codebase? I don't feel like this can be done concurrently, if it can be done what app should I work on @brylie and @gorkemarslan

**Comment by AbhijithGanesh** [comment]
Brylie please assign me to this task.

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, you should look at the subtasks and choose one. (#1029, #1030, #1031, #1032) I work on #1031. You can select one from the remaining. It is more appropriate for you to choose #1032 because you open this issue to move files :) Or #1029 is another good option to get understood the project.

You can write down your request to get assigned in the subtask you choose.

Don't worry. @brylie separate the tasks well. We all can work concurrently and follow @brylie 's guidance easily.

**Comment by AbhijithGanesh** [comment]
I have noted this, I shall work on #1032

**Comment by brylie** [comment]
@gorkemarslan and @AbhijithGanesh, issue #1030 is needed by both #1031 and #1032. As a common dependency, and since it is relatively small, #1030 would be a good starting task.

**Comment by AbhijithGanesh** [comment]
@brylie and @gorkemarslan , we need to get this done, it is becoming one of the stagnant issues

**Comment by brylie** [comment]
@AbhijithGanesh This work has been done, from what I can tell.
