### ISSUE TITLE
Create `notifications` app with initial code

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1029]
### Idea summary

Create a new `notifications` app. Move related code from the `api` app to `notifications`

### Further details

Steps to complete this task:

- [ ] create a notifications app
	- `python manage.py startapp notifications`
- [ ] add the `notifications` app under `INSTALLED_APPS` in `core/settings.py` 
- [ ] move notification-related code from the `api` to the `notifications` app
    - [ ] `api/models/notification.py` -> `notifications/models.py`
    - [ ] remove [api/__init__.py notification import](https://github.com/CiviWiki/OpenCiviWiki/blob/882f9fd522830f5849eddbc9802e4a6ed24d29d3/project/api/models/__init__.py#L8)
- [ ] create database migration(s)
    - [ ] `python manage.py makemigrations`
    - [ ] `python manage.py migrate`
- [ ] Commit changes, push to GitHub, and open a pull request against the `main` branch in this repository

**Comment by gorkemarslan** [comment]
@brylie, could you add `Write unittests` to the list?

**Comment by brylie** [comment]
What part of the `notifications` model do you propose would need unit tests?

https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/models/notification.py#L13-L36

**Comment by gorkemarslan** [comment]
I tend to write tests for models to check whether the instance creation on db is done successfully. Testing models is very minimal and simple. For example,

https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/accounts/tests/test_models.py#L13-L29

here I only controlled the fields.

In `notifications.py`, it is enough to test ForeignKey relations.

Actually, tests are not required not only for present usages but also for future usages. Now we can be sure that everything still works successfully with the help of the tests while moving apps, files, etc.

**Comment by anurag629** [comment]
can I try this?
I can do this.

**Comment by anurag629** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/78868769/134936075-1f97346e-8ec3-4fbf-ac72-c610f0e16d8e.png)


can i change the name of app to notification

**Comment by brylie** [comment]
Yes, in this case, we can break the convention for plural app names.

**Comment by brylie** [comment]
Closing this issue, since I had to rebase the code. New pull request is #1055 and includes your changes and attribution @anurag629

**Comment by gorkemarslan** [comment]
@brylie, now (and previously) we are not using `Notification` model? I guess we'll use it in `discussion` or `thread` app. Right?

**Comment by brylie** [comment]
We can decide whether to use it. Notifications can make the app more engaging, but we can reconsider the feature. In the name of simplicity, it might make sense to delete the unused code. What do you think?

**Comment by gorkemarslan** [comment]
>  it might make sense to delete the unused code. What do you think?

Specifically for `notification` app or the project level?

**Comment by brylie** [comment]
Well specifically for the notification app. We should delete unused code in general.

**Comment by gorkemarslan** [comment]
I am now talking about `notification` app:
As far as I understand there will be an inbox section to show users their notifications such as gorkemarslan follows you.

Is it really necessary to store the `last_modified` field? 🤔 

https://github.com/CiviWiki/OpenCiviWiki/blob/7312b148803469fc3164b2a1624d6ed0fa19d46d/project/notification/models.py#L35-L36

Because notifications will be of form read-only.

**Comment by gorkemarslan** [comment]
There are still unused codes in the project. Of course, we should delete them. After completing all the restructuring parts, I am planning to create a new issue to clean out them.

Further, all codes are stored in the Git repository. We can access them even after deleting them. For improving readability, I am a big fan of deleting. :)

**Comment by AbhijithGanesh** [comment]
Was the tasks in this issue finished?

**Comment by brylie** [comment]
Yes, by PR #1055
