### ISSUE TITLE
Move all thread code from `api` to `threads` app

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1032]
The `api` app contains code that should be moved to the `threads` app. Move all of the following code to the `threads` app, fix any related imports, and make migrations (if necessary).

- [x] related code in `api/models/` to `threads/models.py`
    - [x] [Activity](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/activity.py)
    - [x] [Civi](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/civi.py)
    - [x] [Fact](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/fact.py)
    - [x] [Rationale](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/rationale.py)
    - [x] [Rebuttal](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/rebuttal.py)
    - [x] [Response](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/response.py)
    - [x] [Thread](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/thread.py)
    - [x] ThreadManager
    - [x] CiviManager 
    - [x] CiviImageManager
    - [x] CiviImage
    - [x] ActivityManager
- [x] related code in `api/read.py` -> `threads/api.py`
    - [x] [`get_thread`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L125)
    - [x] [get_civi](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L189)
    - [x] [get_civis](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L201)
    - [x] [get_responses](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L213)
- [x] related code in `api/serializers.py` -> `threads/serializers.py`
    - [x] [CiviImageSerializer](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L120)
    - [x] [CiviSerializer](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L130)
    - [x] [CiviListSerializer](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L182)
    - [x] [ThreadSerializer](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L225)
    - [x] [ThreadListSerializer](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L263)
    - [x] [ThreadDetailSerialzier](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L293)
- [x] [thread-related URL patterns](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/urls.py#L9) in `api/urls.py` -> `threads/urls.py` 
- [x] related code in `api/write.py` to `threads/api.py`
    - [x] [new_thread](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L32) 
    - [x] [createCivi](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L65) - rename to `create_civi`
    - [x] [rateCivi](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L142) - rename to `rate_civi`
    - [x] [editCivi](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L189) - rename to `edit_civi`
    - [x] [deleteCivi](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L226) - rename to `delete_civi`
    - [x] [editThread](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L243) - rename to `edit_thread`
    - [x] [uploadCiviImage](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L396) - rename to `upload_civi_image`
    - [x] [check_image_with_pil](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L439)
    - [x] [uploadThreadImage](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L449) - rename to `upload_thread_image`
- [x] create database migrations with `python manage.py makemigrations`

**Comment by AbhijithGanesh** [comment]
Claim

**Comment by AbhijithGanesh** [comment]
All api related models to threads? I can move the code and resolve imports but I just need confirmation before I start.

**Comment by brylie** [comment]
> All api related models to threads?

Please see the description for notes in the specific code to move and where it should reside.

**Comment by brylie** [comment]
@AbhijithGanesh, I have updated this issue description with the remaining functions to be moved along with the destination file names.

**Comment by AbhijithGanesh** [comment]
Yes brylie, I'll work on this. Please disregard the PR, it has mixed branches and I don't want it to be merged.

**Comment by brylie** [comment]
OK, I'll close PR #1035 and await further discussion about code analysis in a subsequent issue. Please open issues for discussion before making code changes.

**Comment by brylie** [comment]
@AbhijithGanesh For now, please leave the "category"-related code in the `api` app. I'll make a separate task for creating a new `categories` app with relevant code :smiley:

**Comment by AbhijithGanesh** [comment]
I just saw that you removed my PR, sorry for the redundant comment.

**Comment by brylie** [comment]
I think you had a clean branch with just `threads`-related changes, right? If not, perhaps just start a new branch and work through the checklist in this project description :rocket:

**Comment by AbhijithGanesh** [comment]
> 
> 
> The `api` app contains code that should be moved to the `threads` app. Move all of the following code to the `threads` app, fix any related imports, and make migrations (if necessary).
> 
>     * [x]  related code in `api/models/` to `threads/models.py`
>       
>       * [ ]  [activity](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/activity.py)
>       * [ ]  [category](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/category.py) - although this might be better in a `categories` app since it is shared between `threads` and `accounts` apps
>       * [ ]  [civi](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/civi.py)
>       * [ ]  [fact](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/fact.py)
>       * [ ]  [rationale](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/rationale.py)
>       * [ ]  [rebuttal](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/rebuttal.py)
>       * [ ]  [response](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/response.py)
>       * [ ]  [thread](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/models/thread.py)
> 
>     * [ ]  related code in `api/read.py` -> `threads/api.py`
>       
>       * [ ]  [`get_thread`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L125)
>       * [ ]  [get_civi](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L189)
>       * [ ]  [get_civis](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L201)
>       * [ ]  [get_responses](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L213)
> 
>     * [ ]  related code in `api/serializers.py` -> `threads/serializers.py`
>       
>       * [ ]  [CiviImageSerializer](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L120)
>       * [ ]  [CiviSerializer](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L130)
>       * [ ]  [CiviListSerializer](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L182)
>       * [ ]  [CategoryListSerializer](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L193) - although this might be better in a `catetories` app since it is shared between `accounts` and `threads` apps
>       * [ ]  [https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L200] - although this might be better in a `catetories` app since it is shared between `accounts` and `threads` apps
>       * [ ]  [ThreadSerializer](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L225)
>       * [ ]  [ThreadListSerializer](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L263)
>       * [ ]  [ThreadDetailSerialzier](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L293)
> 
>     * [ ]  [thread-related URL patterns](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/urls.py#L9) in `api/urls.py` -> `threads/urls.py`
> 
>     * [ ]  related code in `api/write.py` to `threads/api.py`
>       
>       * [ ]  [new_thread](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L32)
>       * [ ]  [createCivi](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L65) - rename to `create_civi`
>       * [ ]  [rateCivi](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L142) - rename to `rate_civi`
>       * [ ]  [editCivi](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L189) - rename to `edit_civi`
>       * [ ]  [deleteCivi](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L226) - rename to `delete_civi`
>       * [ ]  [editThread](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L243) - rename to `edit_thread`
>       * [ ]  [uploadCiviImage](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L396) - rename to `upload_civi_image`
>       * [ ]  [check_image_with_pil](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L439)
>       * [ ]  [uploadThreadImage](https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/api/write.py#L449) - rename to `upload_thread_image`

Task completed.

**Comment by brylie** [comment]
@AbhijithGanesh please use the checklist in the issue description to indicate exactly which items you have moved. All of the boxes are currently unchecked. Note, most of the changes are simply moving code and not editing it. The only edits that are needed are probably fixing imports and creating migrations with `python manage.py makemigrations`.

**Comment by AbhijithGanesh** [comment]
I am unable to check the boxes.

**Comment by brylie** [comment]
Oh dang. Try pasting the checklist into a comment and using that comment to check the boxes. That way, we can see your progress.

**Comment by brylie** [comment]
@AbhijithGanesh I sent you an invitation to join this repository. If you accept the invitation, you should be able to manage the checklist in the issue description. Thanks for your patience.

**Comment by AbhijithGanesh** [comment]
Thank you Brylie.

**Comment by AbhijithGanesh** [comment]
Brylie should I make specific changes for urls.py, I remember reading about routing somewhere.

**Comment by AbhijithGanesh** [comment]
@brylie Please give me the settings when api is removed.

**Comment by brylie** [comment]
> Please give me the settings when api is removed.

We aren't removing the `api` app as part of this pull request. It looks like the `threads` app is already installed under the `INSTALLED_APPS` in `core/settings.py` so there aren't likely to be any changes needed to the settings.

https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/core/settings.py#L32

**Comment by brylie** [comment]
> should I make specific changes for urls.py

Yes. Move the thread-related URLs (seen below) from `api/urls.py` to `threads/urls.py`.

https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/urls.py#L20-L34

You will also need to add imports in `threads/urls.py` for the related URL endpoint views.

**Comment by AbhijithGanesh** [comment]
I am reworking this repository again, since it needs to be redesigned

**Comment by brylie** [comment]
@AbhijithGanesh thanks for your help and patience with this fast-moving project :smiley:

**Comment by brylie** [comment]
@AbhijithGanesh, I reset the checklist here so you can work through it carefully. Please reference this issue from any pull request you open with the phrase "Closes #1032". Thanks again :100:
