### ISSUE TITLE
[Development Server] Bugfixes and Django 1.11 Testing

### ISSUE THREAD

**Issue by jl24** [CiviWiki/OpenCiviWiki#104]
The current [staging server](https://civiwiki-stage.herokuapp.com) of the `dev` branch has some issues that are preventing fluid testing. 

1. Client side js error that prevents rendering of the thread view
2. Hangup from calling the non-functional Sunlight API that eventually resolves in a 500 error
3. Beta blocker that requires manual access to the db

The current [dev server](https://civiwiki-dev.herokuapp.com) currently has fixes to the three aforementioned issues in addition to the update dependencies branch for testing django 1.11.

**Comment by jl24** [comment]
@mdwest @pscheid2 @brylie dev server is now up with the branch

**Comment by mdwest** [comment]
@jl24 I just looked at both servers.  I couldn't register a new account on the staging server. But I could register with dev. Is that how its supposed to be? 

Also, I don't think all the changes are updated in dev. For example, it still has the article page we discussed deleting. 

That said, this is a great tool to keep testing our progress! Great work! Look forward to talking more about this Monday.

**Comment by jl24** [comment]
@mdwest The staging server currently has the the `dev` branch deployed, which only has the latest approved merges deployed. This does not include the frontend ui changes and beta blocker removal because those were not tested or approved for merge by other developers yet. The dev branch has minor changes up (only the three mentioned above) and the django+dependencies upgrade branch up. This is so that the testing is kept simple and the changes get merged into the staging branch (which is confusingly named `dev`) as swiftly as possible

**Comment by jl24** [comment]
Relate PRs (#105 #97) merged
