### ISSUE TITLE
Move user/account-related templates out of `threads` app

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1050]
### Idea summary

There are several user- and account-related templates in the `threads` app. They should reside in the `accounts` app instead.

### Further details

Move all of the following templates from the `threads` app to the `accounts` app:

- [ ] `threads/templates/threads/base/less_headers/account_less.html` -> `accounts/templates/accounts/base/less_headers/account_less.html`
- [ ] `threads/templates/threads/base/less_headers/login_less.html` -> `accounts/templates/accounts/base/less_headers/login_less.html`
- [ ]  `threads/templates/threads/partials/account/*` to `accounts/templates/accounts/partials/account/*`
- [ ]  `threads/templates/threads/partials/feed/*` to `accounts/templates/accounts/partials/feed/*`
- [ ]  `threads/templates/threads/partials/login/*` to `accounts/templates/accounts/partials/login/*`
- [ ]  `threads/templates/threads/partials/user-setup/*` to `accounts/templates/accounts/partials/user-setup/*`
- [ ] `threads/templates/threads/user/*` -> `accounts/templates/accounts/*`
- [ ] `threads/templates/threads/account.html` -> `accounts/templates/accounts/account.html`
- [ ] `threads/templates/threads/feed.html` -> `accounts/templates/accounts/feed.html`
- [ ] `threads/templates/threads/invite.html` -> `accounts/templates/accounts/invite.html`
- [ ] `threads/templates/threads/user-setup.html` -> `accounts/templates/accounts/user-setup.html`
- [ ] make sure to fix all imports related to the moved files

**Comment by znhv** [comment]
Hi, I'm new to open source, and it's not entirely clear to me whether my corrections have been accepted or not.

**Comment by sahilsaini1107** [comment]
hello@brylie 
If this issue is still open I would love to work on it.
