### ISSUE TITLE
Load Materialize CSS from a CDN

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1051]
### Idea summary

Our project currently keeps the full Materialize CSS under revision control. Since Materialize CSS is an external dependency, we don't need to keep it under revision control. Furthermore, the CSS is not minimized. To improve both of thess issues, we can load the minimized Materialize CSS directly from a CDN.

### Further details

- [x] delete the Materialize CSS files from our project
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/524e02d9e7a46fd1c96451ecfb0d67f9fa7dc84b/project/threads/templates/static/dependencies/materialize.min.css
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/524e02d9e7a46fd1c96451ecfb0d67f9fa7dc84b/project/threads/templates/static/dependencies/materialize.min.js
- [x] replace any Materialize CSS import with a CDN link (markup below)
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/968a8df56212e88154e5129f305f798f787f4a40/project/threads/templates/threads/base/links.html
    - [x] or add it to our `base.html`, if issue #1049 is complete.

### Materialize CDN markup

```html
<!-- Compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>         
```

**Comment by AbhijithGanesh** [comment]
I want this please, I know I've been taking load but this will genuinely be useful for my learning curve! I would be extremely grateful if I am assigned to this!

**Comment by AbhijithGanesh** [comment]
@brylie can I please get this!

**Comment by brylie** [comment]
@AbhijithGanesh, thanks! I assigned you to the issue.

Please let us know if you have any questions or concerns.

**Comment by AbhijithGanesh** [comment]
I don't have any questions  but if I don't get  my other PR merged, it 'd be hard for me to work on this due to unmerged differences @gorkemarslan and @Brylie. Is that okay?

**Comment by brylie** [comment]
@AbhijithGanesh, in pull request #1048, we had to restore the `materialize.min.css` and `materialize.min.js` files so the project would run. So, we still need to delete them as part of this task.

I've un-checked the relevant checkboxes from this issue description to indicate the steps are not complete.

**Comment by AbhijithGanesh** [comment]
Those files are anyways deleted as a part of my branch and shall reflect @brylie and @gorkemarslan . Therefore it shouldn't be a problem
