### ISSUE TITLE
Move static templates/dependencies to `core` app

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1052]
### Idea summary

We have several static templates and dependencies that are used across all apps. As common dependencies, these assets should be moved to the `core` app.

### Further details

Move the following static templates/dependencies to the `core` app.

- [x] `threads/templates/static/*` -> `core/templates/static/`
- [x] `threads/templates/threads/email/*` -> `core/templates/email/`
- [x] `threads/templates/threads/static_templates/*` -> `core/templates/`
- [x] make sure to fix any imports or other code that references the moved files

**Comment by gorkemarslan** [comment]
I'd like to get this one.

**Comment by sahilsaini110** [comment]
hello @brylie 
I love to work on this issue
.

**Comment by sahilsaini1107** [comment]
hello @brylie 
I would love to work on this issue, if it is still open.

**Comment by brylie** [comment]
@sahilsaini110, this issue is currently assigned to @gorkemarslan. Would you mind introducing yourself in our [discussion forum](https://github.com/CiviWiki/OpenCiviWiki/discussions) where we can get you started with some onboarding steps?

**Comment by anurag629** [comment]
i want to work on this issue
