### ISSUE TITLE
Remove beta register and blocker templates

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1053]
### Idea summary

There are still two remaining templates related to the beta registration/blocker. Delete those templates.

### Further details

Remove the following templates:

- [ ] `threads/templates/threads/beta_blocker.html`
- [ ] `threads/templates/threads/beta_register.html`

**Comment by karandeeppotato** [comment]
Hi there,
I'm willing to work on this, can you please assign me?

**Comment by ssm0801** [comment]
Can I take this ?

**Comment by brylie** [comment]
Sure, @ssm0801. Thanks :smiley:

**Comment by ssm0801** [comment]
I am unable to find those templates I guess those are deleted already

**Comment by brylie** [comment]
Ah, strange. I must have been on a stale branch. Thanks for taking a look @ssm0801! I'll add you for review anyhow

@all-contributors please add @ssm0801 for review

**Comment by brylie** [comment]
@all-contributors please add @ssm0801 for review

**Comment by ssm0801** [comment]
Can you tell me what does it mean, add @ssm0801 for review ?

**Comment by brylie** [comment]
It means that you contributed to this project by reviewing code quality since you found that no changes were necessary. We want to acknowledge many types of contributions, so we are following the [All Contributors project](https://allcontributors.org/) guidelines.

**Comment by ssm0801** [comment]
oh okay thank you
