### ISSUE TITLE
Resolve naming mismatch between branches and deployment servers

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#106]
We have multiple servers that are used for testing, such as develop and staging. However, the branches that are being deployed to the servers do not match the name, e.g. dev is being deployed to staging.

# Task
- [ ] Configure the server names to match the branch that is being deployed there

**Comment by ck25** [comment]
the correct branches are now being deployed to their respective servers

**Comment by jl24** [comment]
the correct branches are now being deployed to their respective servers
