### ISSUE TITLE
Update urls for Django 3.2 release

### ISSUE THREAD

**Issue by gorkemarslan** [CiviWiki/OpenCiviWiki#1066]
[django.conf.urls.url](https://docs.djangoproject.com/en/3.2/ref/urls/#url) is deprecated since Django 3.1. 

```python
def url(regex, view, kwargs=None, name=None):
    warnings.warn(
        'django.conf.urls.url() is deprecated in favor of '
        'django.urls.re_path().',
        RemovedInDjango40Warning,
        stacklevel=2,
    )
    return re_path(regex, view, kwargs, name)
```

I want to update all usages of `url()` functions to be `path()`. Usage of [path](https://stackoverflow.com/a/49932648/4476073) is pretty simple and increases readability especially for developers who get started with Django after `Django 3.0` release. 

For example,

**threads/urls.py**
```python
urlpatterns += [
    url(r"^thread_data/(?P<thread_id>\w+)/$", get_thread, name="get thread"),
    url(r"^civi_data/(?P<civi_id>\w+)$", get_civi, name="get civi"),
    ...
]
```

can be written as 

```python
urlpatterns += [
    path("thread_data/<int:thread_id>/", get_thread, name="get thread"),
    path("civi_data/<int:civi_id>/", get_civi, name="get civi"),
    ...
]
```

Currently, there is no work on the backend. Pending PRs and recent issues are for the frontend (static files and templates). So there will be no conflict. 

### Further details

The urls in threads and core use the deprecated method
```py
url(r'<path>')
```
which should be migrated to the `path` method according to Django 3.2 documentation.

### Tasks
- [x] #1070 
- [x] #1077
- [x] #1073
- [x] #1090 
- [x] #1094

**Comment by gorkemarslan** [comment]
@brylie, what do you think if I move [urls.py](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/frontend_views/urls.py) and [views.py](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/frontend_views/views.py) in `frontend_views` to the related places in `accounts` and `threads` apps and delete this folder? I'm planning to create a task list for these changes.

**Comment by brylie** [comment]
@gorkemarslan sounds good. Each step we take to reorganize the code will make maintenance easier. We also need to plan to port the Backbone.js views to regular Django templates as part of deprecating the JS frontend.

**Comment by AbhijithGanesh** [comment]
Can I collaborate on this issue and reduce your workload GorkemArlsan?

**Comment by gorkemarslan** [comment]
Actually, that will be good. I'm not sure whether multiple collaborations in the same PR count for `hactoberfest`. Give me some time to detect all related issues with urls. Then, I'll create new issues that will be part of this parent issue so that multiple developers can contribute to our project. We also make sure that you're going to be assigned to at least one.

**Comment by AbhijithGanesh** [comment]
Yes, thank you!

**Comment by AbhijithGanesh** [comment]
I will also look out for where we can improve on urls.py

**Comment by AbhijithGanesh** [comment]
I would like to branch it out app-wise and make it different issues @gorkemarslan

**Comment by ADV1K** [comment]
I would also like to work on this issue. this might be my first pull request to an open source project 😄. @gorkemarslan

**Comment by gorkemarslan** [comment]
@ADV1K, first of all, you're welcome. :)
We're trying to split this issue into new issues as sub-parts of this one so that we try to make many developers contribute to the project.

We've recently created a similar issue #1026. In the sub-task, you can find clear guidance. We'll try to generate similar guides.

@AbhijithGanesh, could you please slow down a little? :) You should first make a clarification about changes and your findings in your new issue like sub-tasks in #1026. We should take them as an example. Could you do a similar thing for issue #1026 before coding? When @brylie comes, they can make suggestions and we take their approval then we can start coding.

**Comment by AbhijithGanesh** [comment]
I agree Gorkem, I shall add more details like #1026 and then we can start and I hope both of us are on the same page.

**Comment by AbhijithGanesh** [comment]
> 
> 
> @ADV1K, first of all, you're welcome. :) We're trying to split this issue into new issues as sub-parts of this one so that we try to make many developers contribute to the project.
> 
> We've recently created a similar issue #1026. In the sub-task, you can find clear guidance. We'll try to generate similar guides.
> 
> @AbhijithGanesh, could you please slow down a little? :) You should first make a clarification about changes and your findings in your new issue like sub-tasks in #1026. We should take them as an example. Could you do a similar thing for issue #1026 before coding? When @brylie comes, they can make suggestions and we take their approval then we can start coding.

Sorry for being unclear and creating new issues, I just wanted to make sure that the issues are created rather than detailing them. Once I created them I thought I'll add more details.

**Comment by AbhijithGanesh** [comment]
I have patched core-urls so that can be marked done?

**Comment by AbhijithGanesh** [comment]
Also can you please star my work? I have created issue #1073 to elaborate

**Comment by AbhijithGanesh** [comment]
Whats your take on this @brylie

**Comment by brylie** [comment]
@gorkemarslan should take the lead here. @AbhijithGanesh, please allow @gorkemarslan to define and manage the sub-tasks, since they have responsibility for the overall issue (this issue).

One way I like to work is to [create a task list in an issue comment](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists), using markdown:

```
- [ ] task one
- [ ] task two
- [ ] task three
```

Then, GitHub allows you to convert individual tasks in a list into actual issues.

> If a task requires further tracking or discussion, you can convert the task to an issue by hovering over the task and clicking the circle with a dot in the upper-right corner of the task.
>
> https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists#about-issue-task-lists

**Comment by AbhijithGanesh** [comment]
> @gorkemarslan should take the lead here. @AbhijithGanesh, please allow @gorkemarslan to define and manage the sub-tasks, since they have responsibility for the overall issue (this issue).

Sure, Let Gorkem add details to various issues since they came up with the idea. Thanks for the clarification Brylie

**Comment by AbhijithGanesh** [comment]
Are you working on frontend-views @gorkemarslan

**Comment by gorkemarslan** [comment]
I got some flu. 🤧 After some relaxation, now I'm here. I am creating a new PR to solve #1052. Then I'll solve this issue.

And also I will open new issues. Just need some time. :)

**Comment by AbhijithGanesh** [comment]
Take care mate! Health comes first therefore please rest and take care😃
If you would like to reduce workload , I can take up some work  for 
sure.

**Comment by gorkemarslan** [comment]
Thank your kind request. 😊 There is no more work in the frontend part. I guess I'll handle it.

**Comment by AbhijithGanesh** [comment]
Great, I also realized you and brylie work on similar Timezones which is slightly different from mine creating a bit of trouble but okay😅.

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, I am planning to open a new issue to distribute the functions and classes of  `frontend_views` to `accounts` and `threads` apps. I'll assign the issue to you in order to discuss which app is the right place.

But before that, issue #1073 should be fixed and the related PR should be merged. Thus no conflict is encountered.

@brylie, please do not close this issue. I will add more subtasks related to the URLs but in order not to encounter any conflict, first, we should fix these three subtasks.

**Comment by AbhijithGanesh** [comment]
I am up for the task Gorkem Arslan, thank you

**Comment by AbhijithGanesh** [comment]
> @AbhijithGanesh, I am planning to open a new issue to distribute the functions and classes of  `frontend_views` to `accounts` and `threads` apps. I'll assign the issue to you in order to discuss which app is the right place.
> 
> But before that, issue #1073 should be fixed and the related PR should be merged. Thus no conflict is encountered.

All related branches have been merged for #1073, I think it should be closed and if need be I can close it.

**Comment by AbhijithGanesh** [comment]
@gorkemarslan can we close this issue? I believe we fixed all deprecated methods pertaining to url

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, I am making the last changes for URLs, then we can close this.
