### ISSUE TITLE
Migration of frontend_views 

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1073]
### Idea summary

Elaboration of issue #1070

### Further details

As mentioned in issue #1070, we need to migrate from
```py
url(r"^")
```
to 
```py
path()
```
And for frontend_views the following points need to be kept in mind
- [ ] usage of django.urls module for path and include
- [ ] Including the following views using the include method
   - [ ]  About_view
   - [ ]  support_us_view
   - [ ] how_it_works_view
   - [ ] user_profile
   - [ ] issue_thread
   - [ ] base_view
   - [ ] civi2csv
 - [ ] use path for all of the above mentioned urls
 - [ ] Use the same name for reverse match.

**Comment by anurag629** [comment]
@gorkemarslan  Assign me I want to resolve this issue.

Thank You!

**Comment by AbhijithGanesh** [comment]
I think this issue was fixed.

**Comment by anurag629** [comment]
But it is still open

**Comment by AbhijithGanesh** [comment]
I'll close the issue once merged.
