### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by BrianMwangi21** [CiviWiki/OpenCiviWiki#108]
I've created an account and reset my password several times but can't log in

**Comment by jl24** [comment]
@BrianMwangi21 Which server are you trying to log into? are you trying to log into one of our running servers? or are you trying to set up a local development environment?

**Comment by BrianMwangi21** [comment]
Into one of your running servers. Here : https://www.civiwiki.org/login

**Comment by jl24** [comment]
Checked out the logs and the server seems to be running fine. The only advice i can give you is to make sure you're using your username not email to login. Looks like you signed up under the username `brianmwangi21`

**Comment by jl24** [comment]
I've tested the server with multiple accounts and the login system works fine. I'm gonna go ahead and close this issue. If you're still unable to login and are able to locate the source of the issue, please create another issue thread with the details.
