### ISSUE TITLE
Materialize is not defined

### ISSUE THREAD

**Issue by gorkemarslan** [CiviWiki/OpenCiviWiki#1080]
### Description

After login,

I see a nearly empty page.

<img width="1346" alt="Screen Shot 2021-10-02 at 11 13 03" src="https://user-images.githubusercontent.com/16780927/135708936-d9acb48a-b69b-4983-a2fd-cb0d37a6a775.png">

On the developer console of my browser, there is an error about Materialize JS:

<img width="506" alt="Screen Shot 2021-10-02 at 11 14 14" src="https://user-images.githubusercontent.com/16780927/135708958-b25b20f9-0b04-48c3-86c7-b8d8b74597ba.png">

> base.cb801f70fa8d.js:22 Uncaught ReferenceError: Materialize is not defined

Two recent merging requests of removing Materialize CSS and JS files (#1065 and #1067) could cause this issue.

**Comment by brylie** [comment]
@gorkemarslan please check issue #1049, as it may resolve this issue by creating a single source for global JS/CSS imports

**Comment by AbhijithGanesh** [comment]
This reflects in my patch too, once the issue #1049 is fixed, I think this should be resolved.

**Comment by guido97** [comment]
The problem not is in imports, now I work in this, seems that an incomplete upgrade is causing the problem (Sorry for my bad english)
