### ISSUE TITLE
add a sub-section to our development guide explaining how to use the fixtures

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1081]
This project contains fixtures and they are used to quickly populate the categories and threads model.
I have listed the changes in #1082  and this needs to be documented in the changes as the existence of these files are neither mentioned in docs nor are they explained well, therefore the development guide needs to be updated to help developers.

## Example documentation

We have previously documented how to use fixture data in the project, but the documentation was removed from our contributing guide. Here is an example of how our new documentation might look:

### Populate initial data

There are two files, located in the `/data` directory, that contain sample threads and categories data. Run the following commands to initialize the congressional and categories data:

```py
python manage.py loaddata data/sample_threads.json
```

```py
python manage.py loaddata data/categories.json
```

**Comment by LightFelicis** [comment]
Please assign it to me :)

**Comment by brylie** [comment]
@LightFelicis, I've added some example documentation to the task description. Thank you so much for contributing to CiviWiki and welcome to the community! :smile:

**Comment by AbhijithGanesh** [comment]
@brylie this issue is being closed since the branch has been successfully merged
