### ISSUE TITLE
Close issues not relevant to 2.0 milestone

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1086]
### Idea summary

Remove issues that are no longer pertinent

### Further details

I think we should close all un-related/solved issues and make sure they're not related to 2.0 Milestone
@brylie 
@gorkemarslan

**Comment by brylie** [comment]
Not all work/ideas can fit into the 2.0 milestone. It is common for projects to have issues that are not under immediate development, in order to plan a roadmap.

Are there some specific issues that seem outdated or irrelevant?

**Comment by AbhijithGanesh** [comment]
I shall reply to this after checking on all listed issues.

**Comment by brylie** [comment]
Closing, as this is pretty much complete.
