### ISSUE TITLE
Add `media` and `static` URL configs to `core/urls.py` for development

### ISSUE THREAD

**Issue by gorkemarslan** [CiviWiki/OpenCiviWiki#1094]
This is a beginner-friendly issue to help contribute to the community. If you're new to Django, it's just for you.

Right now, [urls.py](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/core/urls.py) in `core` app does not include `media` and `static` URL configurations.

https://github.com/CiviWiki/OpenCiviWiki/blob/dfffa84f83a21ffa7f9f1417a4eb576bed9b010c/project/core/urls.py#L25-L37

So we need to add [static](https://docs.djangoproject.com/en/3.2/howto/static-files/#serving-static-files-during-development) and [media](https://docs.djangoproject.com/en/3.2/howto/static-files/#serving-files-uploaded-by-a-user-during-development) adjustments to this file during the development stage.

**Tasks:**
- [ ] Add static config
- [ ] Add media config

**Comment by anurag629** [comment]
I want to fix this issue.
@gorkemarslan  Assign me, please
