### ISSUE TITLE
 Provide obvious way to navigate to CiviWiki front page from Thread view

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#11]
When viewing a particular Thread, there does not appear to be any obvious way to navigate to the CiviWiki front page.

![screen shot 2017-07-14 at 21 32 49-fullpage](https://user-images.githubusercontent.com/17307/28225623-02d900b4-68dc-11e7-93cd-838c02add5f6.png)

# Goal
Determine if users should be able to navigate to CiviWiki front page from Thread page. If so, provide obvious navigation element for user to click.

**Comment by jl24** [comment]
@brylie I believe this was solved with a previous PR #75 since it brought in the standard top navbar. We can close this specific issue.
