### ISSUE TITLE
[BUG]: FrontEnd routing issues

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1115]
### Description

The header in the application routes the application incorrectly and needs to be fixed. If it routes the anchor tag incorrectly, we'll be having a nested routes tree  of /page1/page2/...

### What should have happened?
Its end output must be like this
```html
<a class="dark-white-text menu-text" href="/howitworks">How CiviWiki Works</a>
```
instead of 
```html
<a class="dark-white-text menu-text" href="howitworks">How CiviWiki Works</a>
```

### What browser(s) are you seeing the problem on?
All

**Comment by brylie** [comment]
If possible, we should use the `{% url '<view-name>' %}` helper to auto-generate the correct URL.

https://docs.djangoproject.com/en/3.2/topics/http/urls/#reversing-namespaced-urls

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, @SimonDamberg has already created a PR, I am assigning @SimonDamberg to this issue.

**Comment by AbhijithGanesh** [comment]
I didn't see the mention of the PR here (in GitHub Mobile😅) anyways thanks for clarification

**Comment by gorkemarslan** [comment]
Interestingly, @SimonDamberg does not appear in the assignees suggestions. :thinking:

**Comment by AbhijithGanesh** [comment]
Major github confusions
