### ISSUE TITLE
[FEAT] Move all dependency related code

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1131]
### Description

Currently, the project uses a lot of dependency files which can be obtained from the provider's cloud/CDN 
The following dependencies must be removed and routed to their CDN\

Current Dependency list:
- [ ] Animate CSS
- [ ] Backbone JS
- [ ] JQuery.min.JS
- [ ] Less.min.js
- [ ] magicsuggest.min.css
- [ ] magicsuggest.min.js
- [ ] underscore.js

Reference for animate css 
[link](https://cdnjs.com/libraries/animate.css)

You can find other links for the above mentioned dependencies there and change them the following way

Currently it is routed this  way:
```html
<script type="text/javascript" src="{% static "dependencies/jquery.min.js" %}"></script>
```

It ideally should be
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

Once completed delete the above mentioned dependency files and create a pull request

**Comment by AbhijithGanesh** [comment]
@brylie I have created this issue for new members to contribute, if it is not taken by anyone, I am always there

**Comment by realce2** [comment]
I'll take this one :)

**Comment by AbhijithGanesh** [comment]
Assigned @realce2
