### ISSUE TITLE
[FEAT]: New Deployment

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1144]
### Idea summary

Rolling out as versions

### Further details

We need to start working on a model where we keep achieving our milestones and deploy them through Digital Ocean (@brylie)

We need to start following new practices which involve deploying. 
The issues that we'll be fixing are:
- [ ] Major bridge gaps between frontend and backend
- [ ] Endpoint mapping
- [ ]  Persistent Data needs to be stored safely
- [ ] Load Balancing
- [ ] Static file serving
- [ ] Feel of this as a product(UI/UX)

**Comment by AbhijithGanesh** [comment]
I would like to work on this brylie

**Comment by brylie** [comment]
This task isn't an urgent priority. We can work on continuous deployment once the project code reaches a more stable state. Currently, we have too many changes in motion and no actual deployment target.

**Comment by brylie** [comment]
Closing as `wontfix` for now.
