### ISSUE TITLE
[FEAT]: Creation of a dockerhub image

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1145]
### Idea summary

Docker Files

### Further details

I think we should bundle the whole application with docker and containerize our code base to migrate to anyother platform in case of future needs

The advantages are as follows:
-  Easier migrations to other Cloud Providers
-  Scalability Testing can be done
-  Data can be persistently saved
-  Usage of K8s to stabilize can be implemented
-  A load-balancer can be implemented

**Comment by AbhijithGanesh** [comment]
I would like to work on this as it is related to  #1144

**Comment by brylie** [comment]
Not urgent. We can keep it in the backlog until the time is right.

**Comment by prakharrathi25** [comment]
@brylie are we considering shipping it through docker anytime soon? I think we can add that feature now?

**Comment by brylie** [comment]
A Docker image could prove useful in the near-term, so feel free to take this issue :-)

**Comment by prakharrathi25** [comment]
Sure, sounds good. I would love to take this issue.
