### ISSUE TITLE
Consolidate Backbone templates for comprehension

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1153]
We are beginning the process of porting Backbone templates to the Django template syntax. However, the Backbone templates are often spread across multiple "partial" files, where a single Backbone model is applied against several combined template fragments.

In order to make it easier to port our Backbone templates, we can combine the templates into single files, where possible.

## Task

- [x] combine Backbone template partials into monolithic template files for easier comprehension

**Comment by brylie** [comment]
@gorkemarslan, why do we need to reopen this issue?

**Comment by gorkemarslan** [comment]
@brylie, could you look at the PR that I just created?

**Comment by gorkemarslan** [comment]
Before we had these lines and templates were working well

```
{% block extra_css %}
    <link type="text/css" rel="stylesheet/less" href="{% static "less/landing.less" %}"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.5.1/less.min.js" integrity="sha512-0YpTMMSmmT3qN4UJF5ZLv5MPiwBMlOOHrIVgdBMGyNiEKoPEMGyih0WkHOEozdl0qDa5cgFEVoteWbI3Ybsxmw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock extra_css %}
```

Now we import `less.js` from `base.html`:

https://github.com/CiviWiki/OpenCiviWiki/blob/a37af11a594337cd27eb8596fc42efa5fe5678be/project/core/templates/base.html#L27-L32

As far as I observe, we need to load `less` files first, then we can run `less.js` properly. Their import order is important. So I just fix this one.
