### ISSUE TITLE
Clicking "My Profile" link shows 500 error

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1154]
### Description

After starting a fresh CiviWiki instance and registering the first user, clicking the "My Profile" link leads to `/profile/`, which displays a 500 error.

### What should have happened?

I expected to see the profile setup wizard.

**Comment by rodolfonei** [comment]
Hi! Can I work on this issue, please?

**Comment by brylie** [comment]
Sure thing, @RodolfoNei. Thanks! :smiley:

**Comment by sreejithliterally** [comment]
Is this issue already assigned to someone?

**Comment by brylie** [comment]
@RodolfoNei is marked as an assignee. If you wish, you can ask @RodolfoNei if they could use some help on this issue.

**Comment by sreejithliterally** [comment]
Okay, @RodolfoNei Hey bro is there any way I can help you with this issue?

**Comment by rodolfonei** [comment]
Hi @sreejithdikru, it was a really simple fix, so it was not necessary, but thanks!
