### ISSUE TITLE
403 errors on /api/upload_profile and /api/edituser

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1155]
### Description

When trying to complete the user profile wizard, there are 403 errors in the Django console when clicking the "finish" button.

![image](https://user-images.githubusercontent.com/17307/138087375-a93dda7a-8505-4809-a254-188d12389cc2.png)

```
"POST /api/upload_profile/ HTTP/1.1" 403 1019
"POST /api/edituser/ HTTP/1.1" 403 1019
```

### What should have happened?

I expected the "edit profile" form to work correctly.

**Comment by silvarthur** [comment]
Hello, may I work on this issue, please?

**Comment by brylie** [comment]
@silvarthur, sure thing. I'll assign you.

**Comment by silvarthur** [comment]
Thanks! (:
