### ISSUE TITLE
[BUG] CSRF Token issue in setup

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1162]
### Description

When I try to setup a user for the first time, it re-directs to the `/setup` and the form doesn't have CSRF token, it needs to contain the CSRF token to allow HTTP POST (in this case)

### Further details

![image](https://user-images.githubusercontent.com/67182544/138486828-d4f633b3-50d6-4c36-b3b6-fc1c3de942c6.png)

**Comment by AbhijithGanesh** [comment]
@Brylie where do I insert the CSRF token? I don't think it is allowed in js files


Update: Just found it out, here:
![image](https://user-images.githubusercontent.com/67182544/138488428-9f40e9a2-97a9-43ba-bcad-f824a117cdf0.png)

**Comment by gorkemarslan** [comment]
Already covered in issue #1155.

**Comment by AbhijithGanesh** [comment]
I'll close this but CSRF issues are becoming big in our project @brylie and @gorkemarslan

**Comment by gorkemarslan** [comment]
I'm aware of that and we didn't have this problem previously. Actually, I spent some time fixing it according to Django docs but I failed. I thought that the issue could be related to the error that materialize not defined but it does not. Now the issue is assigned to someone. If it won't be fixed, I review it and try to solve it again.

**Comment by gorkemarslan** [comment]
Thanks for your caution. 👍

**Comment by brylie** [comment]
I believe we should focus primarily on porting the Backbone templates to Django templates/views. In the process, we will indirectly resolve the CSRF issues when re-creating the relevant forms.

**Comment by AbhijithGanesh** [comment]
I think CSRF is important because it determines how we handle HTTP methods and if we don't solve it, we might run into issues.

**Comment by brylie** [comment]
I understand. We will continue using CSRF tokens for forms. We are just rewriting the templates so will be rewriting the forms including the CSRF tokens.
