### ISSUE TITLE
Fix errors when creating a new thread and showing existing threads

### ISSUE THREAD

**Issue by gorkemarslan** [CiviWiki/OpenCiviWiki#1170]
### Description

- When a new thread is created, 403 error appears in the front end.
- Some parts remain the same after `thread.author` field change from `Profile` to `User`. For example:
https://github.com/CiviWiki/OpenCiviWiki/blob/ab96113090654bc78c3674a47e46c2f9aa08d2b3/project/threads/models.py#L48-L51
- Use f-strings in `threads/models.py`
- Uploaded images should be saved under `media` folder.

**Comment by AbhijithGanesh** [comment]
@gorkemarslan Are you sure about the HTTP 403 part, I think it is related to the CSRF issue so I think we need to move this down our priority list.
