### ISSUE TITLE
Improvement of hyperlink hover animation

### ISSUE THREAD

**Issue by shiv-aay** [CiviWiki/OpenCiviWiki#1179]
### Idea summary

Make header/footer links hover interactive with change of font color shade as a smooth animation

### Further details

Presently Header links have an underline and background change animation on Hover and footer links are non-interactive. Underlining is not a good choice (for header links at least). Underlining should be replaced with change of font color as a quick+smooth animation, something like GitHub's header links behave on Hover. A similar behavior should be added to footer links as well.

**Comment by guido97** [comment]
I'm working in it
