### ISSUE TITLE
'User' object has no attribute 'full_name'

### ISSUE THREAD

**Issue by guido97** [CiviWiki/OpenCiviWiki#1181]
### Description

When I try to login, appears an error 500 that say 'User' object has no attribute 'full_name' (in debug mode) 

### What browser(s) are you seeing the problem on?

Firefox

### Further details

![imagen](https://user-images.githubusercontent.com/44304394/139560521-900dcd61-a938-4586-bce2-7297d2b79b34.png)

**Comment by gorkemarslan** [comment]
I mentioned this error in issue #1170 and PR #1180 will fix it.

**Comment by gorkemarslan** [comment]
Fixed by PR #1180.
