### ISSUE TITLE
Update Thread app templates to Django Templates 

### ISSUE THREAD

**Issue by wassafshahzad** [CiviWiki/OpenCiviWiki#1189]
### Idea summary

Steps to port Thread App

### Further details

- [ ] Create a management command to create multiple threads
- [ ] Port JS scripts of thread app
- [ ] Create Thread Form front end and back end

Add more to-do's  to checklist if discovered.

**Comment by brylie** [comment]
@wassafshahzad this seems like a duplicate of #1152

**Comment by wassafshahzad** [comment]
This 1152 further divided as the threads forms and view is not rendering for me

**Comment by sumitdadwal** [comment]
Hi brylie,
I gave it a try but I guess its a little complicated for me but I would love to assist or help someone if they can guide me a little bit.

**Comment by gorkemarslan** [comment]
Duplicate of #1152
