### ISSUE TITLE
Addition of a Media directory

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1192]
### Description

We need to add a media directory to store profile images when we are getting images from the user.

### What browser(s) are you seeing the problem on?

Not Applicable

### Further details

It'd be of great use for the dev team once we start storing them in  a categorical way which'd make access to images easily.

**Comment by topguns837** [comment]
Hey Abhijith , should the media directory be added to the root directory only (containing Docs , projects , requirements etc. )
I would like to take this issue ...

**Comment by AbhijithGanesh** [comment]
Heyy topguns837 ! Usually the Media URL is added to the root of the directory, I will add the references here

[DOCS](https://docs.djangoproject.com/en/3.2/topics/forms/media/)

**Comment by gorkemarslan** [comment]
@topguns837, I guess you are interested in this issue, so I assign you to that one.

One thing to keep in mind, you can't commit empty folders. To overcome it, a placeholder file is put into them. `.gitkeep` is an empty dummy file that is used just for this purpose. To give an example, [staticfiles](https://github.com/CiviWiki/OpenCiviWiki/tree/develop/project/staticfiles) folder in our project has exactly the same structure. 

Lastly, you should create `media` folder inside [project](https://github.com/CiviWiki/OpenCiviWiki/tree/develop/project) folder such that

```
project
    |_ accounts
    |_ categories
    . . .
    |_ media
    ...
    |_ manage.py
```

**Comment by mnoguier** [comment]
I'm not to familiar with this, but maybe I can contribute with a little guidance?

**Comment by mnoguier** [comment]
It seems like this would be possible using the Flask library in Python, but any further suggestions would be appreciated?

**Comment by brylie** [comment]
@mnoguier, this project uses the Django framework. Adding Flask would create unnecessary complexity.
