### ISSUE TITLE
Small typo on the update_settings.html page.

### ISSUE THREAD

**Issue by dcrwn** [CiviWiki/OpenCiviWiki#1197]
### Description

When browsing to the settings page, on the left side below the Save Changes button, the word "up" appears on the page.
It's in line 63 of the update_settings.html file
![settings_screenshot](https://user-images.githubusercontent.com/4712499/141662758-8ab1c81f-49c7-46f7-8930-33a60a99d391.png)

**Comment by topguns837** [comment]
This is "up" written in line 63 in the update_setting.html file. Can I fix this error ?

**Comment by gorkemarslan** [comment]
@topguns837, yes you can. I am assigning you to this issue. If you need any help, please don't hesitate to write here. :)
