### ISSUE TITLE
port `account.html` to Django template syntax

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1199]
The file `accounts/templates/accounts/account.html` contains several `varbatim` sections that render Backbone content. We want to replace the Backbone content with Django template syntax. 

- [ ] move all elements from `block backbone_template` to `block content`
- [ ] change the Backbone code to use Django template syntax
- [ ] Ensure that all of the following code is replaced by Django template syntax:

account.html - each verbatim section needs to be converted to Django template syntax and the view should provide necessary context data
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/8ced00f932235b1ad472dcae5ecc6d0b9525bcec/project/accounts/templates/accounts/account.html#L14-L89
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/8ced00f932235b1ad472dcae5ecc6d0b9525bcec/project/accounts/templates/accounts/account.html#L92-L102
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/8ced00f932235b1ad472dcae5ecc6d0b9525bcec/project/accounts/templates/accounts/account.html#L105-L139'
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/8ced00f932235b1ad472dcae5ecc6d0b9525bcec/project/accounts/templates/accounts/account.html#L142-L168
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/8ced00f932235b1ad472dcae5ecc6d0b9525bcec/project/accounts/templates/accounts/account.html#L171-L176
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/8ced00f932235b1ad472dcae5ecc6d0b9525bcec/project/accounts/templates/accounts/account.html#L195-L209
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/8ced00f932235b1ad472dcae5ecc6d0b9525bcec/project/accounts/templates/accounts/account.html#L224-L241
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/8ced00f932235b1ad472dcae5ecc6d0b9525bcec/project/accounts/templates/accounts/account.html#L246-L274
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/8ced00f932235b1ad472dcae5ecc6d0b9525bcec/project/accounts/templates/accounts/account.html#L281-L295
- [ ] https://github.com/CiviWiki/OpenCiviWiki/blob/8ced00f932235b1ad472dcae5ecc6d0b9525bcec/project/accounts/templates/accounts/account.html#L352-L369

**Comment by AbhijithGanesh** [comment]
@brylie I was working with this issue right, can you please assign this to me?

**Comment by brylie** [comment]
Thanks @AbhijithGanesh :smiley:

**Comment by AbhijithGanesh** [comment]
Thank you🌟🙏

**Comment by AbhijithGanesh** [comment]
@brylie I'll work on this and finish it by 06-01-2021 (IST)
