### ISSUE TITLE
Civi 'temp score' display has unnecessary precision

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#12]
The 'temp score' display on a Civi card has over ten significant digits of precision.

![screenshot_20170714_213539](https://user-images.githubusercontent.com/17307/28225976-181da73a-68dd-11e7-92a8-4c32f47bddce.png)

# Goal
Consider rounding or truncating the 'temp score' display to improve readability.

**Comment by tractaylor** [comment]
I was looking around the code for where this variable is caculated.  Is it in models/civi.py?  In the score subroutine, I see the rank being calculated.  If this is it, from what I have read about python, I could just wrap the rank variable with a round(rank, 2).  Am I even close?

**Comment by brylie** [comment]
Sounds close. Give it a try, if you like. Just create a new branch.

**Comment by mdwest** [comment]
From what I see this temp score is created in the civi model with the math starting around line 136. Could we add a line of code somewhere (maybe line 167-168) saying {{ value|floatformat:3 }} to round the return number to 3 decimals.

**Comment by brylie** [comment]
Yeah, it seems clean to handle it in a template. Would that approach work?

**Comment by brylie** [comment]
@tractaylor would you like to take this issue?
