### ISSUE TITLE
Dead link on up-for-grabs.net

### ISSUE THREAD

**Issue by GoudronViande24** [CiviWiki/OpenCiviWiki#1212]
### Description

I found this project on https://up-for-grabs.net/. There is this GitHub repo, but also a link to https://www.civiwiki.org/ which redirects to a scam website.

### What should have happened?

Maybe this link instead: civi.wiki

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari, Not applicable

**Comment by brylie** [comment]
PR opened:

https://github.com/up-for-grabs/up-for-grabs.net/pull/3000

**Comment by sumitdadwal** [comment]
Hi Brylie,
I am a begginner coder. I am decent in Django and fastapi. I am looking for contribution oppertunities. I have been following this project for sometime and would love to contribute. Please let me know If I can help with anything.
Sumit

**Comment by brylie** [comment]
@sumitdadwal, we currently need help building Django templates for our `accounts` and `threads` apps. The old templates are built with Backbone and can serve as a reference. However, we may want to start from scratch since the Backbone code may be difficult to figure out.

**Comment by sumitdadwal** [comment]
Yes! I would love to do that. I cloned the project but could not find any backbone.js files.

**Comment by brylie** [comment]
The Backbone JavaScript is interwoven into several Django templates:

- https://github.com/CiviWiki/OpenCiviWiki/tree/develop/project/accounts/templates/accounts
- https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/threads/templates/threads/thread.html

Perhaps start with thread.html and migrate all of the Backbone template code into regular Django/HTML?

**Comment by GoudronViande24** [comment]
Maybe this is not the good issue to talk about this?

**Comment by brylie** [comment]
PR was merged. Closing
