### ISSUE TITLE
Vote counters don't work as expected

### ISSUE THREAD

**Issue by Unit111** [CiviWiki/OpenCiviWiki#123]
While testing I've noticed that the count number for the threads' problems I've opened do not count properly. I was able to generate 40 points by myself using a single account.

**Comment by jl24** [comment]
I'm unsure which number this is referring to, but checked both the counter displayed in the civi-outline section and the points present in each of the individual civis, but was unable to replicate this.

**Comment by brylie** [comment]
@Unit111 can you clarify this issue description?

**Comment by petarPetrovBG** [comment]
I am currently unable to reproduce it on civiwiki.org. 
Previously- by opening the Civi multiple times and changing my vote I the counter was only incrementing without going down during changes.

**Comment by brylie** [comment]
OK. Closing this issue, since the neither @jl24 or @petarPetrovBG could reproduce.
