### ISSUE TITLE
SRS

### ISSUE THREAD

**Issue by Sofis16** [CiviWiki/OpenCiviWiki#1230]
### Idea summary

Writing a Software Requirements Specification

### Further details

Hello I am a student of the Aristotle University and i want to contribute to your project by writing a Software Requirements Specificationi if you do not have one already or by any other way in this category.

**Comment by brylie** [comment]
Sure, that would be great! Thanks for offering to help :smiley:

**Comment by Sofis16** [comment]
Hello I've got some questions about the hardware components of the system.Which devices does it support and are there some specific connections between software components such as databases,operating systems?If these answers are written somewhere in the project lead me there so i can find them myself!

**Comment by brylie** [comment]
We are using the Django web application development framework. It runs across multiple platforms but is usually deployed to Linux. We don't require a specific database, but will eventually target PostgreSQL.

Further details about system requirements and compatibility can likely be found on the following websites.

- https://www.djangoproject.com/
- https://www.postgresql.org/
