### ISSUE TITLE
Upgrade Python to 3.8.12

### ISSUE THREAD

**Issue by gorkemarslan** [CiviWiki/OpenCiviWiki#1235]
In the project, we've specified the minimum version of Python as 3.7. Nevertheless, it should be upgraded to 3.8.12 to be able to be compatible with Django 4. After this change, we'll upgrade Django to 4, which is the last release. (PR #1234)

- [ ] Update [main.yml ](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/.github/workflows/main.yml) to have Python 3.8.12

- [ ] Update our [contributing guide](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/CONTRIBUTING.md#development) to be written Python 3.8+ instead of 3.7+

**Comment by ArdaGunduz00** [comment]
I will help the first open source projects, can I join?

**Comment by gorkemarslan** [comment]
Hi Arda,
There is a pending PR (#1237 ) to solve this issue. I'll approve that PR in a little while.

Thank you for your interest. If you want, you can look at the other issues in the project.

**Comment by ArdaGunduz00** [comment]
> Hi Arda, There is a pending PR (#1237 ) to solve this issue. I'll approve that PR in a little while.
> 
> Thank you for your interest. If you want, you can look at the other issues in the project.

Thanks.
I will look into other issues
