### ISSUE TITLE
Update django-notifications-hq

### ISSUE THREAD

**Issue by gorkemarslan** [CiviWiki/OpenCiviWiki#1244]
Since the current version of `django-notifications-hq` is not compatible with `Django 4` and the new release of this package seems not possible for now, we can adjust the `requirements` of this project so that `requirements` contains the commit number that solves compatibility with `Django 4`, rather than the release version.

**Comment by brylie** [comment]
@gorkemarslan can you link to the upstream issue in `django-notifications-hq` tracking the Django 4 compatible release?

**Comment by gorkemarslan** [comment]
Yes, sure @brylie.

The issue opened to solve the compatibility with Django 4 is [here](https://github.com/django-notifications/django-notifications/issues/322).

You can check out the issue questioning the new release 1.7 [here](https://github.com/django-notifications/django-notifications/issues/326).
