### ISSUE TITLE
[BUG]:Workflow failure

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1248]
### Description

The github workflows for Python environment 3.10 is failing and needs to be patched for the Pull requests to be tested.

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, #1246 aimed to solve this issue. I don't know how to re-run tests for the already opened PRs after changing the workflow for the tests. The one thing that comes to my mind is to commit empty messages in these PRs. @brylie, do you know how to deal with that?

**Comment by AbhijithGanesh** [comment]
There should be an option in actions to re run the tests. It is possible to re run them

**Comment by AbhijithGanesh** [comment]
I don't think the patch worked because despite the merge, the tests are failing in our master branch.

**Comment by gorkemarslan** [comment]
> There should be an option in actions to re run the tests. It is possible to re run them

It runs the previous workflow which was originally worked when the PR had been opened, so not the current one.

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, okay I understand the issue. We need to keep the branches updated with the develop branch because these branches have the Python 3.10 tests in their workflows. So they need to get merged into the develop branch.

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, PRs #1245, #1246, #1249, #1251 make the workflow runs without a problem. We decreased the version of Python to a more stable version (3.8). We also updated Django to 4 so that there won't be any security failure. These all fix this issue. Thanks for your notice.
