### ISSUE TITLE
Civis are probably now deleted from the DB

### ISSUE THREAD

**Issue by Unit111** [CiviWiki/OpenCiviWiki#126]
If there is a problem with one cause and two solutions the total number of Civis is 4. 
If I delete the cause, the number of Civis changes to 3 instead of 1.
I suspect that in this case the solutions are not deleted.

**Comment by brylie** [comment]
Let's see if we can verify this bug with the recent CiviWiki codebase.

**Comment by silvarthur** [comment]
@brylie, may I work on this one as well?

**Comment by brylie** [comment]
@silvarthur, sure. Let's just be cautious about how much work we take at once. Hopefully, this and #147 won't be too difficult.

**Comment by silvarthur** [comment]
Ok, @brylie . I will be working only on those two issues you assigned to me.

**Comment by silvarthur** [comment]
Hello, @brylie. I have just opened the pull request that fixes this problem.

https://github.com/CiviWiki/OpenCiviWiki/pull/1436
