### ISSUE TITLE
Update Dockerfile to use Poetry

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1297]
Once we have switched to using Poetry for package management, we need to update our Dockerfile to use Poetry as well.

## Further details

The Dockerfile currently uses `pip` to install requirements based on `requirements/dev.txt`, which inherits from our base requirements. We can update our Dockerfile to use Poetry to install dependencies (without a virtual environment, since that may be brittle) and then remove our `dependencies/*`.

https://github.com/CiviWiki/OpenCiviWiki/blob/f330cc63d90aa4ee5a573c8598d58d5da1282d8c/Dockerfile#L14-L15

**Comment by ApoorvaKashyap** [comment]
Hi!
Would like to work on this. 
Just to clarify, you only want to add `poetry install`?

**Comment by brylie** [comment]
Ah, sorry. I removed the Dockerfile in #1307

**Comment by brylie** [comment]
@ApoorvaKashyap, are there any other tasks that you would like to consider?
