### ISSUE TITLE
Add pre-commit to project

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1331]
The `pre-commit` script can help enforce good code practices. Similarly, Pre-Commit CI can auto-check pre-commit rules on pull requests.

## Task

- [ ] configure `pre-commit` for this project
- [ ] choose some useful hooks: https://pre-commit.com/hooks.html
    - [ ] black
    - [ ] isort
    - [ ] flake8
    - [ ] pyupgrade
    - [ ] django-upgrade
    - [ ] curlylint
    - [ ] dhjhtml

## Resources

- https://pre-commit.com/
- https://github.com/asottile/pyupgrade
- https://pre-commit.ci/
- https://pycqa.github.io/isort/docs/configuration/pre-commit.html
- https://github.com/asottile/pyupgrade

**Comment by Ni3dzwi3dz** [comment]
I`d love to give it a try!

**Comment by daaavo** [comment]
Hi i'd like to try it! It's only configuring the pre-commit or I could add a .toml file to manage the args for the hooks?

**Comment by brylie** [comment]
Hi @daaavo. Thanks for your interest in helping CiviWiki. Since @Ni3dzwi3dz is currently assigned to this task, would you consider taking a different task?

- https://github.com/CiviWiki/OpenCiviWiki/labels/good%20first%20issue

**Comment by Ni3dzwi3dz** [comment]
Hi, yes, i`m still in the game. Week at work was tought, but i`ll try to send PR on sunday

**Comment by brylie** [comment]
Hei all. Since we don't yet have a pull request for this issue and it is blocking other work, I'll unassign the issue to open it for other developers.

**Comment by brylie** [comment]
@daaavo, since you offered to claim this issue four days ago, you should have the first opportunity to take it forward. Do you want to take this issue, or should we leave it open to another developer?

**Comment by Anuj-Kumar-AJ** [comment]
hi @brylie thanks for letting us know that this issue is open now, I would like to work on it. Can you please assign it to me.

**Comment by brylie** [comment]
@Anuj-Kumar-AJ, thank you for offering to take this issue. I'll assign you since @daaavo [has a task](https://github.com/CiviWiki/OpenCiviWiki/issues/1344) now.

**Comment by Ni3dzwi3dz** [comment]
Terribly sorry for the delay - i just send a PR
