### ISSUE TITLE
Improve code quality and developer experience

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1342]
### Idea summary

The following tasks are intended to improve the overall code quality and developer experience.

### Further details

The book Boost Your Django DX contains many improvements for healthy and fun Django project development.
Epic

Implement the following DX improvements

- [x] #1343
- [x] #1344
- [x] #1345
- [x] #1346
- [x] #1347
- [x] #1348
- [x] #1349
- [x] #1350
- [x] #1351
- [x] #1352

**Comment by aryankeluskar** [comment]
I volunteer to complete #1346

**Comment by brylie** [comment]
Please add a comment in issue #1346. That way, we can see who is currently assigned and decide whether to re-assign the task.

**Comment by Nehemiah60** [comment]
All the tasks under this issue seem complete @brylie. You might cross-check and close the issue. Thanks.

**Comment by brylie** [comment]
Closing as complete
