### ISSUE TITLE
add django-debug-toolbar

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1344]
## Task

- [ ] install `django-debug-toolbar` with the command `poetry add django-debug-toolbar --group dev`
- [ ] follow the [remaining installation instructions](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html)

**Comment by daaavo** [comment]
Hi! I'd like to take this issue, is there something else I've to do besides following the contrib.md file? It's my first time in the hacktoberfest btw

**Comment by brylie** [comment]
Thanks, @daaavo! I'll assign you to this task.

**Comment by daaavo** [comment]
Thanks I'll start as soon as the hacktoberfest begins :D

**Comment by daaavo** [comment]
Hello @brylie can you check my PR to add the django debug toolbar

**Comment by brylie** [comment]
PR reviewed :-)
