### ISSUE TITLE
add django-browser-reload

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1346]
## Task

- [ ] follow the [installation instructions](https://github.com/adamchainz/django-browser-reload#installation) to enable `django-browser-reload` for this project

**Comment by Walexero** [comment]
Hello, would be willing to work on this issue

**Comment by brylie** [comment]
Thanks, @Walexero 😀

**Comment by Walexero** [comment]
okay, i guess i would get my hands off this then

**Comment by brylie** [comment]
@Walexero, sorry for the confusion. I seem to have forgotten to assign you to the issue when you claimed it.

@Mohammed-Saif0 , thank you for working on the issue in pull-request #1366. However, we will give @Walexero the opportunity to work on this issue since they claimed it four days ago.

**Comment by brylie** [comment]
Sorry again for the confusion.

**Comment by Walexero** [comment]
okay thanks, would start working on it, i have another issue opened, have completed one of the tasks remains the second, please respond on the issue page

**Comment by daaavo** [comment]
Hello is this issue still open? if it's so i'd like to give it a try

**Comment by brylie** [comment]
Hi @daaavo. @Walexero is still assigned to this issue but may like some help if you ask them.

**Comment by Nehemiah60** [comment]
Hello, @brylie. Is this issue still open?

**Comment by brylie** [comment]
Yes.

**Comment by Nehemiah60** [comment]
Hello @brylie. I don't know why my changes for this issue are failing the django-upgrade test. Here, is the response when trying to commit my changes.
`django-upgrade...........................................................Failed
- hook id: django-upgrade
- exit code: 1

Rewriting project/core/urls.py
`

**Comment by brylie** [comment]
It should have automatically fixed the code issues. Just stage the changes to `urls.py` and commit. The plugin makes sure we write code that uses the latest Django features and idioms.

**Comment by Nehemiah60** [comment]
Hello, @brylie. I have another error when trying to commit the changes...This is what I get after I stage the changes to urls.py
![browerr](https://user-images.githubusercontent.com/87471613/220857310-1c2163c4-3f39-4b0a-83ef-1fc2964f5c18.png)

This is my log file
[pre-commit.log](https://github.com/CiviWiki/OpenCiviWiki/files/10811659/pre-commit.log)

**Comment by brylie** [comment]
The error in the log file seems to be the following:

> raise RuntimeError("The Poetry configuration is invalid:\n" + message)
>      RuntimeError: The Poetry configuration is invalid:
>        - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'


Try again on a fresh branch, from the latest develop. Then only run `poetry add ...` and the package name.

**Comment by Nehemiah60** [comment]
Hey @brylie. I actually managed to solve the issue. It's because of a new release of the v1.5.0 of poetry-core. I had to upgrade the isort core to v5.12.0. 
Here is the commit [ea81bab](https://github.com/CiviWiki/OpenCiviWiki/commit/ea81bab0720109991d8847c2372c667cf59f1c5f)
