### ISSUE TITLE
add EditorConfig

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1348]
## Task

- [ ] add a `.editorconfig` file to the root directory of this project with the following contents
- [ ] add a note to the CONTRIBUTING guide about configuring .editorconfig support for VSCode and PyCharm

```yaml
# http://editorconfig.org
root = true
[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
insert_final_newline = true
[*.py]
indent_size = 4
```

**Comment by hmajid2301** [comment]
I can take this
