### ISSUE TITLE
Add ID to 'manage categories' button

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#135]
Our automated testing is trying to access the 'manage categories' button to make sure it works properly. However, this is made slightly brittle by the fact that the 'manage categories' button does not have an ID.

# Task
- [ ] 'Manage categories' button has meaningful (unique) ID

**Comment by metonymic-smokey** [comment]
Hey, if I'm not wrong, this is pretty similar to #143. I'd like to take up this issue if open, first time contributor to FOSS.

**Comment by filipgeppert** [comment]
HI @metonymic-smokey ! 
Are you working on this issue? 
Regards:)

**Comment by umr55766** [comment]
I can see there is a `id` already associated to the `manage categories` button. Am I missing something here ?

https://github.com/CiviWiki/OpenCiviWiki/commit/c1e83930f1fb1ebc590d08120d3f95c89e333530

**Comment by umr55766** [comment]
This issue is already fixed I guess, @brylie please close this if I'm not wrong.
