### ISSUE TITLE
disable auto-named migration

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1351]
## Task

- [ ] create a file `project/core/management/commands/makemigrations.py` with the following content

```py
from django.core.management.base import CommandError
from django.core.management.commands.makemigrations import (
    Command as BaseCommand,
)


class Command(BaseCommand):
    def handle(self, *app_labels, name, dry_run, merge, **options):
        if name is None and not dry_run and not merge:
            raise CommandError("-n/--name is required.")
        
        super().handle(
            *app_labels,
            name=name,
            dry_run=dry_run,
            merge=merge,
            **options,
        )
```

**Comment by anurag629** [comment]
Hey i want to work on this issue. Kindly assign me on this and also guide me in further steps

**Comment by harshxtanwar** [comment]
Hey, I'd love to work on this issue, can I get assigned to this task along with some guidance @brylie

**Comment by brylie** [comment]
@simar5244 please add a comment in this issue to indicate that you have claimed it. GitHub won't let me assign you to the issue unless you have commented here. Any pull request should be accompanied by an issue, such as this one, that is assigned to the pull request author.

**Comment by simar5244** [comment]
@brylie Issue Claimed. PR #1359
