### ISSUE TITLE
enable django-linear-migrationss

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1352]
## Task

- [ ] add `django-linear-migrations` with the following command `poetry add django-linear-migrations --group dev`
- [ ] follow the rest of the [django-linear-migrations configuration instructions](https://github.com/adamchainz/django-linear-migrations#installation)

**Comment by SethAngell** [comment]
Hey! I’d love to jump in a help out with this issue if no one else is working it! Seems like a good starting place :)

**Comment by itsrajatrai** [comment]
@brylie Would love to work on this ? Can you assign this issue to me ?

**Comment by brylie** [comment]
Hei @SethAngell and @therajatrai. Thank you for offering to help CiviWiki :-)

I'll assign @SethAngell since they first claimed the issue.

@therajatrai, is there any other task you would like to take?

**Comment by therajatrai** [comment]
@brylie https://github.com/CiviWiki/OpenCiviWiki/issues/1376#issue-1395787473 is this open ?

**Comment by itsrajatrai** [comment]
https://github.com/CiviWiki/OpenCiviWiki/issues/1376#issue-1395787473  Can I work on this ?

**Comment by itsrajatrai** [comment]
@brylie

**Comment by brylie** [comment]
@therajatrai, since @SethAngell is currently assigned, we'll have to find a different task for you to take. Check the issues list for any issue that is not presently assigned.

Also, please don't spam the issue discussion.
