### ISSUE TITLE
Add ID to 'choose (category?)' button

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#136]
Our automated testing is trying to access the 'choose (category?)' button to make sure it works properly. However, this is made slightly brittle by the fact that the button does not have an ID.

# Task
- [ ] 'Choose (category?)' button has meaningful (unique) ID

**Comment by RonitRay** [comment]
Hi, is this still open?

**Comment by jl24** [comment]
@RonitRay Yes you are free to pick this one up.
