### ISSUE TITLE
Update grammar in contributing guide

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1377]
### Idea summary

Improve the grammar in our contributing guide with an automated grammar checker.

**Comment by Atharva1802** [comment]
I want to resolve the given issue. Can you assign it to me please?

**Comment by topguns837** [comment]
I am interested in working on this issue.

**Comment by brylie** [comment]
Thank you for your interest. I am already assigned to this task. Is there any other task you would like to take?
