### ISSUE TITLE
Add instructions for fixing poetry.lock conflicts

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1384]
### Idea summary

We should help contributors resolve conflicts in the poetry.lock file, which is happening quite often.

### Further details

Add the following to our CONTRIBUITING.md to help other developers.

1. check out the `develop` branch with `git checkout develop`
2. update the `develop` branch with `git pull`
3. check out your branch with `git checkout my-branch`
4. attempt to merge `develop` into your branch with `git merge develop`
5. when conflicts are detected in `poetry.lock`, delete the file
7. resolve any remaining conflicts
8. re-generate the `poetry.lock`  with the command `poetry lock`

**Comment by mazen-r** [comment]
Hello, can you assign this issue to me please ?
