### ISSUE TITLE
FileError when editing user profile settings

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1396]
### Description

After registering and filling in my initial profile, I attempt to visit the Settings screen via the user menu (pictured below).

![image](https://user-images.githubusercontent.com/17307/194142702-6e41e2ea-39cc-4298-bf30-37f98835fd99.png)

When I click the "Settings" link, I am taken to the settings page at http://localhost:8000/settings/

The following `FileError` messages are displayed and the settings page looks somewhat broken.

![image](https://user-images.githubusercontent.com/17307/194142426-b67cb95c-6ee5-4b99-93cf-617339fcb15f.png)

### What should have happened?

I expected the settings page to look fairly "clean" and function correctly.

### What browser(s) are you seeing the problem on?

Chrome

**Comment by gorkemarslan** [comment]
The issue will be fixed by https://github.com/CiviWiki/OpenCiviWiki/pull/1393/commits/fc9f81d831b50e611150ce2b8680fe44f2332d10 there are leading spaces in static tags
