### ISSUE TITLE
Settings form doesn't seem to submit

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1397]
### Description

After registering and filling in my initial profile, I attempt to visit the Settings screen via the user menu (pictured below).

![image](https://user-images.githubusercontent.com/17307/194142702-6e41e2ea-39cc-4298-bf30-37f98835fd99.png)

When I click the "Settings" link, I am taken to the settings page at http://localhost:8000/settings/

When I try to submit the form, nothing seems to happen. When I navigate back to my Profile, the changes weren't saved.

### What should have happened?

I expected the settings page to function correctly.

### What browser(s) are you seeing the problem on?

Chrome

### Further details

There don't seem to be any (related) errors in the browser console.

**Comment by gorkemarslan** [comment]
@brylie, I couldn't replicate the error. I think #1393 fixed it. It almost fixes everything on our suffering planet. 😛  

Could you check the page again?
