### ISSUE TITLE
Add ID to 'civi links' field

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#141]
Our automated testing is trying to access the 'civi links' field to make sure it works properly. However, this is made slightly brittle by the fact that the button does not have an ID.

# Task
- [ ] 'Civi links' field has meaningful (unique) ID

**Comment by btsullivan** [comment]
Is this still open? I would like to take it if so.

**Comment by HarendraSingh22** [comment]
Is this still up for grab?

**Comment by jl24** [comment]
@HarendraSingh22 Yep! Feel free to pick this one up.

**Comment by HarendraSingh22** [comment]
On what page is this button ? I have not yet found it

**Comment by jl24** [comment]
The first paragraph in this [previous comment](https://github.com/CiviWiki/OpenCiviWiki/pull/202#issuecomment-397153427) i made explains how to add the ids. After that change, make sure to add the change in the `selectors.py` under `project/test_framework/app/selectors.py` as well.

**Comment by wjkpowell** [comment]
Hi There,

I'd like to give this one a go. First contribution!

:)

**Comment by brylie** [comment]
@wjkpowell welcome! OK, please read through the discussion carefully, as @jl24 has described where/how to add the missing IDs. Open a pull request with your changes, and I will review it. Please let me know in this thread, if you have any difficulties :-)

**Comment by wjkpowell** [comment]
Hi @brylie  Thanks! I've been trying to get my dev environment set up to action this, but having some trouble. I reached out on the Matrix Channel mentioned on the website, thought that would be better than adding as a comment on this issue. Hoping to deliver this this week!

**Comment by brylie** [comment]
@wjkpowell go ahead and open an issue describing the error, with steps to reproduce:

https://github.com/CiviWiki/OpenCiviWiki/issues/new

**Comment by metonymic-smokey** [comment]
Looking to make my first contribution. Is this issue still open? If so, I'd like to give this a shot!

**Comment by brylie** [comment]
@metonymic-smokey this issue is still open. Other developers have had a bit of trouble with the development environment set-up. Are you able to get started with the dev environment?

**Comment by brylie** [comment]
Issue was resolved by @CaioSR. Thanks to all who showed interest!

If you are still looking for a low-hanging-frouit, check out the following issue list:

https://github.com/CiviWiki/OpenCiviWiki/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
