### ISSUE TITLE
Add ID to 'thread type' dropdown

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#142]
Our automated testing is trying to access the 'thread type' dropdown to make sure it works properly. However, this is made slightly brittle by the fact that the dropdown does not have an ID.

# Task
- [ ] 'Thread type' dropdown has meaningful (unique) ID

**Comment by piyushmittal25** [comment]
@brylie 
is project is still open then please elaborate your problem more specifically with examples , i want to contribute in it.

**Comment by brylie** [comment]
@piyushmittal25 thanks for your willingness to contribute! 

Basically, this task is to improve the semantics of our HTML template(s) related to Civi threads. When we write automated tests against our UI, it is important that UI elements have semantic `class` or `id` properties, so our tests are simpler.

The current task is to check the Thread template(s) and make sure the **thread type** select has a semantic `id`.

**Comment by Zach048** [comment]
Hey!

New to open source, is this still open for contribution? I'd like to give it a shot.

**Comment by brylie** [comment]
Jep. Please feel free to open a pull request. If you would like more guideance, we can discuss the issue here or during our weekly, online meeting next Monday

**Comment by brylie** [comment]
We can move this to the 0.3 milestone, as it is non-essential.

**Comment by dl1683** [comment]
Hey I'm a beginner with all this. How can start contributing

**Comment by brylie** [comment]
Hei @dl1683 thanks for your offer. You can create a new branch from `dev`, and then use the previous work from @Zach048 as a guide:
https://github.com/CiviWiki/OpenCiviWiki/pull/202/files

In beginner terms, depending on your level of experience, you will need the following:

- an IDE (not just a text editor, honestly): try [VSCode](https://code.visualstudio.com/)
  - the VSCode Python extension will make your life much easier :-)
- Docker (so you can spin up our new development environment)
  - follow our [Docker development environment instructions](https://github.com/CiviWiki/OpenCiviWiki/blob/dev/readmes/docker-setup.md)

Keep me updated as you work through the above steps, and I will help you to take the following steps.

**Comment by killerontherun1** [comment]
@dl1683 are you working on this? If not I'm alright to continue from where you left off, or where @Zach048 left off from. 

Let me know how you want to proceed.

**Comment by dl1683** [comment]
Hey I've unfortunately not been able to work on it due to medical reasons.
Take it. Best of luck.

**Comment by brylie** [comment]
@dl1683 wishing you well! Hope to see you around the CiviWiki community going forward :-)

**Comment by BB8bear** [comment]
This this still open for contribution?

**Comment by brylie** [comment]
Yes, please follow-through with this issue, as it has had several false-starts ☺

**Comment by hedonhermdev** [comment]
Hey, can I work on this issue if it is still open?

**Comment by brylie** [comment]
Yes, if you can please let us know what problems you encounter while troubleshooting this issue.

**Comment by enigmaticsoulrg** [comment]
Hi, I am a beginner and would love to contribute to this project as well. I've been reading through the comments and I'm excited to give it a shot for the first time.

**Comment by brylie** [comment]
Ok, feel free. Try setting up a dev environment and let us know if there are any feature ideas you have or bugs you discover.

**Comment by CarlaLeal** [comment]
@enigmaticsoulrg are you currently working on this?

**Comment by CarlaLeal** [comment]
@brylie  is this still open?

**Comment by brylie** [comment]
Yes, it is open ☺

**Comment by CarlaLeal** [comment]
To confirm

> Yes, it is open ☺

Can the  Google MAP Key and Django Secret Key be set to anything in the .env file?

**Comment by brylie** [comment]
Well, somewhat. It should work to set a random key for both, but Google maps won't render correctly.

**Comment by CarlaLeal** [comment]
> Well, somewhat. It should work to set a random key for both, but Google maps won't render correctly.
okay, got it :)

**Comment by vishu2435** [comment]
i am somewhat beginner in python is there anypiece of code where i can contribute

**Comment by brylie** [comment]
@vishu2435 yes, what code editor are you going to use? We can help you get set up with a development environment.

Closing this issue as "won't fix".
