### ISSUE TITLE
Fix symmetrical relationship warning

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1427]
### Idea summary

Our Civi model has a relationship to itself with a `related_name` defined, causing the following warning to appear.

### Further details

```
WARNINGS:
threads.Civi.linked_civis: (fields.W345) related_name has no effect on ManyToManyField with a symmetrical relationship, e.g. to "self".
```

## Task

- [ ] ensure the above warning doesn't display anymore
    - e.g., remove the `related_name` argument, or set it to `+`

**Comment by poorvaditya18** [comment]
Hey, I'm interested in working on this issue. Can you please elaborate more?

**Comment by brylie** [comment]
Thanks, @poorvaditya18! I'll assign you to the issue.

**Comment by poorvaditya18** [comment]
Can you specify the path where I could exactly find this function?

**Comment by brylie** [comment]
It looks like the warning message stems from the following line.

https://github.com/CiviWiki/OpenCiviWiki/blob/034d8df40ff6224c352f8bddfc3c1a162163f55a/project/threads/models.py#L227

**Comment by poorvaditya18** [comment]
I am facing the issue while running  python manage.py runserver . Could you tell me the steps/commands how to start it ?

**Comment by brylie** [comment]
@poorvaditya18, please follow the [instructions in our development guide](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/CONTRIBUTING.md#development). If you encounter any issues, let us know which step is failing and the specific error so we can help troubleshoot.

What error are you getting when running `python manage.py runserver`?

**Comment by macintushar** [comment]
Hey I'm interested in contributing to this issue

**Comment by brylie** [comment]
@poorvaditya18, are you still working on this task, or should we assign it to @macintushar?

**Comment by poorvaditya18** [comment]
> @poorvaditya18, are you still working on this task, or should we assign it to @macintushar?

Yes I'm working on it.

**Comment by darshanip** [comment]
Let me know if it is up for grab, @poorvaditya18 & @brylie.

**Comment by brylie** [comment]
I've assigned you both since you have both expressed interest.

**Comment by werberger** [comment]
Hi @brylie , being new to Open Source, I'm not sure what the etiquette is... I believe I've got a fix for this so I'm just putting it in here (but if this is a fix and people are happy for me to go through the steps, I'd love to be assigned and able to make my first contribution to open source)

in  ...project\threads\models.py line 234

> linked_civis = models.ManyToManyField("self", related_name="links", **symmetrical=False,** blank=True)

**Comment by brylie** [comment]
That looks like the correct solution. We'll give @darshanip and @poorvaditya18 some time to resolve the issue.
