### ISSUE TITLE
Quick fix: Github link on site is out of date

### ISSUE THREAD

**Issue by Germlord** [CiviWiki/OpenCiviWiki#144]
Issue is about what the title says: the Github link on the website takes the user to the old Github page. Fixing it should be fairly simple: go to 

"OpenCiviWiki/project/webapp/templates/static_templates/static_footer"

and edit the link to "https://github.com/CiviWikiorg/CiviWiki" to instead go to "https://github.com/CiviWiki/OpenCiviWiki".

I would have fixed this myself, but I'm having trouble installing the prerequisite programs, so I can't test this yet. Hope that this helps?

**Comment by brylie** [comment]
@Germlord would you please consider opening a PR witt this fix?

**Comment by Germlord** [comment]
@brylie Should this be closed? It looks like the fix was merged.
