### ISSUE TITLE
Fix our Matrix chatroom badge

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1442]
### Description

When I view the README, I see that our Matrix chat badge is failing to render correctly.

![image](https://user-images.githubusercontent.com/17307/197240703-b9c940ae-b8a7-473f-a74a-61db3101e0f0.png)

This may be because the badge is trying to get a count of active users via an unstable API.

### What should have happened?

I would expect to see a user-friendly badge that invites me to "join our chat" rather than something that mistakenly indicated that the chat is "inaccessible".

## Task

- [ ] use [Shields.io](https://shields.io/) to replace our Matrix badge with a more simple one that invites the viewer to join our chat
- [ ] the badge should link to the following URL: https://matrix.to/#/#civi.wiki:matrix.org

Note, the following Markdown should be correct and can be added to our README.

```md
![Join our Matrix chat](https://img.shields.io/matrix/civiwiki:matrix.org?server_fqdn=matrix.org)
```

**Comment by frey0-0** [comment]
@brylie I would like to try to do this. Please assign

**Comment by zafar-hussain** [comment]
> Thanks, @zafar-hussain smiley

@brylie you are most welcome

**Comment by brylie** [comment]
Thanks, @zafar-hussain :smiley:

**Comment by frey0-0** [comment]
@brylie the badge still doesn't link to the URL. Can I do that?
