### ISSUE TITLE
Decide on project versioning scheme

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#15]
As a software project, we should release periodic versions. To release sequential versions, we need to decide on a versioning scheme.

# Resources
- [Semantic Versioning](http://semver.org/)
- [Compatibility Versioning](https://github.com/staltz/comver) - simpler than semantic versioning and possibly more appropriate for larger software that doesn't have a public API (code API)
- [PEP 396 -- Module Version Numbers](https://www.python.org/dev/peps/pep-0396/)
- [PEP 440 -- Version Identification and Dependency Specification](https://www.python.org/dev/peps/pep-0440/)

**Comment by mdwest** [comment]
@brylie  Is this a separate document or part of the proposed coding conventions document?

**Comment by brylie** [comment]
Somewhat related to coding conventions, but more of 'release management'.

**Comment by brylie** [comment]
I just added a link to [Compatibility Versioning](https://github.com/staltz/comver), to which I have recently switched in another project.
