### ISSUE TITLE
Contribution: Contributing document instructions do not appear to support Windows/iOS

### ISSUE THREAD

**Issue by Germlord** [CiviWiki/OpenCiviWiki#165]
I'm posting this because I have had a lot of trouble installing the prerequisite programs to run CiviWiki locally. It might be worthwhile to update the contribution page to reflect what developers with other operating systems should do--or if Linux is absolutely necessary, to post that at the start. Please let me know what you think.

**Comment by AbhijithGanesh** [comment]
The readme is clear now and the readme has been taken care of.
