### ISSUE TITLE
Document project coding conventions

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#17]
Code in a collaborative project should be consistent, and hopefully self-documenting. Consistency and clarity help new contributers, code reviewers, and existing developers understand the code.

Choose code standards and describe them in the contributing guide.

# Resources
- Open Source Guide [pre-launch checklist](https://opensource.guide/starting-a-project/#your-pre-launch-checklist)
- [PEP 8 -- Style Guide for Python Code](https://www.python.org/dev/peps/pep-0008/)
- django documentation [Coding Style](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/)
- [Raymond Hettinger - Beyond PEP 8 -- Best practices for beautiful intelligible code - PyCon 2015](https://www.youtube.com/watch?v=wf-BqAjZb8M)

**Comment by mdwest** [comment]
Lets talk about this at our meeting today (August 28h). I want to work on getting these conventions integrated into our repository.

**Comment by mdwest** [comment]
I'm thinking we should integrate conventions into the readme?
