### ISSUE TITLE
Use relative imports in project/api/models/__init__.py

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#171]
In order to transition to Python 3, we will need to make sure all of our relative imports have a dot prefix. E.g.

```py
# Nope
from relative_import import something

# Yep
from .relative_import import something
```

The difference is subtle, but will cause errors if left as is.

# Task
- [x] project/api/models/__init__.py uses dot-prefixed relative imports

This issue is related to issue #18

**Comment by GokuMizuno** [comment]
This issue appears to be resolved as of commit 26b0cf2638af7b1919d6decac2aa91708456f900.

Closing, please reopen if you find something I missed.
