### ISSUE TITLE
Can't login if an account has uploaded personal image before the thumbnail image code was deployed

### ISSUE THREAD

**Issue by jl24** [CiviWiki/OpenCiviWiki#174]
There is a bug with previous deployments updated with the new thumbnail image code. 
Django Error Log:
> Internal Server Error: /auth/login
> Traceback (most recent call last):
>  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
>    response = wrapped_callback(request, *callback_args, **callback_kwargs)
>  File "/app/project/utils/custom_decorators.py", line 20, in inner
>    return func(request, *args, **kwargs)
>  File "/app/project/authentication/authentication.py", line 60, in cw_login
>    request.session["login_user_image"] = account.profile_image_thumb_url
>  File "/app/project/api/models/account.py", line 161, in _get_profile_image_thumb_url
>    os.path.join(settings.MEDIA_ROOT, self.profile_image_thumb.name)
>  File "/app/.heroku/python/lib/python2.7/posixpath.py", line 68, in join
>    if b.startswith('/'):
> AttributeError: 'NoneType' object has no attribute 'startswith'

This prevents existing users from logging in if they created an account prior to the thumbnail image code deployment.

**Comment by brylie** [comment]
Just add a check to make sure the object exists before accessing a property. This is a common type of bug.
