### ISSUE TITLE
Update project to use Python 3

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#18]
CiviWiki seems to depend on Python 2.7. What are some of the reasons for staying with 2.7?

# Goal
Support the latest features of Python, such as `async` / `await`, by updating CiviWiki source/dependencies to support Python 3.

**Comment by brylie** [comment]
After scanning our requirements with `caniusepython3`, it shows only 3 requirements that might need to be upgraded or deprecated:
```
caniusepython3 --requirements requirements.txt 
Finding and checking dependencies ...

You need 3 projects to transition to Python 3.
Of those 3 projects, 3 have no direct dependencies blocking their transition:

  args
  asgi-redis
  asgiref
```

**Comment by brylie** [comment]
It is not clear to me if/where we use the args library.

**Comment by jl24** [comment]
The args library was added by an external developer who initially setup our webapp with the Gunicorn WSGI (commit d65a7a54897b0d0aafdb2632659c31ef9cc8fcd1). Since Gunicorn is no longer used, it can be removed

**Comment by urielfcampos** [comment]
Is this still open ?

**Comment by brylie** [comment]
Closing as this has been completed.
