### ISSUE TITLE
CiviWiki Email Notifications 

### ISSUE THREAD

**Issue by mdwest** [CiviWiki/OpenCiviWiki#183]
- [ ] Email notifications when new civies are added to a thread the user opened
- [ ] Email notification when someone links to user civi
- [ ] Email notification when someone you follow opens a new thread 
- [ ] Email notifications opt out form

**Comment by topguns837** [comment]
Can I work on the 4th feature (Email notifications opt-out form) ?

**Comment by brylie** [comment]
Sure

**Comment by anurag629** [comment]
Hey, i want to work on this issue

**Comment by brylie** [comment]
Closing as out-of-scope for 2.x milestone and the limited resources of the CiviWiki organization.
