### ISSUE TITLE
Upgrading from python 2 to 3 requires changes to our documentation and deployment files

### ISSUE THREAD

**Issue by jl24** [CiviWiki/OpenCiviWiki#190]
## ToDos

- [ ] Change the Python version reference in `CONTRIBUTING.md` to an appropriate version in 3
- [ ] remove the runtime specification file under `project/runtime.txt` (i.e. delete the file)

Related to issue #18

**Comment by BrianPainter** [comment]
These two items are complete in pull request: #778

**Comment by RgnDunes** [comment]
Can I work on this issue, if no one's working on it ?
