### ISSUE TITLE
Update requirements.txt to contain latest version of twisted

### ISSUE THREAD

**Issue by delta-plus** [CiviWiki/OpenCiviWiki#191]
As a result of upgrading to Python 3, we should be using the latest version of twisted: 18.4.

**Comment by brylie** [comment]
I am not sure why we have twisted as a dependency. I.e. it seems like Django is the main 'server' framework for our project, in that we deploy Django behind nginx.

See if we can remove twisted, if possible.

**Comment by brylie** [comment]
Ah, OK. I didn't realize twisted was a dependency of channels (by way of daphne). Well, at the least, we probably don't need to declare Twisted as a top-level dependency of this project. I.e. can we just declare channels as a top-level dependency, if we go that route?
