### ISSUE TITLE
Firefox and Safari rendering apostrophe incorrectly

### ISSUE THREAD

**Issue by GokuMizuno** [CiviWiki/OpenCiviWiki#192]
Both Firefox and Safari can render an apostrophe as random symbols, such as "é «", "â€™", "â€", and more.

This is because both of them have their encoding set to "Default", not UTF-8.  For affected users, their default encoding is Western, that is, ISO-8859-1, which renders the characters differently.

I blame Microsoft.

The easy way to fix this issue is to remove all apostrophe's from our client facing pages.

**Comment by GokuMizuno** [comment]
Added, but the W3C validator threw up the following warning:

A character encoding is specified in the HTTP header (Content-Type: text/html; charset=utf-8), but there was no matching encoding declaration in the page. This may lead to problems later if there is a chance that the document will be read from or saved to disk, CD, etc.

In addition, the W3C Internationalization (i18n) Group recommends to always include a visible encoding declaration in a document, because it helps developers, testers, or translation production managers to check the encoding of a document visually

**Comment by brylie** [comment]
This should work:

```
<meta charset="utf-8"/>
```

See: [Declaring character encodings in HTML](https://www.w3.org/International/questions/qa-html-encoding-declarations)
