### ISSUE TITLE
Export to CSV does not work in Chrome

### ISSUE THREAD

**Issue by jl24** [CiviWiki/OpenCiviWiki#200]
Invalid response is sent by the host, producing the error, ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION.

The csv function works fine on other browsers (Firefox, safari)

**Comment by jgbmattos** [comment]
I think it's working well on chrome now. tested in chome version 74.0.3729.169 - 64 bits

**Comment by brylie** [comment]
Thanks @jgbmattos. Closing issue.

@all-conrtibutors please add @jgbmattos for userTesting

**Comment by brylie** [comment]
@all-conrtibutors please add @jgbmattos for userTesting

**Comment by brylie** [comment]
@all-contributors please add @jgbmattos for userTesting
