### ISSUE TITLE
No way to see which state an issue was opened for on the main feed page. 

### ISSUE THREAD

**Issue by mdwest** [CiviWiki/OpenCiviWiki#207]
On the test server, I noticed that when creating a new thread we can select which state a thread is for, but our thread cards don't this information. We should probably add this information to the card.

**Comment by terrencetuy** [comment]
Hi, if this is still valid, I would like to work on this. Thanks.

**Comment by mdwest** [comment]
Thank you, we would appreciate your help.

Please don't hesitate to reach out if you have any questions and consider
joining our riot chat.

at https://riot.im/app/#/room/#CiviWiki:matrix.org.

Best

-mw

**Comment by brylie** [comment]
@terrencetuy have you set up a development environment? How can we help you with this task?

**Comment by terrencetuy** [comment]
Haven't had too much time to work on this so far, but I do have one question right now. According to the CONTRIBUTING.md, I need a Sunlight API key. How do I get this?

Appreciate the support. Will definitely join the chat once I'm able to get more into the thick of things. Thanks!

**Comment by brylie** [comment]
Well, that documentation needs to be updated. Sunlight Foundation no longer offers their API, so we are now migrating to ProPublica (work-in-progress). See if you can skip that step without any errors.

**Comment by gkeswani92** [comment]
Is this something that still needs to be done?

**Comment by SunflowerPKU** [comment]
Is there something that still needs to be done?

**Comment by brylie** [comment]
@SunflowerPKU please test this issue on https://civiwiki-dev.herokuapp.com/

**Comment by SunflowerPKU** [comment]
@brylie I have tested this issue. Both the test version and release version can select state when creating a new thread so this issue needs to be closed.

**Comment by brylie** [comment]
Thanks for verifying @SunflowerPKU 😎

Would you like to help with a couple more testing/quality assurance (QA) related tasks?

**Comment by brylie** [comment]
@all-contributors please add @SunflowerPKU for userTesting

**Comment by brylie** [comment]
@SunflowerPKU can you please help us teat/verify this issue?

https://github.com/CiviWiki/OpenCiviWiki/issues/477

**Comment by SunflowerPKU** [comment]
@brylie 

> Thanks for verifying @SunflowerPKU 😎
> Would you like to help with a couple more testing/quality assurance (QA) related tasks?

It's my pleasure to make this software better.
