### ISSUE TITLE
Export Button Broken

### ISSUE THREAD

**Issue by mdwest** [CiviWiki/OpenCiviWiki#209]
The export function is broken. I clicked the button and expected to download a file of all voting. Instead, my screen showed an error. 

![image](https://user-images.githubusercontent.com/30572202/43048629-80821350-8d9f-11e8-838b-7852dc5d0336.png)

![image](https://user-images.githubusercontent.com/30572202/43048606-11aceff4-8d9f-11e8-999b-34847a3549e2.png)

**Comment by jl24** [comment]
duplicate of #200
