### ISSUE TITLE
Add docstrings to all model files, classes, and functions

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#21]
Docstrings exist in some models, but are not consistent. Add docstrings to all model files, class, and function definitions.

# Goal
The project should make consistent use of docstrings.

**Comment by North15** [comment]
@brylie I'm available to help on this issue. Thanks!

**Comment by fardeenes7** [comment]
I'm a beginner on this path. I hope you consider me for the issue.

**Comment by brylie** [comment]
Thanks @North15. I have assigned you to the issue.

Would you consider collaborating with @fardeenes7 so they can get started with CiviWiki development?

**Comment by North15** [comment]
@brylie Thanks for assigning me the issue! Definitely, @fardeenes7 if you want to start working on making changes to the models I'll start on the functions. Then once we complete those we can meet somewhere in the middle of the classes. Let me know if that sounds good to you.

**Comment by fardeenes7** [comment]
@North15 I'm okay with that.

**Comment by fardeenes7** [comment]
Added docstring to all model files. Submitted merge request. If you could give a look @brylie

**Comment by brylie** [comment]
Thanks @North15 and @fardeenes7 

I merged the PR opened by @fardeenes7

**Comment by brylie** [comment]
Closed by @North15
