### ISSUE TITLE
Editing Thread Needs to auto-refresh the page

### ISSUE THREAD

**Issue by mdwest** [CiviWiki/OpenCiviWiki#213]
When you click the clipboard button to edit a thread and make changes to the title, after saving changes I would expect to see the new content, but I had to refresh the page to see the update. 

![image](https://user-images.githubusercontent.com/30572202/43048706-f5d445aa-8da0-11e8-9504-f5c1bf246489.png)

**Comment by saxonhouse** [comment]
Hi!
I've been working on a fix for this by re-rendering the thread body along with the thread wiki. Happy to take this one if you want to take a look?

**Comment by mdwest** [comment]
@saxonhouse Thank you! Could you push up the code you have and add @jl24 to review? 

On a side note, if you are free Monday at 10am PST we hold a developer meeting at https://meet.jit.si/civiwiki and enjoy meeting new contributors!

**Comment by saxonhouse** [comment]
Done! Sure I'll check in if I'm free, thanks!

**Comment by mdwest** [comment]
@saxonhouse Thank you for your help on this issue. Would you have any interest in helping on Issue #217. We want to make it possible for unregistered users to view issue threads, and convert them to registered users if they try to vote on a civi, write a civi, or open a new issue thread.

**Comment by saxonhouse** [comment]
@mdwest No problem! Yep, sure, I can look into that.
