### ISSUE TITLE
Profile Link Broken

### ISSUE THREAD

**Issue by Shreyas4991** [CiviWiki/OpenCiviWiki#228]
The link to one's own profile isn't working. I had to plug in the required URL to get to my profile.

**Comment by alecxvs** [comment]
I wasn't able to reproduce this on Chrome 70.0.3538.77 (Mac OSX). Clicking the "Profile" link in the top right worked consistently for me.

**Comment by Shreyas4991** [comment]
The issue was on firefox 63 (stable) on (Ubuntu 18.04) Linux for me.

**Comment by brylie** [comment]
Yep, we really need to test our app on multiple browsers. It is increasingly common that webapps are only tested on Chrome.

**Comment by brylie** [comment]
@mdwest can CiviWiki please set up an account with [BrowserStack](https://www.browserstack.com/)? It is [free for open-source projects](https://www.browserstack.com/open-source?ref=pricing).

**Comment by brylie** [comment]
@alecxvs please try to replicate this bug with Firefox.

**Comment by danielgrijalva** [comment]
Hey, I'm also using Ubuntu 18.04, but I'm on Firefox v66.0.3 and I wasn't able to reproduce this bug.

**Comment by brylie** [comment]
OK, lets close. Thanks for checking @danielgrijalva :-)
