### ISSUE TITLE
Upgrade project dependencies

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#319]
There are several open issues related to project dependencies, which have been created by PyUpBot.

The goal of this task is to update most/all of the project Python dependencies. This includes updating to the Django 2.x series.

The work will also include cleaning up unused dependencies and related code, so the project is a bit leaner.

**Comment by brylie** [comment]
At the very least, we should upgrade the following to the latest version in their minor version series:

**Comment by m0neyy** [comment]
Is this up for grabs? Would you say accessible to someone w/ intermediate Python skills?

**Comment by brylie** [comment]
@m0neyy sure ☺Just focus on the four updates mentioned above, as a start. Upgrade them to the latest in the current series, I.e. no MAJOR version upgrades for now. Let me know if you have any difficulty setting up a development environment.

**Comment by m0neyy** [comment]
Sounds good thanks mate, I'm gonna have a go at it

**Comment by TomaszKolek** [comment]
Can we close it? @brylie
