### ISSUE TITLE
Run Flake8 on project code and fix errors

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#33]
As part of our work to keep the code readable and maintainable, we can use the [Flake8](https://pypi.python.org/pypi/flake8) tool to check for code style problems.

# Goal
Run the Flake8 tool on the CiviWiki codebase. Identify problems and create a roadmap to resolve errors. Close this issue when our code passes Flake8 tests.

# Flake8 report
Flake8 reported several problems with our code, which have been noted in separate issues:

- [x] https://github.com/CiviWiki/OpenCiviWiki/issues/34
- [x] https://github.com/CiviWiki/OpenCiviWiki/issues/36
- [x] https://github.com/CiviWiki/OpenCiviWiki/issues/37
- [ ] https://github.com/CiviWiki/OpenCiviWiki/issues/38
- [x] https://github.com/CiviWiki/OpenCiviWiki/issues/39

Close this issue once the above issues have been resolved.

**Comment by brylie** [comment]
Many of the Flake8 errors are about unused imports. We can add a 'low hanging fruit' task to remove unused imports from the project. This would be a task that a new developer could take for their first contribution.

**Comment by mattyg915** [comment]
Hi, if no one has gotten to these code cleanup issues (and running flake8 on a clone definitely makes it look like they're still there, I'd like to take these on.

**Comment by brylie** [comment]
Hi @mattyg915. Thanks for your interest! We can add you as a collaborator on this repository, so that you can work on your own branch here.

**Comment by brylie** [comment]
Also, try to keep pull requests focused as much as possible. So, opening your own branch/PR would be an easy way for us to review your work :smile:

**Comment by brylie** [comment]
@mattyg915 I invited you to join the OpenCiviWiki team. What specific sub-issue would you like to work on? #34?

**Comment by mattyg915** [comment]
Thanks! I will definitely keep that in mind. Looks like 34 already has someone working on it, so I'll start with 36.
