### ISSUE TITLE
Move all imports to top of file

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#37]
As part of our clean-code conventions, all imports should be at the top of their file.

# Goal
Move all imports to top of their file. No import errors when running Flake8 (#33).

# Task
The following imports should be moved to the top of their file:

- [x] ./civiwiki/wsgi.py:14:1: E402 module level import not at top of file
- [x] ./civiwiki/wsgi.py:15:1: E402 module level import not at top of file

**Comment by mattyg915** [comment]
Addressed in pull request #63
