### ISSUE TITLE
Threads fail to open on the Dev Server(but work on Text Server)

### ISSUE THREAD

**Issue by mdwest** [CiviWiki/OpenCiviWiki#375]
When I click on any thread I expect the thread to open, but instead, the following error is thrown. 

![image](https://user-images.githubusercontent.com/30572202/55982611-220d1d00-5c4e-11e9-97dc-9fb1dea6eb84.png)

We should look at differences between the Dev server and Test Server to identify this issue.

**Comment by brylie** [comment]
@TomaszKolek this seems elated to the most recent PR of yours. Does this look like a failed migration perhaps?

**Comment by TomaszKolek** [comment]
The problem is related to the migration - there wasn't executed on dev. The deployment procedure needs some adjustment probably.

**Comment by brylie** [comment]
K, can you add a fix for the deployment procedure?

**Comment by TomaszKolek** [comment]
Let me close this one as its done
