### ISSUE TITLE
Broken profile image in navbar

### ISSUE THREAD

**Issue by danielgrijalva** [CiviWiki/OpenCiviWiki#378]
> Information: Ubuntu 18.04, Chromium 73.0.3

Hello! when I signed up for an account I didn't select an image for my profile.

Now, the profile section in the navbar is "incomplete" and ugly:

![image](https://user-images.githubusercontent.com/11547406/56300924-aeef2500-60eb-11e9-91a4-640b97f0e209.png)

As you can see, the image is broken and my username is cut off.
Looking at the HTML, the `src` attribute is empty. Maybe we can use your [`/static/img/no_image_md.png`](https://www.civiwiki.org/static/img/no_image_md.png) file?
```html
<img class="chip-image-profile" src="" alt="danielgrijalva">
```

---

**Update**: after signing out and logging in again, this issue is resolved:
![image](https://user-images.githubusercontent.com/11547406/56302192-21610480-60ee-11e9-8cd3-4823c3701e04.png)

So apparently **this bug only happens right after you sign up** and get redirected to civiwiki.org

**Comment by abhinavsagar** [comment]
@danielgrijalva I am also able to reproduce this. Can i work on this?

**Comment by brylie** [comment]
@abhinavsagar thanks for your interest. Yes, please fix this issue :)

**Comment by danielgrijalva** [comment]
@abhinavsagar Hey sorry, I'm already working on this! I will reach to you If I need help.

**Comment by danielgrijalva** [comment]
Hey :wave:  I found that the image being called in the navbar is located at `request.session.login_user_image`:
  https://github.com/CiviWiki/OpenCiviWiki/blob/5e303e9623094f2d2caa8a312ce7b5108ca8502d/project/webapp/templates/partials/utils/global_nav.html#L22

Then, searching through the code for the exact moment when the image is saved in the session, I found the function `uploadProfileImage()`, which is called at the [user-setup.js](https://github.com/CiviWiki/OpenCiviWiki/blob/5e303e9623094f2d2caa8a312ce7b5108ca8502d/project/webapp/static/js/user-setup.js#L238-L244) script.
https://github.com/CiviWiki/OpenCiviWiki/blob/3c75e7fe79d727c022c752dcd35159fcfb8f6151/project/api/write.py#L388

See, _that's_ the problem: if the user doesn't upload an image at sign up, no image will be stored in the session, and the profile image at the navbar will be empty.

So why is it that logging out and in again solves the problem? well, at the login function you're doing this:
https://github.com/CiviWiki/OpenCiviWiki/blob/dc6a127ea821d43c43505432029e63fa917a7529/project/authentication/authentication.py#L63

A possible solution is to do the same at [`base_view()`](https://github.com/CiviWiki/OpenCiviWiki/blob/dc9c33ccecf6bf3d8f9fd6fb8d812d377cc4889c/project/frontend_views/views.py#L17) (`/` route):
```python
if not 'login_user_image' in request.session.keys():
    request.session["login_user_image"] = a.profile_image_thumb_url
```

I tested this and it solves the issue. @brylie what do you think? :thinking:

**Comment by brylie** [comment]
Looks good. Please open a pull request, so we can test.
