### ISSUE TITLE
When uploading a profile image failed then user needs to go back and click on Edit Profile again to upload new image

### ISSUE THREAD

**Issue by richifuentes** [CiviWiki/OpenCiviWiki#392]
When users uploading a profile picture and this failed with the error message "Please use an image that 1280 x 960 pixels or smaller" then users need to go back to the profile and click on Edit Profile again in order to upload a new picture. Just clicking on Choose Picture doesn't do it.

**Comment by brylie** [comment]
@all-contributors please add @richifuentes for bug

**Comment by wassafshahzad** [comment]
Is this still an issue ? if soo can I be assigned on it ?

**Comment by brylie** [comment]
@wassafshahzad can you try to reproduce the issue? If you can't reproduce the issue, we can close the bug report as stale.

**Comment by wassafshahzad** [comment]
Sure I will try it 
Thank you
