### ISSUE TITLE
User-signup flow somewhat confusing

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#4]
The sign-up process for new users is somewhat confusing. 

# Observed behavior
The user is presented with an apology message immediately after filling out the sign-up form, which seems to indicate that the platform is in closed beta. However, an account activation email is still sent to the user, allowing them to complete the registration process.

# Expected behavior
Upon filling out the registration form, the user might see a welcome page. The welcome page can inform them to check their inbox for an activation email. The confirmation screen might also mention that the site is in *open beta*.

Alternatively, the site might disable registration until open beta.

# Steps to reproduce
1. visit https://www.civiwiki.org
2. click any of the sign in/sign up buttons
3. fill in and submit the form

## Sign up flow
![peek 2017-06-14 18-51](https://user-images.githubusercontent.com/17307/27142418-9d955528-5133-11e7-8119-d7a01d7267d3.gif)

## Apology screen (beta period)
![screenshot_20170614_190251](https://user-images.githubusercontent.com/17307/27142588-261faf92-5134-11e7-8a7a-eb606da3cc47.png)

## Confirmation/activation email received
![screenshot_20170614_185522](https://user-images.githubusercontent.com/17307/27142435-b3f132ce-5133-11e7-8cf4-f8016082bee0.png)

**Comment by GokuMizuno** [comment]
I was unable to replicate this error.  W10, Firefox 58.0.2, gmail account.

**Comment by brylie** [comment]
Closing.
