### ISSUE TITLE
Fix Syntax Error: Unexpected token ')'. Expected ')' to end and argument list

### ISSUE THREAD

**Issue by richifuentes** [CiviWiki/OpenCiviWiki#401]
Fix Syntax Error: Unexpected token ')'. Expected ')' to end and argument list on File user-setup.js
![image](https://user-images.githubusercontent.com/9931749/57321500-c37a7800-7101-11e9-8bba-a965b88faacb.png)

**Comment by brylie** [comment]
@richifuentes are you going to open a PR for this issue?

**Comment by brylie** [comment]
I believe this is fixed now. Please test on https://civiwiki-dev.herokuapp.com/
