### ISSUE TITLE
Automatically audit/monitor source code quality metrics

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#44]
In order to promote maintainability and readability, we can use common measures of 'code complexity' as heuristics when developing/refactoring code.

[CodeClimate](https://codeclimate.com/) will automatically scan CiviWiki sourcecode, and return a score based on common 'maintainability' metrics. These metrics include file/function length, number of function parameters, duplicate code, etc. CodeClimate is [free for open source projects](https://codeclimate.com/oss/), and is used, for example, by the [Django project](https://codeclimate.com/github/django/django).

# Goal
Have CiviWiki code automatically audited for maintainability and quality.

# Task
- [x] Configure CodeClimate to scan the OpenCiviWiki repository
- [ ] Add CodeClimate badge to top of OpenCiviWiki README

**Comment by mdwest** [comment]
I have linked code climate to the proper repository now. Are you adding the badge to the readme @brylie? 

-mw

**Comment by brylie** [comment]
Done.
