### ISSUE TITLE
Automatically audit project dependencies

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#45]
As a general guideline, we should strive to keep our project dependencies up-to-date. In order to help with this, there are online services that can check our project dependencies and indicate when dependencies are insecure or outdated.

# Examples
[Requires.io](https://requires.io/) is one service that will monitor Python project dependencies. It also offers a badge that can be placed in our README as a reminder to update dependencies.

[Pyup](https://pyup.io/) will monitor project Python dependencies, and send a pull request when security updates are needed.

# Goal
Find an automated method/service to monitor CiviWiki project dependencies. Have a visual indicator in our README for community and contributors to see the dependency status at a glance.

# Task
If we decide to go with requires.io, then the following steps are relevant:

- [ ] configure requires.io to audit the CiviWiki project repository
- [ ] add requires.io badge to top of CiviWiki README

**Comment by pscheid2** [comment]
It looks like we have both pyup-bot and dependabot set up for this repo already. Both are creating automatic pull requests to update dependencies when they become out of date.
