### ISSUE TITLE
locate.js exposing API key to client

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#464]
The geocoding script is exposing the Google API key to the client:

https://github.com/CiviWiki/OpenCiviWiki/blob/af3cfc3dddc5f07ac527bea922a1a74977e7fc63/project/webapp/static/js/utils/locate.js#L129-L131

As far as I can tell, this is not advisable, because it would allow people to make API calls to Google with the CiviWiki key.

This doesn't seem like a trivial fix, as it would need an endpoint to proxy the geolocation results to the client, but should be top priority.

**Comment by jcolborn-dropdeadgames** [comment]
The Google API key is a client-side key. You can either use a proxy as suggested or you can use API restrictions from Google to stop any requests for that key that are not referred by a certain source URL.

**Comment by brylie** [comment]
OK, we will have to make sure those restrictions are in place for the production key. Thanks for pointing that out @jcolborn-dropdeadgames.
