### ISSUE TITLE
first_name is not defined

### ISSUE THREAD

**Issue by JonanOribe** [CiviWiki/OpenCiviWiki#468]
At "Setup your location" page, when I push over "finish", I get the message:

```
Uncaught ReferenceError: first_name is not defined
    at n.setupUser (user-setup.46ccad28d030.js:225)
    at HTMLDivElement.dispatch (jquery.min.d0212568ce69.js:3)
    at HTMLDivElement.q.handle (jquery.min.d0212568ce69.js:3)
```
But my profile information has all the text boxes with text. Any idea?

**Comment by brylie** [comment]
@JonanOribe please pull the latest develop. This issue should be resolved.

**Comment by brylie** [comment]
@all-contributors please add @JonanOribe for bug

**Comment by brylie** [comment]
This is now resolved.
