### ISSUE TITLE
My Rep Tab fails to display

### ISSUE THREAD

**Issue by mdwest** [CiviWiki/OpenCiviWiki#513]
The My Representative tab should display federal representatives and show a rating of how often their votes align with user support/opposition to bills. 

Currently, the display is bugged and there may be back-end server issues 

![image](https://user-images.githubusercontent.com/30572202/57984008-1f5bcf80-7a25-11e9-96d5-cf7cdf77265a.png)

Note: This bug may only be associated with old accounts. I see my representatives for a new account I created. The actual bug might be the need for a button to reset location for an account.

**Comment by brylie** [comment]
@TomaszKolek was this working as part of your tasks?

**Comment by brylie** [comment]
@TomaszKolek can you please verify this bug?

**Comment by mdwest** [comment]
@TomaszKolek The bug appears to be associated with old accounts. A new account I created shows representatives. But for some reason, old accounts don't. I remember you mentioning this possibility while working on the representative contract. Any insight into why this issue persists is much appreciated.

**Comment by ali1810** [comment]
I would like take up this challenge

**Comment by brylie** [comment]
OK, thanks! Let us know, if you need any help. Create a pull request with any changes you make.

**Comment by ali1810** [comment]
Dear

Thanks for the reply ..

I want to add in the library module SVR the option of feature scaling .

Just let me know how I can proceed and incorporate the update in the sk learn library.

Regards

Ali
________________________________

**Comment by gorkemarslan** [comment]
@brylie, now we don't have reps tab so we can close this issue. Right?

**Comment by brylie** [comment]
Yep. Thanks for helping clean up the backlog :smiley:
