### ISSUE TITLE
Materialize Toast Message is shown too quickly to the user

### ISSUE THREAD

**Issue by richifuentes** [CiviWiki/OpenCiviWiki#514]
In the "Setup your location” when the message "We could not use your browser's location. Please try entering your location" is shown with materialize.toast, this message is only shown very briefly so the user cannot really understand what is going on. My suggestion is the time of materialize.toast should be increase or a permanent message should be shown to the user so that she/he knows what is happening.
![image](https://user-images.githubusercontent.com/9931749/58106711-d18fc480-7be8-11e9-960c-72c96bf6dbce.png)

**Comment by brylie** [comment]
Great first issue! Would you like to extend the Materialize.toast timeout?

**Comment by richifuentes** [comment]
Sure, would 10 seconds be ok?

**Comment by JDRanpariya** [comment]
Is this issue solved?

**Comment by Yogita98** [comment]
@brylie is this issue up for grabs?

**Comment by brylie** [comment]
@Yogita98 yes, please open a pull request with your changes. :-)
