### ISSUE TITLE
add https support in the civiwiki-backend docker 

### ISSUE THREAD

**Issue by richifuentes** [CiviWiki/OpenCiviWiki#517]
deploying docker for setting up the development environment is the easiest way to get openciviwiki up and running on anyone's Laptop. After deploying the app with docker the first time you call 0.0.0.0:8000 you get a page where you need to set up an account, I cannot get pass the Locate page since the only way to enter the address is using google's geolocate functions, and these are disabled by the browsers (all of them) if the web site does not support https, I also get a "We could not use your browser's location. Please try entering your location" toast. See below:
![image](https://user-images.githubusercontent.com/9931749/58264512-48aa9180-7d7e-11e9-9579-afdfa822d5bb.png)

**Comment by tractaylor** [comment]
do you know if a self signed cert will work?  I know alot of browsers still do not like self signed certs.

**Comment by brylie** [comment]
I think we should consider 

1. deprecating the hard-dependency on Google services, and 
2. allowing users to proceed to the site without providing location information.

**Comment by tractaylor** [comment]
that sounds like a good idea.  Without location we could not link to local leaders/politians but we could let them choose that if it was necessary.  And some people might not want to say where they are from anyway.

**Comment by gorkemarslan** [comment]
@brylie, currently we are not using location data so we can close this issue. Right?
