### ISSUE TITLE
"read-only file system" error when running "docker-compose up"

### ISSUE THREAD

**Issue by wjkpowell** [CiviWiki/OpenCiviWiki#530]
I'm trying to set up my development environment so I can contribute to this project, and I'm running into the following error when I run `docker-compose up` as instructed in [docker-setup.md](https://github.com/CiviWiki/OpenCiviWiki/blob/dev/readmes/docker-setup.md)

Here's the content of the `.env` file I created. I've redacted my actual Django and Google Map keys:

```
SUNLIGHT_API_KEY=""
GOOGLE_MAP_API_KEY="My_Google_Map_Key"
DJANGO_SECRET_KEY="My_Django_Secret_Key"
PROPUBLICA_API_KEY=<pro_publica_api_key>

POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=civiwiki_db
POSTGRES_USER=civiwiki
POSTGRES_PASSWORD=civiwiki


CIVIWIKI_LOCAL_DB_HOST=db
CIVIWIKI_LOCAL_NAME=civiwiki_db
CIVIWIKI_LOCAL_USERNAME=civiwiki
CIVIWIKI_LOCAL_PASSWORD=civiwiki

REDIS_URL=redis://redis:6379
DEBUG=True
```

The error I'm seeing is:

`ERROR: failed to update bridge store for object type *bridge.networkConfiguration: open /var/lib/docker/network/files/local-kv.db: read-only file system`

I did find an [SO article](https://stackoverflow.com/questions/53143849/docker-compose-error-read-only-file-system) with a similar error (not exactly the same error), but there are no answers.

Any ideas?

**Comment by brylie** [comment]
What version of Docker are you running? What is your operating system?

**Comment by brylie** [comment]
Did you run Docker with sudo at any point? Check the filesystem ownership/permissions in your project folder, particularly the folder where Postgres container stores data.

**Comment by wjkpowell** [comment]
This is a little bit embarrassing. I don't think I have Postgres installed at all!

I think I lost this jumping back and forth between the `docker-setup.md` and `local-setup.md`. Since it seems Postgres is required to complete the Docker setup, perhaps it would be worth mentioning Postgres in the Docker readme as well.

Thanks for being so responsive! I haven't installed Postgres yet (need to research this a bit), but it seems like this is probably the issue. I'll confirm when I get up and running :)

**Comment by brylie** [comment]
Well, `docker-compose up` is supposed to install a Postgres image, so you don't have to. The Postgtes image will create a folder for data when it is created. This folder may be causing problems for you, but I am not certain. Could you record a screencast of this issue, starting with a fresh `git clone`?

**Comment by wjkpowell** [comment]
Yes, I will give this a shot tonight

**Comment by wjkpowell** [comment]
Hey, here's a link to a video with the repro steps. Not winning any awards for productino value here ;)

2 parts b/c I have no video editing software on my machine.

Part 1: https://youtu.be/h1DZVIlpNN0
Part 2: https://youtu.be/9ukUBVbQEVg

I tried installing PostgreSQL since but not working yet.

**Comment by brylie** [comment]
K, you don't need to install Postgres, since Docker handles that for you. What are your filesystem permisisons in the project directory? e.g.  `ls -l`

**Comment by wjkpowell** [comment]
Here's the result in the `project` directory:

```
-rw-r--r--   1 delores  staff  198 12 Jun 20:47 Procfile.dev
-rw-r--r--   1 delores  staff  238 12 Jun 20:47 Procfile.prod
drwxr-xr-x  20 delores  staff  640 12 Jun 20:47 api
-rw-r--r--   1 delores  staff  154 12 Jun 20:47 app.json
drwxr-xr-x   8 delores  staff  256 12 Jun 20:47 authentication
drwxr-xr-x   9 delores  staff  288 12 Jun 20:47 civiwiki
drwxr-xr-x   6 delores  staff  192 12 Jun 20:47 core
drwxr-xr-x   5 delores  staff  160 12 Jun 20:47 data
drwxr-xr-x   5 delores  staff  160 12 Jun 20:47 frontend_views
-rwxr-xr-x   1 delores  staff  251 12 Jun 20:47 manage.py
-rw-r--r--   1 delores  staff   14 12 Jun 20:47 runtime.txt
-rw-r--r--   1 delores  staff  208 12 Jun 20:47 setup.cfg
drwxr-xr-x  10 delores  staff  320 12 Jun 20:47 test_framework
drwxr-xr-x   4 delores  staff  128 12 Jun 20:47 webapp
```

Also, here's the result in the `OpenCiviWiki` directory:

```
-rw-r--r--   1 delores  staff   1383 12 Jun 20:47 Dockerfile
-rw-r--r--   1 delores  staff  31610 12 Jun 20:47 License.md
-rw-r--r--   1 delores  staff    109 12 Jun 20:47 Procfile
-rw-r--r--   1 delores  staff  16385 12 Jun 20:47 README.md
-rw-r--r--   1 delores  staff    609 12 Jun 20:47 docker-compose.yml
drwxr-xr-x   4 delores  staff    128 12 Jun 20:47 docs
-rwxr-xr-x   1 delores  staff    341 12 Jun 20:47 entrypoint.sh
drwxr-xr-x  16 delores  staff    512 12 Jun 20:47 project
drwxr-xr-x   7 delores  staff    224 12 Jun 20:47 readmes
-rwxr-xr-x   1 delores  staff    550 12 Jun 20:47 requirements.txt
-rw-r--r--   1 delores  staff     14 12 Jun 20:47 runtime.txt
```

**Comment by brylie** [comment]
Hm, the `data` directory seems to be writable:

> drwxr-xr-x   5 delores  staff  160 12 Jun 20:47 data

What happens if you delete `data` and then re-run `docker-compose up`?

**Comment by wjkpowell** [comment]
This seems to have worked! `docker-compose up` runs now, and I can get onto the rest of the setup.

Not sure if there's anything you'd like to do here to avoid this issue for others in the future.

**Comment by brylie** [comment]
Closing as resolved.
