### ISSUE TITLE
Review Flake8 configuration, remove rules from ignore that would improve our code quality

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#55]
While auditing the project code quality (#33), I noticed that several Flake8 rules were being ignored:

https://github.com/CiviWiki/OpenCiviWiki/blob/3c287290e907c0e1aa2c82f6588afcdb4b3b81e4/setup.cfg#L1-L2

While it may be desirable to ignore some Flake8 rules, there are likely rules being ignored that would encourage good coding practices. For example, we are lacking a lot of docstrings in CiviWiki modules and classes.

# Rules we currently ignore

## Continuation lines
- E121, continuation line under-indented for hanging indent
- E122, continuation line missing indentation or outdented
- E126, continuation line over-indented for hanging indent
- E127, continuation line over-indented for visual indent
- E128, continuation line under-indented for visual indent
  - https://stackoverflow.com/questions/15435811/what-is-pep8s-e128-continuation-line-under-indented-for-visual-indent
- E131, continuation line unaligned for hanging indent

## Comments
- E265, block comment should start with ‘# ‘
- E261, at least two spaces before inline comment
- E262, inline comment should start with ‘# ‘
- E266, too many leading ‘#’ for block comment

## Whitespace
- E501, line too long (82 > 79 characters)
- E302, expected 2 blank lines, found 0
- E303, too many blank lines (3)
- E226, missing whitespace around arithmetic operator
- E231, missing whitespace after ‘,’, ‘;’, or ‘:’
- E201, whitespace after ‘(‘
- E202, whitespace before ‘)’
- E203, whitespace before ‘:’
- W293, blank line contains whitespace
- W391, blank line at end of file
- W292, no newline at end of file
- W503, line break occurred before a binary operator

## Other
- E123, closing bracket does not match indentation of opening bracket’s line
- F403, ‘from module import *’ used; unable to detect undefined names
- E401, multiple imports on one line
- E731, do not assign a lambda expression, use a def

# Goal
Refine the Flake8 configuration. Ignore fewer Flake8 rules. Improve our code quality/practices.

# Tasl
- [ ] Add description of each ignored Flakd8 rule to this isse
- [ ] Determine which Flake8 rules to continue ignoring
- [ ] Remove useful Flake8 rules from the ignore list, to improve our project code quality

**Comment by brylie** [comment]
After a brief search, I found out that we should be able to exclude our migrations from Flake8:

```
 flake8 --exclude=migrations
```

**Comment by brylie** [comment]
I think we can stop ignoring the whitespace rules. I see that we are overriding the line length rule, but would defer to Two Scoops of Django authors regarding their opinion about line length:

> On open source projects, there should be a hard 79-character limit. Our experience has shown
that contributors or visitors to these projects will grumble about line length issues; however, it
has not kept contributors away and we feel the value isn’t lost.

**Comment by jl24** [comment]
@brylie I believe these were personal flake8 configs from a previous developer to the project that was never revisited. I'm not opposed to removing all of these rules for now, and opening the floodgate for the changes that it will require

**Comment by gorkemarslan** [comment]
I am assigning myself to this issue. I think I'll remove most of the rules. (maybe all of them). I'm searching for which rules are appropriate for the Django projects.

**Comment by brylie** [comment]
Sounds good. We should also harmonize the flake8 and `black` rules, as [described in the `black` documentation](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8).

Please see the related pull request to add a flake8 step to our CI process: https://github.com/CiviWiki/OpenCiviWiki/pull/1119

**Comment by gorkemarslan** [comment]
In our linting workflow:

https://github.com/CiviWiki/OpenCiviWiki/blob/ddbaebfeec47bb583c27774e2fb1cb6a97ecdaae/.github/workflows/main.yml#L34-L39

@brylie, according to the link you sent I will set up `flake8` to be compatible with `black`:

```
max-line-length = 88
extend-ignore = E203
```

So I only apply these changes and remove others.

One thing worth mentioning is that recommended `max-line-length` by [Django](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#python-style) is 120.

> An exception to PEP 8 is our rules on line lengths. Don’t limit lines of code to 79 characters if it means the code looks significantly uglier or is harder to read. We allow up to 119 characters as this is the width of GitHub code review; anything longer requires horizontal scrolling which makes review more difficult. 

But `black` default is 88 so I'll set up `flake8` to be 88. Let's do not listen to what Django says here. :)
