### ISSUE TITLE
The link is not working https://www.civiwiki.org

### ISSUE THREAD

**Issue by 0xrishabh** [CiviWiki/OpenCiviWiki#598]

**Comment by brylie** [comment]
Yep. It looks like the domain registration may be misconfigured or has lapsed.

**Comment by abhishekmadhu** [comment]
Hi,
How can we resolve this? Do we have a plan?
Thanks.

**Comment by StrangledJTAC** [comment]
whois lookup shows the domain registrant to be an organization named "samirnet -domain names for sale", so it seems that our registration with galcomm lapsed and it was sold to someone else. Now unless we find some funds and acquire it again, I don't see a solution except switching to a different domain.

**Comment by ganeshbhargav** [comment]
We can register this domain again using these options :-
They are widely used.
https://domains.google/
https://www.godaddy.com/domains

I checked https://domains.google/ and https://www.civiwiki.org is still available.

**Comment by brylie** [comment]
On closer inspection, **civiwiki.org** is *not* available via domains.google. Only **civilwiki.org** is suggested:
![image](https://user-images.githubusercontent.com/17307/95647869-9b076200-0adb-11eb-83f5-0138c0a20286.png)


I checked Namecheap and Gandi.net as well, and Namecheap lists civiwiki.org as a premium domain ($500).
![image](https://user-images.githubusercontent.com/17307/95647864-80cd8400-0adb-11eb-8a45-02b31d26c2a6.png)

**Comment by brylie** [comment]
I went ahead and registered **civi.wiki**
![image](https://user-images.githubusercontent.com/17307/95648066-377e3400-0add-11eb-9b9a-a33224146ece.png)

I'll try to get the domain configured over the next couple of weekends, and outline a roadmap for the continuation of this project.

**Comment by pscheid2** [comment]
Do we still have access to our heroku account for deploying the app?

I'm curious if we will need to set up a new account to deploy milestone 2.0.

**Comment by brylie** [comment]
I'd like to steer us away from Heroku at some point (perhaps not immediately.) 

I believe the CiviWiki development deployment (including database) can run on a single [Dokku](https://dokku.com/) instance costing around 3-5€ per month on [Hetzner](https://www.hetzner.com/cloud) or [DigitalOcean](https://www.digitalocean.com/products/droplets/). 

Likewise, the [DigitalOcean App Platform](https://www.digitalocean.com/products/app-platform/) offers a compelling and affordable alternative to Heroku, including automated deployments directly from GitHub source. DigitalOcean App Platform would cost around $15/month for a [managed database](https://www.digitalocean.com/products/managed-databases-postgresql/) plus the cost of droplet resources for CiviWiki deployments (e.g. dev/staging). So, a minimal DigitalOcean App Platform running cost is around $20/month.

**Comment by matthewdeanmartin** [comment]
You should remove the www.civiwiki.org link from the GitHub project front page if y'all don't control the domain anymore. Parked domains often are loaned out to malicious code distributors.

**Comment by brylie** [comment]
@matthewdeanmartin good point. I removed the link. We own the civi.wiki domain, but don't have any content there. Perhaps we can set up a static placeholder for now.

**Comment by brylie** [comment]
The static placeholder site is now live at https://civi.wiki
