### ISSUE TITLE
Ran into an issue setting up a dev environment using the CONTRIBUTING.md

### ISSUE THREAD

**Issue by tractaylor** [CiviWiki/OpenCiviWiki#65]
As I was following the directions to set up a dev environment, I ran into an issue when trying to run pip install -r requirements.txt.

This is the error I copied from the shell...
##
Collecting psycopg2==2.6.1 (from -r requirements.txt (line 8))
  Using cached psycopg2-2.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
##

After doing some searching, I found some instructions.  Running the following commands

$ sudo apt-get install python-psycopg2
$ sudo apt-get install libpq-dev

Then I reran the pip install -r requirements, it ran successfully.

**Comment by tractaylor** [comment]
I plan on setting up another VM for this project this weekend.  I will try to grab the log as well.  I suspect that maybe I just needed to install libpq-dev.  I honestly have not looked to see what that module is to help diagnose this issue i ran into.

**Comment by brylie** [comment]
@tractaylor good sleuthing. Add notes about your findings to our README, so other developers can overcome the issue.
