### ISSUE TITLE
User Account Page is not saving the location

### ISSUE THREAD

**Issue by tractaylor** [CiviWiki/OpenCiviWiki#66]
When I type in my address (not use the "Locate Me" feature), it loads the representatives.  But when I leave the page (go back to my feed), and come back to the user account page, my address is gone and the list of representatives is gone.

After I tried to use the "Locate Me" feature, it again loads the representatives, but after I leave and come back the location info is missing along with the representatives.

**Comment by mdwest** [comment]
I think this may be a display bug. On my account, it appears to display the correct information but just loses the address on the account settings page. Perhaps this can help identify the bug in the code?
