### ISSUE TITLE
Add feature to add a link to a Representative's Web Page

### ISSUE THREAD

**Issue by tractaylor** [CiviWiki/OpenCiviWiki#67]
This would be a nice feature on the My Reps page.  It shows the user's representatives.  It would be nice to have a link to a page that shows information about them.

**Comment by mdwest** [comment]
This is a great addition. This info is available through open states and ProPublica, but we need to integrate it!

**Comment by tractaylor** [comment]
I did read over openstates api and ProPublica over the weekend.  There is so much civiwiki could get from there.  The most interesting I thought was how you can get how each representative voted on a bill.  Imagine linking that information to a bill that is linked to a civi!
