### ISSUE TITLE
When running on local server says 'DJANGO_SECRET_KEY' error

### ISSUE THREAD

**Issue by JDRanpariya** [CiviWiki/OpenCiviWiki#677]
**I have forked the repo and now I am trying to run website on local server with code "python manage.py runserver"**
_An error appears saying_-
 "F:\Git Contribution\OpenCiviWiki\project\civiwiki\settings.py", line 44, in <module>
    SECRET_KEY = get_env_variable("DJANGO_SECRET_KEY")
  File "F:\Git Contribution\OpenCiviWiki\project\civiwiki\settings.py", line 25, in get_env_variable
    raise ImproperlyConfigured(error)
django.core.exceptions.ImproperlyConfigured: Environment variable 'DJANGO_SECRET_KEY' not found.`

**Comment by brylie** [comment]
You will need to set the `DJANGO_SECRET_KEY` environment variable prior to running CiviWiki. `DJANGO_SECRET_KEY` can be any string of characters. What is your operating system?

**Comment by JDRanpariya** [comment]
win10

**Comment by brylie** [comment]
Try the following in your terminal:

```
cmd /C "set DJANGO_SECRET_KEY=changeme && python manage.py runserver"
```

**Comment by brylie** [comment]
This is the Superuser question I used for reference:
https://superuser.com/questions/223104/setting-and-using-variable-within-same-command-line-in-windows-cmd-exe

**Comment by BrianPainter** [comment]
pull request #772 addresses the issue of not having defaults if the environment variable is not set.

**Comment by JDRanpariya** [comment]
cool if you think issue is fixed. We can close this issue.
also thanks.
