### ISSUE TITLE
django environ

### ISSUE THREAD

**Issue by JDRanpariya** [CiviWiki/OpenCiviWiki#678]
In .gitignore .env_sample is provided but when I looked for main settings.py environ is not used I don't understand how to set environment variables(such as api_keys etc.) here...

And can we use django environ instead of os.environ I think code will be easy and clean

**Comment by brylie** [comment]
What is your operating system?

**Comment by JDRanpariya** [comment]
Windows 10

**Comment by brylie** [comment]
The Windows PowerShell documentation describes [how to set environment variables](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7). The environment variables are needed temporarily. If you want, create a shell script to set the environment variables with a single command :-)

**Comment by JDRanpariya** [comment]
I am working on django environ so it's easy to set keys

**Comment by brylie** [comment]
OK, would you like to open a pull request with any changes or documentation for other developers to use Django environ?

**Comment by JDRanpariya** [comment]
ya but's it's not yet completed I would appreciate help from others because I'm facing some issues with loading variables

**Comment by BrianPainter** [comment]
@JDRanpariya adding django environ has been completed and merged into master.

**Comment by BrianPainter** [comment]
@JDRanpariya should this issue be closed?

**Comment by JDRanpariya** [comment]
@BrianPainter Thanks for that
