### ISSUE TITLE
While looking over the beta site, I had a difficult time finding where to go to manage my settings

### ISSUE THREAD

**Issue by tractaylor** [CiviWiki/OpenCiviWiki#68]
Looking around the beta site, I was trying to find where to edit my account settings.  I was on the phone with Mitchell and ended up asking him.  

With it being a button with a + graphic, it made me think it was to add something, not edit my profile.  

I had thought the "Manage" button on the feed page would get me to a managed my user acct page.

**Comment by mdwest** [comment]
This is great feedback. We have had design disagreement about the circle navigation from the beginning.  I would be interested in either developing a more standard nav bar for the system, or in the alternative, a better graphic to make it apparent that the circle is our navigation hub? if thats possible?
