### ISSUE TITLE
Remove dependency on Google Maps

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#7]
The Google Maps dependency may be unnecessary, and poses an additional encumbrance when setting up a development environment. For example, without a Google Maps API key, the new user registration wizard cannot be completed:

![screenshot_20170714_204541](https://user-images.githubusercontent.com/17307/28223790-68aa8cac-68d5-11e7-8394-0180b680d470.png)

Remove all code related to Google maps:
https://github.com/CiviWiki/OpenCiviWiki/search?q=google

**Comment by brylie** [comment]
@EkanshBhatnagar would you like to take this issue?

**Comment by jdcbautista** [comment]
If they don't, can I?

**Comment by brylie** [comment]
@jdcbautista sure thing! I'll go ahead and assign you.

Please let me know if I may be of assistance.

**Comment by jdcbautista** [comment]
@brylie Thanks!  

I've forked the repo and started making some changes today.  I'm currently stuck installing modules.  I'm running python 2.7.16 within a virtualenv and zsh is killing every operation I try to run.  

Currently on an M1 Mac.  Did some digging and others are experiencing trouble with python 2.7 + virtualenv on M1 chips.

I'll dig a bit more and maybe take a stab on an intel based laptop.

**Comment by GokuMizuno** [comment]
Whatever happened to the pre-2018 upgrade to Python 3 performed on the
codebase?

Was that not merged?

**Comment by brylie** [comment]
@jdcbautista, as @GokuMizuno mentions, CiviWiki was upgraded to support Python 3.x. We now only support Python 3.7 and above. 

The Python 3 upgrade was done to keep our dependencies up-to-date while aligning with the broader [decision to sunset Python 2.x on Jan. 1st, 2020](https://www.python.org/doc/sunset-python-2/). Admittedly, there may be some files that mention Python 2.x, that have slipped through our development process.

Are you able to:
- create a Python 3.7 virtual environment, or
- use our `docker-compose.yml` to start up a Python 3.7 development environment?
