### ISSUE TITLE
Action items from 2017-09-11 meeting

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#73]
- [ ] Add GitFlow guidelines to README
  - [ ] Add simple feature/develop diagram
- [ ] deprecate beta blocker
  - each user can send invites
  - invite someone to a specific CiviWiki article
- [ ] Adding a civi should be simpler
  - having to type name of a link is difficult
  - when clicking ...

**Comment by mdwest** [comment]
Getting into a civi-thread 

Delete the thred landing page + limit content to fit on feed page

**Comment by mdwest** [comment]
IMprove ability to post and link civies 

1) When selectiong civi type (problem cause or solution) display only civies which can be linked (i.e. problmes to causes to solution withon the thread)

**Comment by mdwest** [comment]
rather than typing the title of a civi you want to link, display a list of potential civies and allow user to select (link button) and then click the civi or civies they want to link

**Comment by mdwest** [comment]
Linking constraints 
Problem doesn't link to anything 
cause links to problem 
solution links to causes

**Comment by brylie** [comment]
Add feature for draft stage Civis

**Comment by brylie** [comment]
Add public/private designation for Civis
  - owner(s) can invite people to view private Civis

**Comment by jl24** [comment]
@brylie I've been working a bit on the frontend portions in individual thread page so I would like to take over this issue if possible

**Comment by brylie** [comment]
> I would like to take over this issue if possible

Cool beans. Do you mean all of the TODO items @mdwest has described in this issue, or is there a specific GitHub issue you are referring to?

**Comment by jl24** [comment]
More of the items that @mdwest has mentioned. Looks like the only issue i see related to the individual thread view changes is #11, and the three items seem to detract from the original issue here. I think it might be best to create a new, more focused issue for this so it could be more easily tied to a PR.

**Comment by brylie** [comment]
Cool, would you mind creating the issue?
