### ISSUE TITLE
Create CiviWiki API design guidelines

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#77]
After discussing with @jl24, we agreed that the CiviWiki APIs are somewhat inconsistent. To remedy this, we should put together an initial API  Design guidebook. These designs will encourage consistency throughout CiviWiki APIs.

**Comment by jl24** [comment]
resolving #24 will help us point towards the right direction, and i like your idea of following the OpenAPI Specification

**Comment by AbhijithGanesh** [comment]
@brylie and @JOO33 I am closing this is no longer relevant.
