### ISSUE TITLE
Create project continuation roadmap

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#781]
The CiviWiki project has been on hiatus. Let's reboot the development.

Create a project roadmap with the following goals:
- simplicity
- sustainability
- internationalization

**Comment by JOO33** [comment]
@brylie I would like to also help with creating the new roadmap!

**Comment by brylie** [comment]
@jl24 I have added the 2.0 milestone with the goals of 

- refactoring
- simplifying
- fixing technical debt
- reviving project development

Please review issues from the existing backlog and assign relevant issues to 2.0 milestone (or close issues no longer relevant).

The most radical change I would propose would be that we
- deprecate the "front-end" JavaScript codebase 
- use standard Django templates/views
- use something like [Django Unicorn 🦄](https://www.django-unicorn.com/) if/when dynamic page elements are needed (we don't need a whole JavaScript framework/SPA for a few dynamic page elements)

**Comment by brylie** [comment]
https://github.com/CiviWiki/OpenCiviWiki/milestone/5

**Comment by JOO33** [comment]
@brylie I 100% agree with the changes that you propose. The JavaScript codebase is and has been a big hindrance. I'll go through the backlog.

**Comment by brylie** [comment]
Thanks @jl24! I see you are already busy gardening the backlog :-)

**Comment by JOO33** [comment]
@brylie I went through an initial run through for the 2.0 milestone and believe the following are relevant.

**Project Planning/Setup**
#781, #87, #598

**DevOps**
#146, #45, #47, #79, #157

**Updating Dependencies**
Libraries: #18, API: #7 , #99

**Code Quality/Documentation**
#21, #55, #77, #165

Migration from JS to Python & refactor Django codebase
#827, #83

There are also core feature related bugs (issues  #121, #10, #125, #513), but most will need to be revisited after the front-end is changed. Do you think it will helpful to keep these bug reports? Or should we de-clutter now since these issues will be mostly relevant to the old JS based codebase?

**Comment by brylie** [comment]
Let's keep them around until we can verify the functionality works in the new front-end. We can add a label to remind us to re-visit the bug reports.

**Comment by brylie** [comment]
@JOO33 I opened an RFC to discuss another relatively large change/simplification to the CiviWiki codebase. 

https://github.com/CiviWiki/OpenCiviWiki/issues/830

If we improve/approve the RFC, it would seem relevant to include in a 2.0 release.

**Comment by brylie** [comment]
Hei @JOO33, would you mind changing my role in the CiviWiki members to be an Owner? I want to set up a team and send invites to all of our contributors so they are included in the organization as well.

**Comment by pscheid2** [comment]
Hey all! It's awesome to see you picking this project back up.

I'm curious what you think a good goal for a minimal set of features to get working in production would be? I definitely agree that simplification is needed, both on the technical side and on the product side of the project.

Maybe we start working to get the app back up in production with just civis/civi threads and a super basic feed of threads?

**Comment by brylie** [comment]
> Maybe we start working to get the app back up in production with just civis/civi threads and a super basic feed of threads?

That sounds like a great MVP :-)

**Comment by brylie** [comment]
Closing this issue as we have defined a [2.0 Milestone](https://github.com/CiviWiki/OpenCiviWiki/milestone/5) with many planned tasks.
