### ISSUE TITLE
Refactor frontend code to follow component structure - Due 6/27/2018

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#82]
Our frontend code is somewhat disorganized. We agreed to re-structure the frontend code, so that it is easier to understand.

# Goal
- Improve project maintainability by re-structuring code.
- Prepare to replace frontend framework, by re-structuring code to follow component-oriented structure

# Resources
## Backbone architecture
- [Organizing a Backbone Application](http://thinkingonthinking.com/organizing-a-backbone-application/) (2013)

## Componentized web
- [The Web's Declarative, Composable Future.](https://addyosmani.com/blog/the-webs-declarative-composable-future/) by Addy Osmani

**Comment by brylie** [comment]
I think many Backbone projects may pre-date the 'componentized' web application movement. So, we may need to look towards other component frameworks for inspiration, and define our own bespoke component structure.

**Comment by mdwest** [comment]
Not well versed in the technical details, but if continuing to use the backbone framework will get us to a stable version sooner, I vote we use it and create our own standardization. Might be good to document our front-end "component structure" so we can easily share it with any developer interested in contributing to the front-end.

**Comment by jl24** [comment]
Unless there are any objections, I will be using (Marionette.js)[https://marionettejs.com/] and (webpack)[https://webpack.js.org/] to help with the restructuring process.

**Comment by brylie** [comment]
That sounds fine by me. 

Please consider that Marionette may be a stepping stone towards a broader migration of this project's frontend code towards [WebComponent](https://www.webcomponents.org/)-based architecture. For a, slightly old, overview, see the following:

- [Web Components + Backbone: A Game-Changing Combination](https://www.webcomponents.org/community/presentations/webcomponents-plus-backbone-a-game-changing-combination-at-backbone-conf)

**Comment by JOO33** [comment]
Closing due to solution proposed by #827 . The JS related issues will be no longer relevant.
