### ISSUE TITLE
Refactor backend code to follow Django app structure

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#83]
Our backend code is all written as a single Django app. We agreed to re-structure the backend code, so that it is easier to understand and follows Django conventions.

# Goal
- Improve project maintainability by re-structuring code.
- Make it easy for new developers to get oriented to codebase, by following community conventions

# Resources
- [Django App Structure](https://www.codingforentrepreneurs.com/blog/django-app-structure/) (2016)
- [Recommended Django Project Layout](http://www.revsys.com/blog/2014/nov/21/recommended-django-project-layout/) (2014)
- [The Structure of a Django App](https://bradmontgomery.net/blog/the-structure-of-a-django-app/) (2008)

**Comment by AbhijithGanesh** [comment]
Is this issue relevant anymore? @brylie
