### ISSUE TITLE
RFC: remove features related to elected representatives

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#830]
CiviWiki has some features to provide information about elected representatives. The data are integrated from third party sources, such as ProPublica Congress API (and previously Sunlight API #99 ).

## Proposal
Remove code related to listing details of elected officials. Consider also (possibly in a separate RFC) removing code related to user locations (such as the Google Maps location prompt).

## Rationale
The third-party integration code has been one of the largest sources of development and maintenance effort, with brittle/broken results.

Only U.S. Congressional data are currently integrated, limiting the relevance of the feature to people around the world.

The "elected officials" feature may be out-of-scope for the unique value proposition of CiviWiki: namely promoting constructive discourse around political issues.

Removing the "elected officials" feature would also mean that people can register without providing their geographic location, improving privacy and anonymity.

## Related code
Remove the following code.

:warning: **Note** Remember to run the [`makemigrations` command](https://docs.djangoproject.com/en/3.2/ref/django-admin/#django-admin-makemigrations) after changing the project models.

### Accounts model
https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/account.py#L125-L127

https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/account.py#L330

https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/account.py#L333-L336

https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/account.py#L21-L22

### CiviWiki model(s)
https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/rationale.py#L10-L12

https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/representative.py

### Frontend templates/views
Remove the following

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/webapp/templates/partials/account/tabs/my_reps.html

**Comment by tberm** [comment]
Hi @brylie , I am working on removing location-related fields from user accounts ( #856 ) and can see that the representatives account data depends on the location data. OK if I take on this issue and remove everything related to representatives/elected officials as part of the same PR dealing with location fields?

**Comment by brylie** [comment]
@tberm yes. Let me know if I can be of assistance. I am available for pair-programming most days from 10AM - 4PM Eastern European Time.

**Comment by brylie** [comment]
@tberm I am available for the next hour in a [CiviWiki office hours hangout](https://codebuddies.org/hangout/qmdQirv9AhdNYkyGo) on Codebuddies.org.

**Comment by brylie** [comment]
@tberm I have updated the issue description with links to the relevant code.

**Comment by brylie** [comment]
Closed by #875
