### ISSUE TITLE
The url on the project page here on GitHub refers to a parked domain

### ISSUE THREAD

**Issue by InDieTasten** [CiviWiki/OpenCiviWiki#833]
The link(https://www.civiwiki.org/) in on the root page of this repository directs to a parked domain.

I suggest fixing the link, or removing it.

**Comment by InDieTasten** [comment]
Bump

**Comment by gorkemarslan** [comment]
Our new URL is [https://civi.wiki/](https://civi.wiki/).

This issue is solved by #1212.
