### ISSUE TITLE
Remove Celery dependency

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#845]
Celery may be used for fetching representative data and storing it to our cache table, since we are removing the "representatives" feature (to make this project better suited for an international community) we can likely remove the Celery dependency.

**Comment by pat-nel87** [comment]
I'd be interested in helping out with this, thank you

**Comment by brylie** [comment]
I believe we will still need Celery to send emails, so I'll close this issue as "wontfix"
