### ISSUE TITLE
Allow project to run without Postgres during development

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#846]
Our database actions are fairly generic CRUD. Since there isn't anything Postgres specific, the project should run with SQLite during development. While this may contradict conventional wisdom, the reason for allowing SQLite is to lower the barrier to entry for new developers.

**Comment by gorkemarslan** [comment]
@brylie, could you close this issue? Currently, SQLite is used during development.

**Comment by brylie** [comment]
Trying to add @jabrielcjones for their contribution to this task.
