### ISSUE TITLE
Remove "closed beta" functionality

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#849]
Let's treat CiviWiki as an active project that people might deploy to any number of servers for any purpose. To that end, we probably don't need the "closed beta" feature any longer.

This mainly involves removing the `beta_blocker` decorator from frontend views.

## Related code
Remove the following code.

:warning: **Note** Remember to run the [`makemigrations` command](https://docs.djangoproject.com/en/3.2/ref/django-admin/#django-admin-makemigrations) after changing the project models.

https://github.com/CiviWiki/OpenCiviWiki/search?p=2&q=beta

Here are a few places to be mindful of:

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/authentication/urls.py#L11

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/webapp/static/js/beta_register.js#L3

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/frontend_views/views.py#L14

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/frontend_views/views.py#L22-L23

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/frontend_views/urls.py#L6

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/frontend_views/urls.py#L17

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/authentication/authentication.py#L103-L104

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/authentication/authentication.py#L147-L148

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/webapp/templates/beta_register.html#L1

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/authentication/urls.py#L11

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/core/custom_decorators.py#L24

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/webapp/static/less/beta.less#L4

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/civiwiki/settings.py#L110

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/api/models/account.py#L124

**Comment by jithenms** [comment]
Would love to take on this task as one of my first open-source contributions. 

To get a better understanding, the beta_blocker decorator essentially prevents those without beta access from accessing features. Since you're launching CiviWiki as an active project, I understand why you wouldn't need the "closed beta" feature then.

I believe I would just need to remove the decorators from the functions so that everyone has the ability to access all features, correct? Let me know if there any other changes e.g. remove or add functions.

Otherwise, I'll get to work on it!

**Comment by brylie** [comment]
Thanks for offering to help! 😀

Yes, removing the decorator and setting should be sufficient.

Shall I assign you to the task?

**Comment by brylie** [comment]
Make sure to remove most/all code related to the closed beta and invitations:

https://github.com/CiviWiki/OpenCiviWiki/search?p=2&q=beta

Here are a few places to be mindful of:

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/authentication/urls.py#L11

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/webapp/static/js/beta_register.js#L3

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/frontend_views/views.py#L14

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/frontend_views/views.py#L22-L23

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/frontend_views/urls.py#L6

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/frontend_views/urls.py#L17

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/authentication/authentication.py#L103-L104

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/authentication/authentication.py#L147-L148

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/webapp/templates/beta_register.html#L1

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/authentication/urls.py#L11

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/core/custom_decorators.py#L24

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/webapp/static/less/beta.less#L4

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/civiwiki/settings.py#L110

https://github.com/CiviWiki/OpenCiviWiki/blob/ff74546f8fdc277c9bc5705f3df0c807c1130c62/project/api/models/account.py#L124

**Comment by jithenms** [comment]
Sure, I'll take it.

I believe I've completed the task and will be submitting a PR. Let me know if there are any errors or additional changes I need to make. Thanks!

**Comment by brylie** [comment]
@jithenshriyan I am available for the next hour in a [CiviWiki office hours hangout](https://codebuddies.org/hangout/qmdQirv9AhdNYkyGo) on Codebuddies.org.

**Comment by brylie** [comment]
@jithenshriyan please provide an update regarding your status with this issue. Let me know if there is any way I can help.

Edit: my bad. I had forgotten to review your pull request. Overall, great work! I made a couple of small change requests.

**Comment by 1337god** [comment]
Is there a working website demo?

**Comment by brylie** [comment]
Not currently. We will probably deploy a demo once we are closer to the 2.0 release.

**Comment by brylie** [comment]
@shashankks0987 this is another high priority task, which might be worth completing before #926

**Comment by shashankks0987** [comment]
@brylie Cool I can take this up before #926.
 I need some clarification on where the user should be redirected instead of '/beta' ?

**Comment by brylie** [comment]
Sure thing! Just redirect the user to the front page after logging in. Make sure the page indicates they are logged in, e.g. by displaying a log out button.

**Comment by shashankks0987** [comment]
@brylie How do you guys access the tables in the database usually? Using \d through psql in the docker container is not showing me any tables

**Comment by shashankks0987** [comment]
I'm a little confused with something here:
With this diff:
```
@@ -19,8 +19,6 @@ def base_view(request):
         return TemplateResponse(request, "static_templates/landing.html", {})
 
     a = Account.objects.get(user=request.user)
-    if not a.beta_access:
-        return HttpResponseRedirect("/beta")
     if not a.full_account:
         return HttpResponseRedirect("/setup")
     if "login_user_image" not in request.session.keys():
@@ -61,7 +59,6 @@ def base_view(request):
 
 
 @login_required
-@beta_blocker
 @full_account
 def user_profile(request, username=None):
     if not username:
```

Whenever I try to login I'm getting a google_api_key missing error:
![image](https://user-images.githubusercontent.com/47640763/122065593-b1ef1880-ce0f-11eb-95cd-72fad6d0e21a.png)

What am I missing here?

**Comment by brylie** [comment]
It looks like you might be bumping into an issue with Google Maps. Specifically, the `/setup` route/view has some code related to Google Maps. However, we want to remove Google Maps from our project: https://github.com/CiviWiki/OpenCiviWiki/issues/7

Would you consider removing the Google dependency before taking this "closed beta" issue? That would help out other developers too.

**Comment by brylie** [comment]
Closed by #934

**Comment by aniket-banyal** [comment]
There is still `beta_access` field in `Account` 

https://github.com/CiviWiki/OpenCiviWiki/blob/aa44eeb0e90944a229dc2fa35e83925c97e40e41/project/api/models/account.py#L123

`CLOSED_BETA` is still being used in these 2 places- 
https://github.com/CiviWiki/OpenCiviWiki/blob/aa44eeb0e90944a229dc2fa35e83925c97e40e41/project/accounts/views.py#L57-L58

https://github.com/CiviWiki/OpenCiviWiki/blob/aa44eeb0e90944a229dc2fa35e83925c97e40e41/project/accounts/authentication.py#L151-L152

Do you want these to be removed?

**Comment by brylie** [comment]
@dummy26 yes. Please open a specific PR for those changes. Good catch!

**Comment by aniket-banyal** [comment]
Sure!

**Comment by aniket-banyal** [comment]
Should I commit these migration files also?
![Screenshot (368)](https://user-images.githubusercontent.com/40134444/128218720-46bbb380-ec75-41f5-94d0-846bb2ca1947.png)

**Comment by brylie** [comment]
Yes, migrations get committed to the source control.
