### ISSUE TITLE
Clean up and update dependencies

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#851]
Make sure all dependencies are up to date (in addition to Django 3.2 LTS #848). Also, remove unneeded dependencies, such as

- django-notifications-hq (double-check how it is being used)
- channels
- asgi-redis
- coreapi
- requests (after disabling code that integrates 3rd party Propublica data)
- sunlight
- honcho
- sentry-sdk

**Comment by North15** [comment]
Hey @brylie, I would like to take on this task if it's still open and needs to be resolved. Thanks.

**Comment by soumallyadev07** [comment]
Hey @brylie  Would love to help with this!

**Comment by brylie** [comment]
Thanks, @soumallyadev07! Please let me know your progress and any hurdles in getting a development environment set up. I'll assign you to the issue, so we can indicate that it is in progress.

**Comment by brylie** [comment]
@soumallyadev07, would you mind saying how you found out about the CiviWiki project? I want to continue with community-building efforts, so any information about how to reach new contributors is welcome.

**Comment by brylie** [comment]
@soumallyadev07 would you be willing to start by upgrading the Django dependency to version 3.2 LTS? If so, we can start with issue #848

**Comment by soumallyadev07** [comment]
> Thanks, @soumallyadev07! Please let me know your progress and any hurdles in getting a development environment set up. I'll assign you to the issue, so we can indicate that it is in progress.

I'll set up my Dev Environment and get started!

**Comment by soumallyadev07** [comment]
> @soumallyadev07, would you mind saying how you found out about the CiviWiki project? I want to continue with community-building efforts, so any information about how to reach new contributors is welcome.

I actually found this project on [https://up-for-grabs.net/](https://up-for-grabs.net/)

**Comment by soumallyadev07** [comment]
> @soumallyadev07 would you be willing to start by upgrading the Django dependency to version 3.2 LTS? If so, we can start with issue #848

Sure! I'll upgrade and send a pull request for you to check

**Comment by soumallyadev07** [comment]
> @soumallyadev07 would you be willing to start by upgrading the Django dependency to version 3.2 LTS? If so, we can start with issue #848

Hey! I'm trying to set up my Dev Environment and upgrading the dependencies and I ran into 2 issues as of now, the psycopg2  is not getting install and throwing an error(Attached Screenshot).
<img src="https://i.ibb.co/4RP2yL9/Screenshot-421.png" alt="error" style="height: 100px; width:100px;"/>

2nd issue is coming from asgi-redis as it requires a lower version of channels while Django and some other libraries demand a higher one and there is no common version.

**Comment by mohas1203** [comment]
> > @soumallyadev07 would you be willing to start by upgrading the Django dependency to version 3.2 LTS? If so, we can start with issue #848
> 
> Hey! I'm trying to set up my Dev Environment and upgrading the dependencies and I ran into 2 issues as of now, the psycopg2 is not getting install and throwing an error(Attached Screenshot).
> ![error](https://camo.githubusercontent.com/be0e6c18f7624c781f24bf375747aab215a3bdb94b21952c5bbbb3df24ddf39b/68747470733a2f2f692e6962622e636f2f34525032794c392f53637265656e73686f742d3432312e706e67)
> 
> 2nd issue is coming from asgi-redis as it requires a lower version of channels while Django and some other libraries demand a higher one and there is no common version.

Instead of trying `pip install psycopg2` try `pip install psycopg2-binary`, I'm pretty sure its the same thing. Check out [this article](https://pysql.tecladocode.com/section05/lectures/04_psycopg2_vs_psycopg2-binary/) to learn about the differences.

**Comment by soumallyadev07** [comment]
> > > @soumallyadev07 would you be willing to start by upgrading the Django dependency to version 3.2 LTS? If so, we can start with issue #848
> > 
> > 
> > Hey! I'm trying to set up my Dev Environment and upgrading the dependencies and I ran into 2 issues as of now, the psycopg2 is not getting install and throwing an error(Attached Screenshot).
> > ![error](https://camo.githubusercontent.com/be0e6c18f7624c781f24bf375747aab215a3bdb94b21952c5bbbb3df24ddf39b/68747470733a2f2f692e6962622e636f2f34525032794c392f53637265656e73686f742d3432312e706e67)
> > 2nd issue is coming from asgi-redis as it requires a lower version of channels while Django and some other libraries demand a higher one and there is no common version.
> 
> Instead of trying `pip install psycopg2` try `pip install psycopg2-binary`, I'm pretty sure its the same thing. Check out [this article](https://pysql.tecladocode.com/section05/lectures/04_psycopg2_vs_psycopg2-binary/) to learn about the differences.

Thanks! I installed psycopg2-binary but I still don't seem to understand the error that is being generated here.

**Comment by mohas1203** [comment]
@soumallyadev07 To install psycopg2 there are a lot of dependencies that you need for it whereas psycopg2-binary usually just works after being downloaded. You can also check out this [discussion ](https://github.com/psycopg/psycopg2/issues/674) where the address some of the problems

**Comment by fardeenes7** [comment]
Can I get a chance to work on the issue? I would really love to

**Comment by brylie** [comment]
In reqrirements.txt, change the following line

```
psycopg2==2.8.6
```

to

```
psycopg2-binary==2.8.6
```

Then re-run the build process.

**Comment by soumallyadev07** [comment]
> In reqrirements.txt, change the following line
> 
> ```
> psycopg2==2.8.6
> ```
> 
> to
> 
> ```
> psycopg2-binary==2.8.6
> ```
> 
> Then re-run the build process.

I've changed and installed all the requirements and then tried to run - 
```
python manage.py runserver
``` 
in the "project" folder but I'm getting the **ModuleNotFoundError: No module named 'celery'** error even though celery is installed using pip.
![Screenshot (424)](https://user-images.githubusercontent.com/55331884/119081820-73d22500-ba1a-11eb-83cb-002ce4b554a1.png)

**Comment by brylie** [comment]
Edit: we will keep the Celery dependency, as it is needed for sending emails.

**Comment by brylie** [comment]
Please notice the following part of the issue description:

> Also, remove unneeded dependencies, such as

    django-notifications-hq (double-check how it is being used)
    channels
    celery
    asgi-redis
    coreapi
    requests (after disabling code that integrates 3rd party data)
    sunlight
    honcho
    sentry-sdk

**Comment by fardeenes7** [comment]
hey @brylie  should I give it a try?

**Comment by brylie** [comment]
@fardeenes7 it is a bit confusing for multiple people to work on the same issue. Would you consider trying an issue that is not assigned in our 2.0 backlog?

https://github.com/CiviWiki/OpenCiviWiki/milestone/5

**Comment by brylie** [comment]
@North15 would you be interested in working on issue #848? That is a really important issue for keeping us up to date with Django LTS.

**Comment by North15** [comment]
@brylie Yes, I can start working on this issue.

**Comment by brylie** [comment]
@North15 ok, let's carry the conversation over to issue #848
