### ISSUE TITLE
Use django-taggit for Civi keyword hashtags

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#854]
We currently use a `Hashtag` model to categorize Civis. Switch to using django-taggit for keyword tagging. Use the word "keyword" instead of "hashtag" throughout the UI and data model.

**Comment by loukikstudent** [comment]
Hi, new to contributing but would love to help out, if i can do it

**Comment by brylie** [comment]
Thanks, @loukikstudent! I have assigned you to the issue.

Out of interest, how did you find out about CiviWiki?

**Comment by loukikstudent** [comment]
Thank you for the assignment @brylie .
I was actually just browsing GitHub explore to see if there are any cool repos that i could utilize in my projects, then came across this repo's issues tagged with "good first issue" and thought to myself i might as well try and give back to the community that has given me so much and also i contributed before the whole hacktoberfest reeks havoc

**Comment by brylie** [comment]
Thanks for the info @loukikstudent 

Please let me know if you have any difficulties with or need advice regarding to this issue :-)

**Comment by yutytuty** [comment]
Hi, also new to contributing and was wondering if I could help with this issue? This is the first project I am contributing to so was wondering if I can ask for help here as well.
Thank you in advance!

**Comment by loukikstudent** [comment]
Hi, i went through the code, i saw the Hashtag model, you want me to modify it so that it uses django-taggit and replace hashtag with keyword everywhere. I shouldnt be changing the Hashtag model name right?

**Comment by brylie** [comment]
Correct. In effect, we can remove the `Hashtag` model and use a `TaggableManager` field on any model that (ForeignKey) references `Hashtag`.

E.g.

```py
class Civi(models.Model):
    # ... fields here
   
    # Use TagabbleManager for any model with keyword tags
    tags = TaggableManager()
```

Change the following fields to use `TagabbleManager` as in the example above:
https://github.com/CiviWiki/OpenCiviWiki/blob/b5802ad07ca3b42c6a77b383b6c450841fdff916/project/api/models/thread.py#L94

https://github.com/CiviWiki/OpenCiviWiki/blob/b5802ad07ca3b42c6a77b383b6c450841fdff916/project/api/models/account.py#L113

**Comment by loukikstudent** [comment]
I have made the changes to satisfy the conditions of this issue, the problem is that i am trying to test it with docker deploy but i keep getting error in civiwiki-backend.
````
standard_init_linux.go:219: exec user process caused: no such file or directory

standard_init_linux.go:219: exec user process caused: no such file or directory

standard_init_linux.go:219: exec user process caused: no such file or directory

standard_init_linux.go:219: exec user process caused: no such file or directory

standard_init_linux.go:219: exec user process caused: no such file or directory

standard_init_linux.go:219: exec user process caused: no such file or directory

standard_init_linux.go:219: exec user process caused: no such file or directory

standard_init_linux.go:219: exec user process caused: no such file or directory

standard_init_linux.go:219: exec user process caused: no such file or directory

standard_init_linux.go:219: exec user process caused: no such file or directory
````

I have tried using EOL conversion but had no success. @brylie kindly look into the PR and let me know if any other changes are required and also could you help me with test of this code in docker as well.
Thank you

**Comment by brylie** [comment]
@loukikstudent try running CiviWiki without Docker. It should work reasonably well with just Python virtual environment. Try on a fresh version of the develop branch, as we have simplified the dependencies substantially today. Then, apply your changes against a fresh branch, so you don't have to wrestle with Git too much.

**Comment by loukikstudent** [comment]
Hi @brylie,
 I have migrated the changes also added it under "INSTALLED_APPS" as well as updated requirements.txt.

The issue is in api/accounts.py -> Accounts model the field ai_interests, i cannot add TaggleManager() because it through an error during migrations
ValueError: You can't have two TaggableManagers with the same through model.
Because of this i cannot completely remove the Hashtag model.

PR #900

**Comment by brylie** [comment]
Feel free to remove the `ai_interests` field, as it is not needed.

**Comment by loukikstudent** [comment]
The changes have been made.
@brylie hi sorry, i was really confused about the PRs so i issues a new PR with all the changes PR #900.
