### ISSUE TITLE
Remove location-related fields from user Account (profiles)

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#856]
We currently request that people provide their physical address and geographic coordinates. This PII may be unnecessary and is somewhat risky for us to collect as a small project.

Remove location-related data/fields from user accounts. 

NOTE: we can add this feature at a later point when we know it is a core benefit. Right now we are deprecating code related to government representatives, so user locations are irrelevant.

## Related code
Remove the following fields from the `Account` model

https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/account.py#L113-L123

:warning: **Note** Remember to run the [`makemigrations` command](https://docs.djangoproject.com/en/3.2/ref/django-admin/#django-admin-makemigrations) after changing the `Account` model fields.

Also remove location-related properties from the `Account` model:
https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/account.py#L154-L181

### Model manager
Make sure we no longer use the location field(s) in other places, such as the model manager:
https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/account.py#L39

https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/account.py#L76

### accounts post-save hook
https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/account.py#L327-L329

https://github.com/CiviWiki/OpenCiviWiki/blob/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/api/models/account.py#L332

**Comment by kweku-45** [comment]
Finding it difficult to locate User model. Which folder is it in?

**Comment by tberm** [comment]
Hi there, I'm new to open source and would like to take this on as a first issue!

It seems pretty straightforward so I'll get started on it, but let me know if you have any pointers.

**Comment by brylie** [comment]
Thanks @tberm! Let me know if I can be of assistance with pair programming.

**Comment by brylie** [comment]
@tberm I am available for the next hour in a [CiviWiki office hours hangout](https://codebuddies.org/hangout/qmdQirv9AhdNYkyGo) on Codebuddies.org.

**Comment by brylie** [comment]
@tberm please be aware of issue #855 as it relates to the Accounts app.

**Comment by brylie** [comment]
@tberm I have updated the issue description to include the specific lines of code to remove from the project. Remember to run `makemigrations` command after changing the `Account` model.

**Comment by tberm** [comment]
Thanks for the help in the description @brylie. I've actually removed a bit more code than what you've linked above -- hopefully I haven't gone too far! I've just submitted my changes in PR #875 so you can take a look. That covers both this issue and #830.

A couple of questions:
- Are the tests currently in a working state? I've tried running them following [readmes/testing.md](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/readmes/testing.md) but getting errors about Django settings not being configured for the aloe tests and an error in test_propublica.py for `manage.py test`.
- Am I right in thinking that the `Vote` model represents a vote cast by a representative for a bill? If so, does it need to be removed as well if we are removing representatives?

**Comment by brylie** [comment]
Closed by #875
