### ISSUE TITLE
new: Add typing to functions and Var

### ISSUE THREAD

**Issue by freelancing-solutions** [CiviWiki/OpenCiviWiki#868]
# Typing Highly Needed

- [ ]  Refactor  the code base module by module to start using typing 
- [ ]  Add Test Cases to Support Typing for each module.

Suggestions the best place to start could be 
- [Front End Views](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/frontend_views/views.py)

**Comment by Floyd-Droid** [comment]
I'm interested in this issue. I could begin by annotating the functions of the frontend views, unless there is a better place to start.

Also, it seems [django-stubs](https://github.com/typeddjango/django-stubs) would be helpful to integrate.

**Comment by brylie** [comment]
Closing as `wontfix`
