### ISSUE TITLE
Restructure CiviWiki organization to facilitate community stewardship

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#885]
Currently, the CiviWiki organization has three members:

- @mdwest (Owner)
- @JOO33 (Owner)
- @brylie (Member)

While we are trying to recognize all contributors in our README, it may be more beneficial to invite contributors to join our GitHub organization.

As a first step towards greater community involvement in the CiviWiki project, let's:

1. create one or more groups in the CiviWiki organization for contributors (e.g. Design, Development, Documentation)
2. invite all current and previous contributors to join the CiviWiki organization by adding them to the relevant team

## List of contributors to invite
In the same order as our README:

- @lisbonjoker
- @TomaszKolek 
- @Unit111 
- @Sv3nman 
- @ryan-barrett 
- @WCollins3 
- @delta-plus 
- @GokuMizuno 
- @dborstelmann
- @DCalliet 
- @tractaylor 
- @tomjohnhall 
- @jstrang 
- @danielgrijalva 
- @g1stavo 
- @pscheid2 
- @terrencetuy 
- @JonanOribe 
- @shaunak-gupta 
- @dlarner3194 
- @darcymeyer 
- @Jazriel 
- @therohitramesh 
- @richifuentes
- @alecxvs
- @Shreyas4991
- @SunflowerPKU
- @jgbmattos
- @torabshaikh 
- @CaioSR 
- @umr55766 
- @JDRanpariya 
- @Di-ref 
- @BrianPainter 
- @AnkanDas22
- @gteti 
- @harsha0609 
- @obafemiolorungbon 
- @tberm 
- @PyDrummer

**Comment by brylie** [comment]
@mdwest or @JOO33, would you mind adding me as an Owner in the CiviWiki organization so I can work on the above-mentioned changes?

**Comment by lisbonjoker** [comment]
We could use either Matrix or a self-hosted RocketChat

**Comment by brylie** [comment]
Ping @mdwest and @JOO33

**Comment by AbhijithGanesh** [comment]
I would like to be a part time steward if there is a need of it.

**Comment by brylie** [comment]
@mdwest or @JOO33, would you mind adding me as an Owner on the [CiviWiki organization members page](https://github.com/orgs/CiviWiki/people)?

![image](https://user-images.githubusercontent.com/17307/134664910-68fc9f19-707e-4fa4-9e19-72f127ccd1e5.png)

**Comment by gteti** [comment]
Thank you 😃

**Comment by brylie** [comment]
I propose we create a new organization and move the `OpenCiviWiki` repository to that organization to have complete stewardship control.
