### ISSUE TITLE
Create reset password view under the accounts app.

### ISSUE THREAD

**Issue by a7madnassar** [CiviWiki/OpenCiviWiki#908]
Currently, when the user wants to reset the password, they go to a Django admin page, which has a different look.  Newly implemented registration and login views have been created under the '/accounts/' path. This task is to replace the current reset password page with a page that looks like the registration and login pages.

**Comment by a7madnassar** [comment]
@brylie can you please assign this task to me. I created it to complete the work done on the user registration/login section. This task is to migrate the current reset password page into the new '/accounts/' path.

**Comment by brylie** [comment]
Thanks @a7madnassar!

**Comment by a7madnassar** [comment]
@brylie I have the reset password functionality working. But I have to wait for the Celery pull request I just submitted to be accepted. Once you merge my last Celery removal changes. I will submit another pull request for the password reset flow.

Thanks

**Comment by brylie** [comment]
@a7madnassar I just merged the Celery PR :-)

**Comment by a7madnassar** [comment]
@brylie cool, I will submit another PR for this soon. Thanks
