### ISSUE TITLE
Ensure local-setup documentation is still valid

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#909]
We have a [local-setup document](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/docs/contributing/local-setup.md) to help new contributors run CiviWiki on their local computers. With recent changes, some of the details in local-setup.md may be irrelevant.

Make sure we update the local-setup.md with correct details for getting started with CiviWiki development.

**Comment by Floyd-Droid** [comment]
Hi @brylie, I'd like to work on this issue.

**Comment by brylie** [comment]
Thanks @Floyd-Droid! I'll assign you.

**Comment by Floyd-Droid** [comment]
Hello, @brylie. I'm having trouble getting an account set up. Here is my process:

(1) Create/activate a virtual environment and install dependencies
(2) python manage.py migrate
(3) install categories.json fixture
(4) collect static files
(5) create superuser
(6) run the server

When I go to register (same info as superuser), I get two errors:
(1) "Sorry, this username already exists"
(2) "An account exists with this email address"

This suggests the account already exists, but when I attempt to log in, I get a "Not found" error.

If I try to register another user with different name and email, I have to click the register button twice before getting the same 2 messages above. When I try to log in with the new user info, I'm taken to the /beta page. Any help will be greatly appreciated.

**Comment by brylie** [comment]
> When I go to register (same info as superuser), I get two errors:
> (1) "Sorry, this username already exists"
> (2) "An account exists with this email address"

Go to log in, rather than register. The `createsuperuser` command has already created an account without needing to register through the UI.

**Comment by Floyd-Droid** [comment]
I still get the 'Not found' error. After some searching, it seems that the createsuperuser command creates an accounts.models.User instance. However, in accounts/authentication.py, line 71:

https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/accounts/authentication.py#L69-L76

It attempts to grab a corresponding Account instance, but there are none in the database.

**Comment by brylie** [comment]
Ok, we probably need to configure the default user model. I created issue #917 to make sure the default user model is used.

I will create a separate issue to track the resolution of this registration/login bug you describe.
