### ISSUE TITLE
Create user profile template

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#914]
When migrating the old frontend templates to Django, we noticed the user profile was not rendering any content. Rather than weed through the proclaimed "horrendous code" that was responsible for rendering the BackBone view, let's just write a _simple_ user profile template from scratch. 

https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/webapp/static/js/account.js#L32-L33

## Task
- determine what fields are available on the user profile
- sketch a basic user profile page using pencil and paper or a drawing app
- discuss the proposed sketch
- implement the sketch using conventional Django elements like Form and class-based views

**Comment by praneethratna** [comment]
I'm a newcomer and would like to contribute in solving this issue, Could you please help me out?

**Comment by devRawnie** [comment]
[Here](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/accounts/models.py#L5-L11), I couldn't find any fields specified in the User model. Is there some other model, defined elsewhere?

**Comment by brylie** [comment]
We have an `Account` model that is basically the equivalent of a user profile:

https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/api/models/account.py#L105

I propose we 
1. move the `Account` model source code into the `accounts` app
2. rename the `Account` model to `Profile`
3. create a FormView for the `Profile` model with route
4. change front-end links to use the new 'ProfileForm` view/route

**Comment by brylie** [comment]
I opened an issue to move all accounts related code to the accounts app and rename the `Account` model to `Profile`: #926

**Comment by brylie** [comment]
This task can focus on rendering the profile edit form and should be considered a child task of #926

**Comment by wassafshahzad** [comment]
@brylie  I worked on settings forms issue and this looks similar to that so could you assign it to  me?
secondly should we also have a PR  template  ?  I can create one if you could create a ticket for it an assign it to me

**Comment by brylie** [comment]
@wassafshahzad thanks for the help :-) I've assigned you to the issue.

**Comment by wassafshahzad** [comment]
> @wassafshahzad thanks for the help :-) I've assigned you to the issue.

No problem always happy to help

**Comment by wassafshahzad** [comment]
@brylie would you kindly explain how will this be different from the settings form?
I could make it so that this form is readonly and clicking an edit button will redirect you to settings form.

**Comment by brylie** [comment]
@wassafshahzad good point. Let's perhaps deprecate the "user profile" form/template in favor of the settings page. I.e. just link directly to the settings page and remove any code/mention of "profile" perhaps?

**Comment by wassafshahzad** [comment]
So should i change the link from profileView to settingView ?
if possible could you explain your idea ? 
Thank you

**Comment by brylie** [comment]
@wassafshahzad yes. Linking to `settingView` is fine for now.

**Comment by wassafshahzad** [comment]
Put up Pr for this issue.

**Comment by brylie** [comment]
Looks good. We'll merge the PR once the review comments are resolved :smiley:

**Comment by wassafshahzad** [comment]
Sorry I didn't add the tests yet.
Are there any more issues of priority?
