### ISSUE TITLE
Create settings view/tempate

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#915]
When migrating the old frontend templates to Django, we noticed the settings view was not rendering any content. Rather than weed through the Backbone.js code that was responsible for rendering the view, let's just write a _simple_ user profile template from scratch. 

## Task
- determine what fields are available on the settings page
- sketch a basic settings page using pencil and paper or a drawing app
- discuss the proposed sketch
- implement the sketch using conventional Django elements like Form and class-based views

**Comment by max1204** [comment]
@brylie issue #889 PR was merged. And there you mentioned two tickets This issue and one other issue. So I'm working on this. 

The #889  do we close it or add something to it?

**Comment by manuneerav** [comment]
@brylie I am assuming that in this profile settings page you need fields mostly related to user personal data i.e first name, last name, location etc.  Please specify if there is anything else that you need.

**Comment by brylie** [comment]
@manuneerav yes, let's just focus on the profile fields now until we find any other settings that need a form.

**Comment by manuneerav** [comment]
![IMG20210619142645.jpg](https://user-images.githubusercontent.com/59529237/122637228-190c1600-d10b-11eb-8e04-91142e91c8fb.jpg)

**Comment by manuneerav** [comment]
Have a look at it

**Comment by brylie** [comment]
Looks great. Let's start with the basic text fields and handle the profile image in a separate task. I like the layout.

**Comment by brylie** [comment]
Make sure both buttons have the same text. I.e "save changes"  is a good text. It might be simple enough to have only one button that submits the form.

**Comment by ghost** [comment]
Hi, I'm pretty new at this and this is the first project I try to contribute to. Is there a way I can contribute? Here or on another Issue?

**Comment by brylie** [comment]
Thanks @yanijun! Perhaps you can work with @manuneerav on this task to move it along? @manuneerav has already provided a sketch of the desired form fields so now it is a good time to build the form using Django code

**Comment by mullera3** [comment]
Hello I'm looking to contribute to any open source project. This is going to be my first time contributing to an open source is there anything I can do to help? @brylie

**Comment by brylie** [comment]
@mullera3 would you like to help test out the developer documentation? We want to make sure it is easy for new developers to get started with CiviWiki, so the documentation is really important.

**Comment by ghost** [comment]
hey I'm kinda lost in all of this is there an group chat (discord/slack) for help and questions?

**Comment by brylie** [comment]
@yanijun the best option right now is to discuss issues on GitHub, which is nearly real-time but also keeps conversations contained in the context of an issue.

What specific issue(s) are you encountering with development?

**Comment by ghost** [comment]
ok so is docker really necessary for me to work on the project?  And seen there is no code yet for the template should I open a fork for it or how should I proceed once I have some code written that I'd like to be reviewed?

**Comment by brylie** [comment]
Docker should be optional. If you have difficulty running the project with just `python manage.py runserver` please let me know, so I can simplify the development process.

Yes, we need to build this template from scratch. Start with a basic sketch then use the Django Forms and templates to build the form.

**Comment by wassafshahzad** [comment]
Is this issue still open  ?

**Comment by ghost** [comment]
Hi, yes. I am out of my depth here, I think I kinda jumped the gun here trying to get this done. I still need some studying. 
Hope I will be able to return and help in the future.

**Comment by wassafshahzad** [comment]
> Hi, yes. I am out of my depth here, I think I kinda jumped the gun here trying to get this done. I still need some studying. 
> Hope I will be able to return and help in the future. 

Ok I'll start going through the setting view and drawing the sketch

**Comment by vishalda** [comment]
Hey @brylie, I would like to work on this issue with @manuneerav

**Comment by brylie** [comment]
@VDA-001, thanks! I'll co-assign you to the task.

**Comment by codingfarhan** [comment]
Hey, new to open source here. Have worked on a few Django projects previously. Willing to contribute code. Anyway I can help on this (or any other) issue?

**Comment by wassafshahzad** [comment]
@brylie  I have created a pull request for this issue please to review

**Comment by brylie** [comment]
Thanks @wassafshahzad. I have just reviewed the PR after a week's absence from GitHub. Please address the lint issues mentioned by @pep8speaks and we can merge the PR

**Comment by Adyyousf** [comment]
hey I'm finding issue to solve and start contributing to opensource. Is there anything I can do to help? I know Django and have worked on it.

**Comment by wassafshahzad** [comment]
> hey I'm finding issue to solve and start contributing to opensource. Is there anything I can do to help? I know Django and have worked on it.

Hi, you can go to the issue tab to view and pick an issue you would like to work on.

**Comment by brylie** [comment]
@Adyyousf, we have several issues with the "[good first issue](https://github.com/CiviWiki/OpenCiviWiki/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)" label.

**Comment by wassafshahzad** [comment]
We should close this issue @brylie
