### ISSUE TITLE
Configure default user model

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#917]
With recent work on a custom user model, we may have forgotten to configure Django to use the custom user model as default when creating new users.

Make sure our `User` model is configured as the project default (in the base settings). 
https://github.com/CiviWiki/OpenCiviWiki/blob/374381b6e4b9b556580157f33fbd8c67204c1b36/project/accounts/models.py#L5-L11

**Comment by shashankks0987** [comment]
@brylie I'd like to start contributing to this project and want to start off with this issue. Could you elaborate on this: User model is configured as the project default

**Comment by shashankks0987** [comment]
Also nothing past the login page is developed yet right? Because after my local setup it sends me to /beta

**Comment by shashankks0987** [comment]
Isn't this what you're looking for 
```
# Custom User model
AUTH_USER_MODEL = 'accounts.User'
``` 
It is already present in settings.py @brylie

**Comment by brylie** [comment]
Thanks for the clarification @shashankks0987. I'll assign you to this issue and close it since you did the research and found there wasn't any code needed. In any case, this should count as a code contribution even though you didn't need to change anything.

So, the main task becomes to make sure we are using the correct user model in our login/register views #918 Would you consider contributing to issue #918 @shashankks0987?

**Comment by shashankks0987** [comment]
Alright, you can close this. #918 is already implemented I guess, Is there anything I can take up?

**Comment by brylie** [comment]
@shashankks0987 try to reproduce/fix the bug report in #918. I think the register and login views are using the wrong user model. I have been able to reproduce the bug.

**Comment by brylie** [comment]
@shashankks0987 would you be interested in refactoring our accounts code by moving from the `api` directory into the `accounts` app and renaming the `Account` model to `Profile`? #926
