### ISSUE TITLE
Discuss possibilities for community chat channel

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#921]
As our community grows, we want to support collaboration by recommending a primary chat channel/service. Our current recommended community chat channel is Matrix/Riot.im, which has recently been re-branded as [Element](https://element.io/) and undergone usability improvements.

As there aren't a lot of participants in the Riot.im chat, it might be a good opportunity to re-assess which chat service fits the community needs the best. However, it might also be the case that we simply need to be more actively present on the existing Element channel to encourage community adoption.

## Background
We originally set up the channel on Riot.im with several complementary aims:

- offer a channel for the CiviWiki community to congregate and collaborate
- participate in a democratic, federated, and open-source chat community
- co-mingle with other communities and open-source projects

In the subsequent years, the CiviWiki project has gone dormant, so there haven't been many active community members in the Riot.im channel. Now that we are rebooting the project, it might be opportune to re-appraise our community chat recommendations while stepping up our involvement in whichever discussion platform we use.

**Comment by brylie** [comment]
We originally set up the channel on Riot.im with several complementary aims:

- offer a channel for the CiviWiki community to congregate and collaborate
- participate in a democratic, federated, and open-source chat community
- co-mingle with other communities and open-source projects

In the subsequent years, the CiviWiki project has gone dormant, so there haven't been many active community members in the Riot.im channel. Now that we are rebooting the project, it might be opportune to re-appraise our community chat recommendations while stepping up our involvement in whichever discussion platform we use.

**Comment by pscheid2** [comment]
I think the most important piece is increasing our participation in whatever chat client we choose.

I'm most familiar with Discord or Slack, but am fine with other options if they don't create any barriers to collaboration. @brylie as the most active project member, what are your chat preferences?

**Comment by brylie** [comment]
I don't have a super-strong opinion on the matter, but tend to prefer chat networks that are federated and open-source when possible. That said, I have profiles on Discord, Element, Libera IRC, Signal, Slack, Telegram, and WhatsApp, which is becoming a bit mind-boggling.

Perhaps we can re-assess the user experience situation with Element and then decide whether we want to move to another network?

**Comment by pscheid2** [comment]
> Perhaps we can re-assess the user experience situation with Element and then decide whether we want to move to another network?

Sounds good to me! Let's use the existing chat for a while and reconsider if we start see downsides.

**Comment by brylie** [comment]
I'm also thinking that most of our current communications needs might be served by an asynchronous tool, such as [Discourse](https://www.discourse.org/). Discourse is open-source, has a blend of features that make it suited for near-real-time chat and asynchronous community engagement, and offers free hosting for open-source projects.

**Comment by brylie** [comment]
GitHub is also good for asynchronous and near-real-time discussions. There are so many options :-)

**Comment by pscheid2** [comment]
Github is good for asynchronous communication, but I think we're missing a space for brainstorming and developer questions/technical help which in my opinion github is not great for.

**Comment by brylie** [comment]
By the way, I have been looking into setting up a [WorkAdventure](https://workadventu.re/) virtual office for the CiviWiki organization. E.g. we could call it our CiviWiki virtual office and have meetings and such, which might feel a bit more welcoming than a text channel.

What are your thoughts and experiences with virtual collaboration environments like WorkAdventure or Gather.town?

**Comment by pscheid2** [comment]
I don't have any experience with either but I have heard more praise for gather.town

**Comment by AbhijithGanesh** [comment]
Do we have a discord server right now?  I would say Discord/Slack would be more suitable for our community to work and we might be able to use bots for moderation and other tasks pertinent to this job.

**Comment by brylie** [comment]
We don't have a Discord/Slack. What would be some of the benefits and, importantly, drawbacks of Discord and Slack?

**Comment by AbhijithGanesh** [comment]
for discord: We can implement bots and extreme customization making the community insanely active . It will also give us the benefits of interaction. It will speed our project dev. 
Slack benefits the same but I am personally inclined towards discord for its accessibility and availability.

**Comment by gorkemarslan** [comment]
Any update? The project is taking attention. :) Seemingly, it is getting harder to get in contact. We need to move our discussions to the new chat channel ASAP.

**Comment by brylie** [comment]
@gorkemarslan, what are the difficulties you face when contacting project contributors? We currently have GitHub issues and a discussion forum. The conversations on GitHub, such as this, seem to be fairly active.

**Comment by AbhijithGanesh** [comment]
@brylie I am of the opinion that GitHub is active but it doesn't work as fast as discord/slack. Can we give the platforms a chance?

**Comment by brylie** [comment]
I don't believe the project/community is active enough to introduce, or transition to, a new tool for real-time chat. Also, introducing a Slack or Discord channel will introduce another "ownership" dynamic, where we are currently having difficulty transitioning this GitHub organization to community governance (#885).

We have used Slack in the past and [currently use Matrix](https://riot.im/app/#/room/#CiviWiki:matrix.org). 

I propose we stick with the existing Matrix chat channel that has been established for a few years. I am removing the GitHub bot from our Matrix channel and will commit to being more active there as well.

**Comment by AbhijithGanesh** [comment]
Points well noted brylie; We understand your perspective.

**Comment by brylie** [comment]
Thanks for your understanding. Please accept my apologies for the delay in responding to our chatroom.
