### ISSUE TITLE
sqlite3 doesn't seem to support some db operations we use in our app

### ISSUE THREAD

**Issue by pscheid2** [CiviWiki/OpenCiviWiki#939]
When running the app with sqlite in development on the /settings page, I'm getting the following error when trying to make changes to a users first and last name.

It seems like sqlite might be incompatible with some db operations we use in our app.

![image](https://user-images.githubusercontent.com/6983738/122582256-f0f6b700-d025-11eb-9bd1-cd0c639d3fd3.png)

cc: @brylie

**Comment by brylie** [comment]
@pscheid2 can you share the full stack trace?

I believe this may be a relatively narrow case, and possibly resulting from custom SQL. In any case, we should aim to simplify all of our DB usage to what can be achieved with sqlite, until we know there is a specific feature of another DB that would be useful to the project.

**Comment by brylie** [comment]
What happens if you remove this, unused, line?

https://github.com/CiviWiki/OpenCiviWiki/blob/2dec5e9b1ec8caa4d9c8f256505334888b97fd7c/project/frontend_views/views.py#L191

**Comment by brylie** [comment]
Based on a search, this issue may also be related to our use of `.distinct`:

https://github.com/CiviWiki/OpenCiviWiki/search?q=distinct

**Comment by pscheid2** [comment]
Full stack trace

```
Traceback (most recent call last):
  File "/Users/pscheid/projects/CiviWikiFork/venv/lib/python3.7/site-packag=
es/django/core/handlers/exception.py", line 47, in inner
    response =3D get_response(request)
  File "/Users/pscheid/projects/CiviWikiFork/venv/lib/python3.7/site-packag=
es/django/core/handlers/base.py", line 181, in _get_response
    response =3D wrapped_callback(request, *callback_args, **callback_kwarg=
s)
  File "/Users/pscheid/projects/CiviWikiFork/project/api/read.py", line 61,=
 in get_profile
    for thread_id in solution_threads:
  File "/Users/pscheid/projects/CiviWikiFork/venv/lib/python3.7/site-packag=
es/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/Users/pscheid/projects/CiviWikiFork/venv/lib/python3.7/site-packag=
es/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache =3D list(self._iterable_class(self))
  File "/Users/pscheid/projects/CiviWikiFork/venv/lib/python3.7/site-packag=
es/django/db/models/query.py", line 171, in __iter__
    for row in compiler.results_iter(chunked_fetch=3Dself.chunked_fetch, ch=
unk_size=3Dself.chunk_size):
  File "/Users/pscheid/projects/CiviWikiFork/venv/lib/python3.7/site-packag=
es/django/db/models/sql/compiler.py", line 1130, in results_iter
    results =3D self.execute_sql(MULTI, chunked_fetch=3Dchunked_fetch, chun=
k_size=3Dchunk_size)
  File "/Users/pscheid/projects/CiviWikiFork/venv/lib/python3.7/site-packag=
es/django/db/models/sql/compiler.py", line 1162, in execute_sql
    sql, params =3D self.as_sql()
  File "/Users/pscheid/projects/CiviWikiFork/venv/lib/python3.7/site-packag=
es/django/db/models/sql/compiler.py", line 536, in as_sql
    distinct_params,
  File "/Users/pscheid/projects/CiviWikiFork/venv/lib/python3.7/site-packag=
es/django/db/backends/base/operations.py", line 176, in distinct_sql
    raise NotSupportedError('DISTINCT ON fields is not supported by this da=
tabase backend')

Exception Type: NotSupportedError at /api/account_profile/paultest/
Exception Value: DISTINCT ON fields is not supported by this database backe=
nd
```

**Comment by dpspcghst** [comment]
> Based on a search, this issue may also be related to our use of `.distinct`:
> 
> https://github.com/CiviWiki/OpenCiviWiki/search?q=distinct

I watched @jabrielcjones try to fix this issue yesterday. I sent him this link and it seemed to help:

https://stackoverflow.com/questions/54249017/distinct-on-fields-is-not-supported-by-this-database-backend

`distinct('field_name')` is not supported in MySQL. It only supports `distinct()`.
`distinct('field_name')` will only work on PostgresSQL.

**Comment by jabrielcjones** [comment]
After @deepspaceghost and I implemented his suggestion, the error went away. We're now regression testing the fix.

**Comment by brylie** [comment]
@jabrielcjones would you mind opening a pull request with the solution you found?

**Comment by jabrielcjones** [comment]
@brylie Done. https://github.com/CiviWiki/OpenCiviWiki/pull/951
