### ISSUE TITLE
Update documentation to remove references to congress.json

### ISSUE THREAD

**Issue by FatalTrip** [CiviWiki/OpenCiviWiki#958]
I spent a while looking for the initial data congress.json that the contributing.md document says to loaddata in. It turns out the .json was not in the data directory so I had to skip that step. What should I do? submit a pull request with that step taken out?

**Comment by brylie** [comment]
We have recently removed support for the "elected officials", which were based on the U.S. electoral system. The documentation was not updated to reflect that the data are no longer needed. We'll update the docs ASAP :-)

**Comment by aniket-banyal** [comment]
May I work on it? It would be a good first issue for me!

**Comment by FatalTrip** [comment]
> May I work on it? It would be a good first issue for me!

Feel free too! Anytime there is an issue you can work on it and contribute without asking. :)

**Comment by aniket-banyal** [comment]
Am I just supposed to remove this from CONTRIBUTING.md? 
```py
python manage.py loaddata data/congress.json
```

**Comment by FatalTrip** [comment]
> Am I just supposed to remove this from CONTRIBUTING.md?
> 
> ```python
> python manage.py loaddata data/congress.json
> ```

I am pretty new too, but I think that's all we have to do to fix this issue :)

**Comment by aniket-banyal** [comment]
Thank u @FatalTrip! I will begin working on it.
