### ISSUE TITLE
Don't use general Exception class to catch exceptions 

### ISSUE THREAD

**Issue by aniket-banyal** [CiviWiki/OpenCiviWiki#962]
`except Exception as e` is usually not considered a good practice.

https://github.com/CiviWiki/OpenCiviWiki/blob/aa44eeb0e90944a229dc2fa35e83925c97e40e41/project/accounts/authentication.py#L165-L166

https://github.com/CiviWiki/OpenCiviWiki/blob/aa44eeb0e90944a229dc2fa35e83925c97e40e41/project/accounts/authentication.py#L233-L234

Maybe these should be catching some specific Exceptions

**Comment by calicomills** [comment]
@dummy26  
Can I take this up?

**Comment by aniket-banyal** [comment]
Sure!

**Comment by brylie** [comment]
@calicomills, thanks for your help. I've assigned you to the issue.

**Comment by calicomills** [comment]
@brylie @dummy26 I think many actual errors can go hidden using the general` Exception` class, I think we should have separate custom `Exception` classes and `raise` custom exceptions when we encounter something wrong, and consequently ditch the try/except block.

Something like this,

```
class AccountCreationError(Exception):
       def __init__(self, *args):
            if args:
                self.msg = args[0]
            else:
                self.message = None

      def __str__(self):
          if self.msg:
              return f'AccountCreationError, {self.msg} '
          else:
              return 'AccountCreationError has been raised'
```

**Comment by brylie** [comment]
@calicomills looks good. That way it would be descriptive.

**Comment by calicomills** [comment]
> @calicomills looks good. That way it would be descriptive.

OK..I will start working on this.
