### ISSUE TITLE
Profile Error - partials/account/tabs/my_bills.html doesn't exist

### ISSUE THREAD

**Issue by aniket-banyal** [CiviWiki/OpenCiviWiki#964]
Internal Server Error: /profile/ani

Error - django.template.exceptions.TemplateDoesNotExist: partials/account/tabs/my_bills.html

I checked and found that my_bills.html was deleted in b600ead9fc563eef6086fb1c46120d71dba97703

**Comment by brylie** [comment]
Good catch. We removed (most) functionality related to bills/legislation but seem to have overlooked this template. Please consider removing the reference to the template and any similar code you may find.

**Comment by aniket-banyal** [comment]
You may assign it to me

**Comment by aniket-banyal** [comment]
https://github.com/CiviWiki/OpenCiviWiki/blob/76d49d5a01de3ae0e89c71a8b4499c7b5625e8de/project/threads/templates/threads/account.html#L74

I made this change - `src="{% static 'js/account.js' %}"`
And removed references to mybills

Now on opening profile, it just continues to load indefinitely (Might be related to #914)

Also take a look at the error in console - 

![Screenshot (373)](https://user-images.githubusercontent.com/40134444/128339314-6339af02-45b3-4763-a7cc-7f743195cc92.png)

I visited the url shown in the console and got this error - 

Internal Server Error: /api/account_profile/ani/
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\OpenCiviWiki\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\HP\Desktop\OpenCiviWiki\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HP\Desktop\OpenCiviWiki\project\api\read.py", line 51, in get_profile
    result = Account.objects.summarize(a)
  File "C:\Users\HP\Desktop\OpenCiviWiki\project\api\models\account.py", line 40, in summarize
    "history": [
  File "C:\Users\HP\Desktop\OpenCiviWiki\project\api\models\account.py", line 41, in <listcomp>
    Civi.objects.serialize(c)
  File "C:\Users\HP\Desktop\OpenCiviWiki\project\api\models\civi.py", line 46, in serialize
    "hashtags": [hashtag.title for hashtag in civi.hashtags.all()],
AttributeError: 'Civi' object has no attribute 'hashtags'

**Comment by aniket-banyal** [comment]
Do I need to change the files in `project\staticfiles` folder or would they be automatically changed?

**Comment by brylie** [comment]
Well, we're in the process of replacing the JavaScript UI with static templates that get rendered by Django. So the ideal outcome here would be to replace this template with a Django-only template and delete the deprecated JS for this particular view. You can feel free to take creative liberty with the rendered output but it might be worth using the existing styles since they are fairly nice.

**Comment by brylie** [comment]
For the specific error, it looks like we changed the `hashtags` field to just `tags` and neglected to update the related code.

https://github.com/CiviWiki/OpenCiviWiki/blob/76d49d5a01de3ae0e89c71a8b4499c7b5625e8de/project/api/models/civi.py#L107

It might be worth searching the project for uses of the `hashtags` field and replacing it with `tags` to see how far we get.
