### ISSUE TITLE
[FEATURE] Add Issue Templates and pull request template

### ISSUE THREAD

**Issue by vishalda** [CiviWiki/OpenCiviWiki#982]
Add issue and pull request templates to help contributors share the right details at the start of a thread.

**Comment by brylie** [comment]
My only caution here is not to add too much ceremony to the templates. We want to welcome new contributors. Some PR/issue templates are a bit foreboding.

**Comment by AbhijithGanesh** [comment]
Was this issue solved or assigned? I am up for fixing it,I'd like to be assigned if no one took it before

**Comment by brylie** [comment]
Sure, you can take it @AbhijithGanesh. Please be considerate that we want to have a very simple process for filing bugs and ideas. Not too much ceremony.

**Comment by AbhijithGanesh** [comment]
Thank you @brylie . I shall keep that in mind

**Comment by AbhijithGanesh** [comment]
I shall be uploading a Mark Down file today regarding this
Would that be fine
(I am in the GMT +5:30 time zone, so I would be uploading this before end of day IST)

**Comment by vishalda** [comment]
@AbhijithGanesh Nice, but I guess It would be good if we had a .yml file as it is easier for users to raise an issue rather than modifying a mark-down file to raise an issue. @brylie What do you say?

**Comment by AbhijithGanesh** [comment]
> 
> 
> @AbhijithGanesh Nice, but I guess It would be good if we had a .yml file as it is easier for users to raise an issue rather than modifying a mark-down file to raise an issue. @brylie What do you say?

I am not extremely strong with YML files but I am sure I can figure it out, I am waiting for confirmation from @brylie .

**Comment by brylie** [comment]
@AbhijithGanesh and @vishalda, yes let's use a YAML file since that will render a form instead of requiring familiarity with Markdown.

The GitHub documentation has a section on [creating issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) with an example YAML file.

**Comment by AbhijithGanesh** [comment]
Should I Rebase? are there changes to the main Repository?

**Comment by AbhijithGanesh** [comment]
I have created a PR, please test it and let me know. This is my first experience of creating a yml template so please excuse me if i am slow .

**Comment by AbhijithGanesh** [comment]
the PR got merged but i am unsure whether I can help more or my initial PR was sufficient

**Comment by brylie** [comment]
@AbhijithGanesh the initial PR was sufficient. We can close this issue now :smiley:
