### ISSUE TITLE
Unable to run development enviroment using docker

### ISSUE THREAD

**Issue by wassafshahzad** [CiviWiki/OpenCiviWiki#992]
I recently pulled recent changes into master and was unable to run the development environment using docker-compose.
I believe that issue may be caused by addition of new settings which have not been documented in the documentation. 
Stack Trace for reference 

civiwiki-backend | xvfb-run: error: xauth command not found
civiwiki-backend | Starting ChromeDriver 2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926) on port 9515
civiwiki-backend | All remote connections are allowed. Use a whitelist instead!
civiwiki-backend | Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
civiwiki-backend | /usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
civiwiki-backend |   """)
civiwiki-backend | Traceback (most recent call last):
civiwiki-backend |   File "/app/project/manage.py", line 10, in <module>
civiwiki-backend |     execute_from_command_line(sys.argv)
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
civiwiki-backend |     utility.execute()
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
civiwiki-backend |     django.setup()
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
civiwiki-backend |     apps.populate(settings.INSTALLED_APPS)
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
civiwiki-backend |     app_config.import_models()
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
civiwiki-backend |     self.models_module = import_module(models_module_name)
civiwiki-backend |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
civiwiki-backend |     __import__(name)
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/notifications/models.py", line 15, in <module>
civiwiki-backend |     from jsonfield.fields import JSONField
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/jsonfield/__init__.py", line 1, in <module>
civiwiki-backend |     from .fields import JSONCharField, JSONField
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/jsonfield/fields.py", line 22
civiwiki-backend |     def __init__(self, *args, dump_kwargs=None, load_kwargs=None, **kwargs):
civiwiki-backend |                                         ^
civiwiki-backend | SyntaxError: invalid syntax
civiwiki-backend | /usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
civiwiki-backend |   """)
civiwiki-backend | /usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
civiwiki-backend |   """)
civiwiki-backend | Unhandled exception in thread started by <function wrapper at 0x7f23f8e77f50>
civiwiki-backend | Traceback (most recent call last):
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
civiwiki-backend |     fn(*args, **kwargs)
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
civiwiki-backend |     autoreload.raise_last_exception()
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
civiwiki-backend |     six.reraise(*_exception)
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
civiwiki-backend |     fn(*args, **kwargs)
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
civiwiki-backend |     apps.populate(settings.INSTALLED_APPS)
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
civiwiki-backend |     app_config.import_models()
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
civiwiki-backend |     self.models_module = import_module(models_module_name)
civiwiki-backend |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
civiwiki-backend |     __import__(name)
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/notifications/models.py", line 15, in <module>
civiwiki-backend |     from jsonfield.fields import JSONField
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/jsonfield/__init__.py", line 1, in <module>
civiwiki-backend |     from .fields import JSONCharField, JSONField
civiwiki-backend |   File "/usr/local/lib/python2.7/site-packages/jsonfield/fields.py", line 22
civiwiki-backend |     def __init__(self, *args, dump_kwargs=None, load_kwargs=None, **kwargs):
civiwiki-backend |                                         ^
civiwiki-backend | SyntaxError: invalid syntax

**Comment by brylie** [comment]
> civiwiki-backend | Starting ChromeDriver 2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926) on port 9515
> civiwiki-backend | All remote connections are allowed. Use a whitelist instead!
>civiwiki-backend | Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

What branch (commit) are you checking out? We removed ChromeDriver in a previous issue.

I'm not getting that syntax error above, but do have a different error:

> civiwiki-backend |   File "/app/project/accounts/models.py", line 116, in Account
> civiwiki-backend |     Category, related_name="user_categories", symmetrical=False
> civiwiki-backend | NameError: name 'Category' is not defined

**Comment by brylie** [comment]
After a bit of work, I've gone ahead and removed the Docker environment and updated the contributing guide to reflect the simplified way of running the server. Please use the revised instructions below.

- https://github.com/CiviWiki/OpenCiviWiki/blob/develop/CONTRIBUTING.md#development

**Comment by wassafshahzad** [comment]
> > civiwiki-backend | Starting ChromeDriver 2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926) on port 9515
> > civiwiki-backend | All remote connections are allowed. Use a whitelist instead!
> > civiwiki-backend | Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
> 
> What branch (commit) are you checking out? We removed ChromeDriver in a previous issue.
> 
> I'm not getting that syntax error above, but do have a different error:
> 
> > civiwiki-backend |   File "/app/project/accounts/models.py", line 116, in Account
> > civiwiki-backend |     Category, related_name="user_categories", symmetrical=False
> > civiwiki-backend | NameError: name 'Category' is not defined

I was working on master branch of my own fork.

**Comment by wassafshahzad** [comment]
> After a bit of work, I've gone ahead and removed the Docker environment and updated the contributing guide to reflect the simplified way of running the server. Please use the revised instructions below.
> 
>     * https://github.com/CiviWiki/OpenCiviWiki/blob/develop/CONTRIBUTING.md#development
Thank you, It worked.
