### ISSUE TITLE
Seperate requirements.txt

### ISSUE THREAD

**Issue by gorkemarslan** [CiviWiki/OpenCiviWiki#998]
Now, our [requirements.txt](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/requirements.txt) file includes all the dependencies that are used in development, testing, and production. It is a good practice to separate dependencies according to in which stages they are used. Eventually, a package used in the development won't be installed in the production stage.

As far as I know, there are two conventions here:

1. Create a folder named `requirements` and place `base.txt`, `dev.txt`, `prod.txt` etc. inside it. (e.g. [EvalAI](https://github.com/Cloud-CV/EvalAI/tree/master/requirements))
2. Create files without the parent requirements folder. (e.g. [weblate](https://github.com/WeblateOrg/weblate))

- [ ] Choose a way to place requirements files (as mentioned above)
- [ ] Separate requirements.txt file
- [ ] Update docs (e.g. `pip install -r requirements.txt` needs to be changed.)

**Comment by brylie** [comment]
I'm more familiar with the first approach. It lets us have some common settings across files while only maintaining what is specific to each environment.

**Comment by gorkemarslan** [comment]
Could you please assign me to this issue?

I also find the first approach more convenient. It is reasonable to collect the similar files in a folder. Otherwise, as in the latter approach, the bulk of files are present in the main directory.

Is [test_framework](https://github.com/CiviWiki/OpenCiviWiki/tree/f152ad5986ebfd25ff60ad5ca7c34563818f1e17/project/test_framework) directory being used now? I am asking this because `aloe`, which is commented, and `selenium` packages are not available in the requirements.txt file.

**Comment by brylie** [comment]
We can deprecate the selenium tests in that folder, so no it's not really being used. The `aloe` package was causing issues when creating the Python environment, so should remain commented out until it is needed and will not break the development environment.
